### ISSUE TITLE
Add animation.

### ISSUE THREAD

**Issue by max5354** [z-huang/music#100]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add animation's like "bouncy" or "stretch OverScroll".

### Why do you want this feature?

It will increase look of app.

**Comment by z-huang** [comment]
Where will the animation be added?

**Comment by z-huang** [comment]
Okay. But the feature will not have a high implement priority.

**Comment by z-huang** [comment]
I think it's too fancy and not necessary.
