### ISSUE TITLE
Even after closing the app the music still plays

### ISSUE THREAD

**Issue by dainvincible1** [z-huang/music#1026]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

play a song then close the app also remove it from recent tasks. the song still plays
before the new version, the song used to stop after closing the app

### Expected behavior

the song should close

### Actual behavior

play a song then close the app also remove it from recent tasks. the song still plays

### Screenshots/Screen recordings

https://github.com/z-huang/InnerTune/assets/127825700/a2ab1c2d-61f0-40eb-8920-27e4e0aa8df4

### InnerTune version

latest version

### Android version

11

**Comment by z-huang** [comment]
That's a change in 0.5.3. You have to pause and dismiss the notification to stop the player.

**Comment by dainvincible1** [comment]
> That's a change in 0.5.3. You have to pause and dismiss the notification to stop the player.

can you please add a option in settings which would ensure that music playback stop when app will be cleared from ram. that will be really helpful

**Comment by DarkCrypt** [comment]
> That's a change in 0.5.3. You have to pause and dismiss the notification to stop the player.

This is fucking annoying.

I close the app, the notification player stays open and is completely useless. If I reopen the app, it works properly again.

The only way I can get rid of it is to dismiss it as stated (which is only possible from lockscreen) or force stop the app.
