### ISSUE TITLE
Show new releases only from liked artists

### ISSUE THREAD

**Issue by noegodinho** [z-huang/music#1027]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

The app shows a set of new release albums from random artists but I do not listen to any of them. 

### Why do you want this feature?

That way would be able to know when a new release from an artist I like arrives.

### Additional information

App version: 0.5.3

**Comment by catgangdev** [comment]
Yeah it's a good feature for more personalized songs. Else my new release list filled with the artists I don't listen .

**Comment by z-huang** [comment]
Maybe we can make the albums of your favourite artists displayed first.

**Comment by catgangdev** [comment]
> Maybe we can make the albums of your favourite artists displayed first.

That's maybe a good idea. As I don't want to completely hide the artists I don't listen. Because sometimes I do like some songs even from them too. So if our favourite artists displayed first on the list seems a good idea

**Comment by noegodinho** [comment]
> Maybe we can make the albums of your favourite artists displayed first.

That would be great.
