### ISSUE TITLE
Tracks with certain titles won't download or play (contains strong language)

### ISSUE THREAD

**Issue by rifqire** [z-huang/music#1030]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

I noticed that track titles containing a word "fuck" won't be able to download or play.

Here's the steps:
1. Search for the album titled "Norman Fucking Rockwell!" by Lana Del Rey
2. Download the album
3. Play either track 1 or 4

### Expected behavior

Both tracks should be able to play and the album should download all the tracks.

### Actual behavior

Both tracks won't play and the album downloaded all the tracks except those two. I think it's weird since track 3 of NFR also contains a bad word, but somehow it can be played and downloaded.

The other album of her is Ultraviolence, go to track 9 and it's the same situation.

### Screenshots/Screen recordings

![Screenshot_2023-09-04-01-01-23-718_com zionhuang music](https://github.com/z-huang/InnerTune/assets/30471081/99f97de0-0080-4c02-9c34-f0db992d4d71)
![Screenshot_2023-09-04-01-17-09-148_com zionhuang music](https://github.com/z-huang/InnerTune/assets/30471081/99e2b8fb-60c2-4f1a-89e9-4970d12e86c2)

### InnerTune version

0.5.3

### Android version

Android 13

**Comment by z-huang** [comment]
Mine works. Sometimes Piped server is down and age-restricted songs can't play.

<img width=200 src="https://github.com/z-huang/InnerTune/assets/39427017/ed58225c-04dc-43f7-b199-706630a2a2d7" />
