### ISSUE TITLE
old features are best

### ISSUE THREAD

**Issue by rajat-ankel** [z-huang/music#1031]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

old swipe changeing tracks is best why they get removed, old square large thumbnail  layout on playing menu is also looking good and unique why this all get removed  

### Why do you want this feature?

old features are the best

### Additional information

you can add a toggle button on settings to turn or off this features

**Comment by z-huang** [comment]
Swipe to change songs: #1017 
In 0.5.3 the horizontal padding in the player screen is increased by 32 dp. I think it is visually better and easier for single hand.
