### ISSUE TITLE
Offline mode to play cached songs

### ISSUE THREAD

**Issue by yonoff** [z-huang/music#1037]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I really miss the offline mode in the application.  A similar mode is present in ViMusic - offline playlist.    It would be great if you could add a similar playlist to the app.

<img width=200 src="https://github.com/z-huang/InnerTune/assets/9549832/1be691d4-1356-467c-8279-b52168f11c36" />

### Why do you want this feature?

Very useful in roaming and places with poor connectivity.

**Comment by Donald-Win** [comment]
Downloaded/cached music can be found in the songs tab. Everything in the library section is cached and everything in the downloaded section is the manually downloaded songs.

<img width=200 src="https://github.com/z-huang/InnerTune/assets/140929208/6a6d68c4-df30-41ca-9c46-296ec5990a7e" />

**Comment by yonoff** [comment]
This is not exactly what I meant.
Recently played tracks are cached in the cache regardless of whether I added them to the library or downloaded them.
And this offline playlist allows me to play them offline randomly without using traffic while roaming or in flight mode.
Screenshots:

1. ViMusic offline playlist with shuffle launch option
2. InnerTune cache settings. it looks similar to cache settings in ViMusic, according to the used storage, I see that there are previously played tracks, and not added to the library. (My library is almost empty)

<img width=200 src="https://github.com/z-huang/InnerTune/assets/9549832/7e4c490b-1c04-4496-9c69-001624bf2ea7" />

<img width=200 src="https://github.com/z-huang/InnerTune/assets/9549832/d4f03b5c-3dcb-4a44-8b9b-1d825f9185b6" />

**Comment by Donald-Win** [comment]
Note the same button in the screenshot that I posted. It does exactly what you are asking for.

**Comment by Donald-Win** [comment]
<img width=200 src="https://github.com/z-huang/InnerTune/assets/140929208/6fe56a28-308a-4e22-bbf9-d6dc4a2ddf50" />

Added an extra screen shot here to better show.

Some songs on here such as "Forgot about Dre" and "N 2 Gether Now" were not manually added by me in anyway. They had simply played at some point and thus added to the cache. I did nothing at all to manually add them to the "library "

Other songs such as "The Git Up" and "Ex Machina" I have manually downloaded as I want them to remain available in the event that the cache becomes full and songs start dropping out.

This whole section can be essentially treated as your "offline playlist" with the addition that you essentially have the option of "All" (library), "Liked" or "Downloaded" all of which can be played without a data connection.

**Comment by yonoff** [comment]
This is not entirely true.
I am using FOSS version 0.5.3.
I installed the app a couple of days ago and managed to add to my library or mark as liked only 13 tracks.
In songs tab, only those tracks that I marked as liked or added to the library are displayed.
At the same time, all the tracks played earlier are displayed in the history section. The number of tracks in the history corresponds to the used cache size displayed in the storage settings. But unfortunately in the history section there is no shuffle or offline play buttons.
Sadly, that used cache cannot be fully used offline, as the application does not have offline mode to play all cached tracks. 
In my opinion, this would make it possible to fully use the cache with the already existing cache storage size settings.
At the moment, offline playback of cached tracks is present in the application description, but there is no way to use it.

<img width=200 src="https://github.com/z-huang/InnerTune/assets/9549832/e7c2baa1-fbda-4e5f-a627-0162da8802b9"/>

**Comment by Donald-Win** [comment]
I am also using FOSS 5.3. It works for me exactly as I have described. 

I usually chose a song I like at home on wifi and use that to start radio play to discover new tracks. Then, when I am working out in the field, I play the library on random and all of these tracks that I have not liked, downloaded or added in any other way end up in the mix.

It does seem like this is not the same for you tho so hopefully z-huang will be able to clarify things when they are able to.

For the record, it did take me a little bit to adjust to not having it in the playlists and would not mind at all if it was reverted back or even having both implementations run side by side.

**Comment by yonoff** [comment]
I found screenshots of the settings of older versions of the application on various forums. There in the settings there was an option to automatically add played tracks to the library (General > Auto add song to library / Auto download). Perhaps you configured this in a previous version of the application and these settings continue to work in the current version. As a result, previously played songs appear in your library and you can play them offline. 
**In version 0.5.3 these settings are missing, perhaps this is a bug?**

<img width=200 src="https://github.com/z-huang/InnerTune/assets/9549832/03f7fc5e-8393-4c5f-85ab-762fe3addf0a" />

<img width=200 src="https://github.com/z-huang/InnerTune/assets/9549832/a206c4ba-2ebe-4166-9660-70f6ae9353e3" />

**Comment by z-huang** [comment]
Let me clarify how this works:
- Song cache: Played chunks are cached. When the cache size is over the limit, least used cache will be deleted.
- Download: The whole song is saved, and there isn't a limit of downloaded song size.

When you're offline, both downloaded songs and cached chunks can play.

Some points you should know:

- Auto add to library / auto download: they exists before v0.5.0, and they have no relation to the cache system. I'm still evaluating whether to add them back in the future version.
- Library is just a place to store your tracks. Songs in the library may be cached, may be partially cached, or may not be cached. It depends on whether you've played them and the cache isn't deleted by the LRU strategy.
- The cache system is designed to save bandwidth, while the download system is designed to play offline.

**Comment by rickdtc** [comment]
# my suggestion 

I think that having another tab like downloaded called cached on library which stores fully cached songs.

# what about the partially cached song?

Having this option from murglar in settings would be great.

![Screenshot_20230909_090751_Murglar 2](https://github.com/z-huang/InnerTune/assets/74096544/b6d4b868-ab62-46c5-856c-ce5c8fe846e0)

**Comment by z-huang** [comment]
> The cache system is designed to save bandwidth, while the download system is designed to play offline.

I'm following this guideline. Download the song if you want to listen to it offline.
