### ISSUE TITLE
Auto resume on restoring connection to playback device

### ISSUE THREAD

**Issue by LantashTheTokra** [z-huang/music#1038]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add a toggleable option to resume playback when a bluetooth or wired device is connected/reconnected.

### Why do you want this feature?

Just a quality-of-life feature that I like from another app.

### Additional information

UI implemetation in similar app ViMusic ![Screenshot_20230906-214213](https://github.com/z-huang/InnerTune/assets/84555704/cb2d64a9-60da-45ef-9480-decc96ba53c1)

**Comment by z-huang** [comment]
Isn't this provided by Android? When I switch from the speaker to my earphones, the audio automatically resumes.
