### ISSUE TITLE
Color match now playing screen with thumbnail.

### ISSUE THREAD

**Issue by max5354** [z-huang/music#104]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Color match now playing screen with thumbnail. Like poweramp. This will increase looks of app.
![Screenshot_20220611-202419_Poweramp](https://user-images.githubusercontent.com/90886938/173192974-1e334a7b-b463-470b-b92e-196fbffbef14.jpg)

### Why do you want this feature?

Because it's looks great instead of just normal now playing screen.

**Comment by z-huang** [comment]
Transfer to #159.
