### ISSUE TITLE
Change the cache location of songs.

### ISSUE THREAD

**Issue by sanyoog** [z-huang/music#1040]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Basically it's a small idea, it's a request to add a feature or an option to cache location, like i want to cache the songs on my sd card, so can we get a feature where we just change the cache from phone storage to sd card without bringing back the directory system. Like u can keep the directory as u want just we want the cache to be shifted from phone storage to sd card

### Why do you want this feature?

It's usefull for low storage device like mine and help conserve storage space

**Comment by z-huang** [comment]
Duplicate of #987
