### ISSUE TITLE
If possible, please add a option in settings which would ensure music playback to stop when app is closed from recent tasks and ram

### ISSUE THREAD

**Issue by dainvincible1** [z-huang/music#1041]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

![image](https://github.com/z-huang/InnerTune/assets/127825700/3916b542-a250-4c2c-b7e1-3525c9a71fd3)

something like this

### Why do you want this feature?

It takes more steps to close and stop the song and remove it from the notification or status bar.

**Comment by Zaxx69** [comment]
This toggle is very much needed, dev please look into it

**Comment by dainvincible1** [comment]
@z-huang is there any possible for this feature??

**Comment by z-huang** [comment]
Yes, see #1272.

**Comment by dainvincible1** [comment]
> Yes, see #1272.

thanks
