### ISSUE TITLE
Change the way search screen navigation works

### ISSUE THREAD

**Issue by nvllz** [z-huang/music#1042]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

The "Back" arrow in the search screen takes the user back to the previous query with each tap. This is sometimes inconvenient, as we can't quickly get to the previous screen until we tap the arrow x+1 times. Especially when searching for many songs in a row.

I'd either change the way the arrow works (to make it go back to the previous screen instead of the previous search), or make a long tap on the arrow make the user go back to the previous screen regardless of any previous searches.

### Why do you want this feature?

I found it really inconvenient to have to tap so many times after some searches to get to the playlists screen from where I'd decided to search for some new songs. Some user recently made an issue about this problem, but the "home button" idea was dismissed without any comment. If you don't like the idea, please let us know why.
Cheers

**Comment by ansarimohammed422** [comment]
Yaa i also want it to be implemented as stated above
Because it becomes inconvenient every time we press back button it hoes to previously searched song and not to the home screen

**Comment by z-huang** [comment]
Done. 6660e8b774303d2464f06b7c09f0768ecb19c014
