### ISSUE TITLE
No songs queued up when selecting radio

### ISSUE THREAD

**Issue by Carter0108** [z-huang/music#1044]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Select a song from quick picks or selecting radio from a the menu of any song.

### Expected behavior

Song should play and then queue up more songs afterwards.

### Actual behavior

Only first song is queued and then nothing plays after it's finished.

### Screenshots/Screen recordings

![Screenshot_20230908-191509](https://github.com/z-huang/InnerTune/assets/55948138/255f297e-aaf5-4c58-8889-a781fcca5801)

### InnerTune version

0.5.3

### Android version

Android 13

**Comment by z-huang** [comment]
Please provide logs. Keyword: `YouTube.next`

**Comment by teemue** [comment]
I have the same problem. Nothing seems to pop in logs when starting radio. Also, album views show nothing.

**Comment by z-huang** [comment]
I'll reopen the issue if anyone provides logs.

**Comment by teemue** [comment]
After playing a song and clicking Start radio [2023-09-12-14-22-04.am.log](https://github.com/z-huang/InnerTune/files/12585844/2023-09-12-14-22-04.am.log)

**Comment by z-huang** [comment]
No useful information found. `YouTube.next` is the string I'm interested in.

**Comment by teemue** [comment]
> No useful information found. `YouTube.next` is the string I'm interested in.

It's not mentioned at all in logs !
