### ISSUE TITLE
Remove in app volume

### ISSUE THREAD

**Issue by kaneryu** [z-huang/music#1045]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

It's redundant to have a volume slider in app when we already have one on the phone. This may cause situations where users will be confused as to why their music is suddently quieter.
If the purpose of the feature is to allow for the music to play a bit quieter over another app, like a game, most moble operating systems already have this feature.

**Comment by z-huang** [comment]
The volume slider within this app allows you to adjust the volume more precisely; the system's volume control is too coarse.
