### ISSUE TITLE
Allow download to choosen folder

### ISSUE THREAD

**Issue by murkom** [z-huang/music#1046]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Is it possible to implement this? Download audio to some folder user chooses. Thanks

### Why do you want this feature?

This would allow to copy downloaded audio to my music folder.

**Comment by z-huang** [comment]
Duplicate of #987

**Comment by murkom** [comment]
Actually this is not about having cached files on external folder. But opus/webm/aac whatever. Those files that are cached are exo files. But thanks anyway

**Comment by z-huang** [comment]
Downloaded songs are also exo files. 😅

**Comment by murkom** [comment]
> Downloaded songs are also exo files. 😅

Not playable in regular players, like vlc, etc....
