### ISSUE TITLE
Artist's albums not showing 

### ISSUE THREAD

**Issue by dainvincible1** [z-huang/music#1048]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Search "taylor swift" then go to "albums"

### Expected behavior

it should show albums

### Actual behavior

it loads forever and doesnt show albums

### Screenshots/Screen recordings

![image](https://github.com/z-huang/InnerTune/assets/127825700/7b04e8eb-ac02-46aa-ba19-ed2b0fce7fc3)

### InnerTune version

latest debug version

### Android version

android 11

**Comment by owenconnorz** [comment]
In my opinion this is something to do with corruption when clearing data it will work again but if you backup and restore some reason it backs up the bug and the issue will return I think the back up needs to be changed to only get your music as iv seen it as it backups the account and maybe more we don't know about @z-huang maybe this is a big issue as iv been facing it a lot

**Comment by dainvincible1** [comment]
> In my opinion this is something to do with corruption when clearing data it will work again but if you backup and restore some reason it backs up the bug and the issue will return I think the back up needs to be changed to only get your music as iv seen it as it backups the account and maybe more we don't know about @z-huang maybe this is a big issue as iv been facing it a lot

but this time i did nothing, no backup and restore. even after uninstalling and installing this issue is happening

**Comment by owenconnorz** [comment]
have u cleared data

**Comment by dainvincible1** [comment]
> have u cleared data

yes, done couple of times. that didnt work, so i uninstalled and installed again, it didnt work either.  tried the foss version, that also didnt work

**Comment by owenconnorz** [comment]
Strange I just tried it and it worked by clearing cache and data in system settings but after a while it comes back not sure its when I update to the newest debug or something goes wrong so I now use the main app as I don't wanna face this issue maybe if the app wasn't built as a debug and just a normal apk but as a beta this would solve the issue

**Comment by z-huang** [comment]
YouTube changed the api response. I'll fix it later.

**Comment by owenconnorz** [comment]
Ahh so that's why thanks @z-huang hopefully it will be the end of the issue 😊

**Comment by dainvincible1** [comment]
> YouTube changed the api response. I'll fix it later.

thank you
