### ISSUE TITLE
Download songs to device storage

### ISSUE THREAD

**Issue by Glitchy-Tozier** [z-huang/music#1049]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I love this app. The one thing I'd like to see added is the ability to download songs to the device storage instead of some app-specific storage.

### Why do you want this feature?

This way, even in case the phone dies or something happens to the app, I get to just move the SD-card out of my phone and to another device.
Plus, I'd like to be able to find the songs inside my music-player app.

**Comment by z-huang** [comment]
Thanks for your support. But did you really check if there're already issues about this? 😉 #987 #1040 #1046

**Comment by Glitchy-Tozier** [comment]
> But did you really check if there're already issues about this? 😉 #987 #1040 #1046

I really did, but it seems like I forgot to enable display of closed issues.😅

By the way, why is this not planned? Because of the way you store files (with some special file extension)?

**Comment by z-huang** [comment]
Yes, the song is downloaded into chunks, so it can't be opened directly.

**Comment by Glitchy-Tozier** [comment]
That's unfortunate
