### ISSUE TITLE
Add option to pause after every song

### ISSUE THREAD

**Issue by Glitchy-Tozier** [z-huang/music#1050]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I'd appreciate having the option to make the app pause after a song is finished. Currently, as far as I can tell, the only options we have available are:

- Automatically play next song
- Automatically repeat this song infinitely
- Automatically repeat this song once

I'm proposing to add a fourth option:
- Pause playback after the song finishes, letting the user manually continue when desired

### Why do you want this feature?

I like to get a pause after hearing a song, letting certain feelings linger. Unfortunately, this is not possible with the current automatic continuation mechanisms. This is why I'm proposing this feature.

### Additional information

Currently, it's possible to fake this functionality by using the sleep-mode with "End of Song". However, this way, the user needs to re-enable this mode every time after starting the next song.

**Comment by z-huang** [comment]
I'm wondering if this is really a needed feature for most people. I have never encountered an app with this feature.
