### ISSUE TITLE
Nothing showing in app...

### ISSUE THREAD

**Issue by calm032019** [z-huang/music#1051]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Just open the app

### Expected behavior

Music, albums etc should show

### Actual behavior

The screen is just blank and when I search it just loads.

I think this is something to do with a device admin app I use on my phone as it often blocks some apps and websites.

Is there a way to find out where InnerTune is 'pulling' the source of all the content from? I will try and whitelist this on my device admin app.

### InnerTune version

v0.5.3

### Android version

Android 13

**Comment by Pratham-vais** [comment]
@z-huang  your innertune application is not showing any search item. Please do something

**Comment by z-huang** [comment]
You should whitelist music.youtube.com.
Mine works. You should provide logs so that I can investigate.
