### ISSUE TITLE
Liking song adds to library section, removing like does not remove from library

### ISSUE THREAD

**Issue by github-user93** [z-huang/music#1052]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. like any song, it gets added to both the 'library' and 'liked' section.
2. remove the like. it does not remove from 'library' section.

### Expected behavior

if liking a song adds it to both 'liked' and 'library' section then removing the like should also remove it from both those sections.

### Actual behavior

removing the like only removes from 'liked' section, song still stays in 'library' section.

### InnerTune version

0.5.2

### Android version

android 10

**Comment by github-user93** [comment]
https://youtu.be/1yJiJMbEWQA
a video showing the issue.

**Comment by z-huang** [comment]
This is an intended behaviour.
