### ISSUE TITLE
Piped Support Feature Request

### ISSUE THREAD

**Issue by siggi1984** [z-huang/music#1053]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Would it be possible to support piped accounts and custom instances for library backups and then have your playlists cross-device?

### Why do you want this feature?

This app looks great so far and I'd love to see it work as a replacement for any other proprietary music app.

**Comment by thefoqs** [comment]
I'd like that too. Excelent non proprietary app for listening music + support piped accounts = Perfection.

**Comment by z-huang** [comment]
I won't work on it, but contribution is welcome.
