### ISSUE TITLE
Add remove option in Albums

### ISSUE THREAD

**Issue by GurrenLagann114** [z-huang/music#1061]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I noticed there's no option that allows you to remove a song from an album you created. This might me problematic if you for mistake add the same song twice.

### Why do you want this feature?

Lack of a remove option in custom albums.

**Comment by sleepy56** [comment]
I have a question does a button need to be added because we can remove the song by swiping the song left or right in the album

**Comment by GurrenLagann114** [comment]
> I have a question does a button need to be added because we can remove the song by swiping the song left or right in the album

Didn't know that. Thank you mate.
