### ISSUE TITLE
Change app startup sections 

### ISSUE THREAD

**Issue by Eri1320** [z-huang/music#1064]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I would like there to be the option to remove the "new releases", or that instead, suggested radios come out, or something similar, as they appear on Youtube Music. 

### Why do you want this feature?

Because all the new releases that I get are horrible, and annoying.

### Additional information

It would be nice to have other sections, and to be able to remove or choose which ones to leave and which ones to remove.

**Comment by z-huang** [comment]
The home screen is revamped! You can try it out by downloading the debug build.
