### ISSUE TITLE
Podcasts load infinitely, and they don't open

### ISSUE THREAD

**Issue by Eri1320** [z-huang/music#1065]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

I search for a podcast, and when I try to get into the podcast, it loads infinitely. 

For example, if you search for Duolingo Podcast, it comes out in Podcast, but you give it to enter, load infinitely and never open

### Expected behavior

It should show me the podcast episodes, but it doesn't show me anything, because it doesn't finish loading

### Actual behavior

Charge infinitely

### Screenshots/Screen recordings

![Screenshot_2023-09-18-00-47-33-130_com zionhuang music](https://github.com/z-huang/InnerTune/assets/111612989/cf6ee9ef-bdf9-4df6-9cde-106439d5c9df)

![Screenshot_2023-09-18-00-47-36-338_com zionhuang music](https://github.com/z-huang/InnerTune/assets/111612989/300cdc1a-5cfe-421a-87e4-636675a1ff1c)

### Logs

I don't know how to get the logs. Maybe you should add the option in the "about" section. 

### InnerTune version

0.5.3

### Android version

Android 12

**Comment by z-huang** [comment]
Podcast not supported.

**Comment by triggerfx** [comment]
> Podcast not supported.

Why ? Is it not possible to playback like music with same UI ? Whats different than music, both are on YouTube
