### ISSUE TITLE
Download all button

### ISSUE THREAD

**Issue by zexha** [z-huang/music#1068]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I would like to have a Download All button to download all songs from library.

### Why do you want this feature?

I recently tried the backup/restore feature. First, I backed up from my phone and restored it into a tablet. It seems like I got everything, but all songs have not downloaded yet in the tablet. I can see all songs that I already downloaded from my phone, so it would be great to have a download all button to get all songs back in the new device instead of re-download again one by one.

**Comment by zerobun** [comment]
If u have playlist u can still download all of the songs inside it with 1 press (download all button)

What I suggest is you just add all your music on one playlist and then download it and then delete the whole playlist after they are downloaded, only the playlist gets deleted and the download songs stay.

**Comment by zexha** [comment]
Zeroburn: thanks for your input. 
I did not create a playlist at the first place, so when I imported data into new device. It just showed all songs in the library and no feature to select multiple songs and add it into a playlist at once, need to add it manual one by one, it's the same as i play it and click download it one by one. I think it is time-consuming. User needs to play the song, click add to libray to have it in library, click download, and click add to playlist. 

I would be easier to just have download all button in library section, so when I play a song and I like it, I can just click add to library and come back later download it all at once. Or improve library feature such as select feature that allow user to select multiple songs and add to a playlist at once, so user can download all songs in playlist at one click.

**Comment by zerobun** [comment]
> Zeroburn: thanks for your input. I did not create a playlist at the first place, so when I imported data into new device. It just showed all songs in the library and no feature to select multiple songs and add it into a playlist at once, need to add it manual one by one, it's the same as i play it and click download it one by one. I think it is time-consuming. User needs to play the song, click add to libray to have it in library, click download, and click add to playlist.
> 
> I would be easier to just have download all button in library section, so when I play a song and I like it, I can just click add to library and come back later download it all at once. Or improve library feature such as select feature that allow user to select multiple songs and add to a playlist at once, so user can download all songs in playlist at one click.

I see, I guess for now you could use the touch recorder app and recording u downloading a song and then replaying the macro recorded the same number of times as the songs in ur app. And it will add them all automatically while you just do something else.

**Comment by dt192** [comment]
I have the same issue. I had all my albums downloaded, then due to the YT api changing had to switch to an RC version at which point I lost all my downloads. I redownloaded them all one by one. Now I've switched from that to the latest version, again I've lost all my downloads.

Either a 'download all' button or the option to store downloads in the user area rather than app area so they don't get wiped on uninstall would be good. Both if possible.

**Comment by z-huang** [comment]
Now you can use multi-select to download all songs.

**Comment by dt192** [comment]
@z-huang How does this work? I tried long pressing an album which would be the way multi selects tend to work, but nothing happens? Also are there not any docs? Maybe it would be a good idea to create some docs and document how things work.

**Comment by z-huang** [comment]
Long click on a library song, and you're in multi-select mode, where you can select more songs and download them together.

**Comment by dt192** [comment]
The feature request here was `I would like to have a Download All button to download all songs from library.` I don't think multiselect solves that issue.

I currently have 176 albums in my library and no way to download them. In order to use multiselect, I would need to go into each album and select all the tracks (which would be slower than using the download option in the triple dot menu on the outside). The problem either way is that I would need to do this 176 times and I'm very likely to end up with a lot more albums over time, so this would be even worse in the future.

**Comment by z-huang** [comment]
If I understand correctly, we need multi-select for albums so that we can select all albums and press download.

**Comment by dt192** [comment]
I just took a look at the multiselect and the way you have implemented it is nice, so yes that would work well if you could do it for albums or songs in the playlist section without much trouble.

Failing that yiu could just add a triple dot menu to the right of the tiles/list view toggle and just have a download all option in that.

I think the multiselect would be more useful as could also be used for deleting multiple albums at once or adding multiple albums to a playlist etc.
