### ISSUE TITLE
Add spotify-like search pull down menu in playlists

### ISSUE THREAD

**Issue by yssasha** [z-huang/music#1069]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

When you open some playlist, and no matter how far you scrolled, you can pull down a menu from the top of the app so you'll get search the song in playlist bar. Also there can be added lock/unlock playlist order feature and sort by feature

### Why do you want this feature?

For a better user experience and comfort

**Comment by z-huang** [comment]
Search in playlist done in #721.
