### ISSUE TITLE
Select artists on details page

### ISSUE THREAD

**Issue by xmha97** [z-huang/music#1073]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Play a song
2. Select details button
3. Tap on a artists

### Expected behavior

Show artist page

### Actual behavior

Copy all artists to clipboard 📋

### Screenshots/Screen recordings

![Screenshot_2023-09-20-08-18-04-725_com zionhuang music](https://github.com/z-huang/InnerTune/assets/23485114/87837c07-b522-40ae-b6d7-29664dd7657f)

Artists are selectable on player page:
![Screenshot_2023-09-20-08-17-54-810_com zionhuang music](https://github.com/z-huang/InnerTune/assets/23485114/f20afaae-ea58-4fa3-a811-95710f2c15e9)

### Logs

N/A

### InnerTune version

0.5.3

### Android version

Android 13

**Comment by z-huang** [comment]
This is not a bug.

**Comment by xmha97** [comment]
Ok, I was wrong, this is a feature request, not a bug.

This feature is necessary for mixes because it is not possible to select all artists on the playback screen.

![Screenshot_2023-09-20-08-13-30-893_com.zionhuang.music.jpg](https://github.com/z-huang/InnerTune/assets/23485114/fc86be8e-f14c-4f99-8ae6-b88534dd0a10)

Please reconsider adding this feature.
Thanks 🙏

**Comment by xmha97** [comment]
Ok, I was wrong, this is a feature request, not a bug.

This feature is necessary for mixes because it is not possible to select all artists on the playback screen.

![Screenshot_2023-09-20-08-13-30-893_com.zionhuang.music.jpg](https://github.com/z-huang/InnerTune/assets/23485114/fc86be8e-f14c-4f99-8ae6-b88534dd0a10)

Please reconsider adding this feature.
Thanks 🙏 @z-huang

**Comment by z-huang** [comment]
There's "View Artists" in the player menu to select from multiple artists.

**Comment by xmha97** [comment]
> There's "View Artists" in the player menu to select from multiple artists.

Thanks 👍

![Screenshot_2023-09-21-13-49-49-619_com.zionhuang.music.jpg](https://github.com/z-huang/InnerTune/assets/23485114/85edc058-c66b-4b0a-b1db-b23abb516e3d)
