### ISSUE TITLE
Make Long pressing on queued songs to bring bottom manu sheet

### ISSUE THREAD

**Issue by ansarimohammed422** [z-huang/music#1074]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Like in VImusic when we long press a song which is in the queue we get bottom manu of that song and we can make that song favourite from their and perform various things on that.

But innertune doesnt have that feature,
When we longpress a song in queue in innertune it just selects that song and we can drag it up wards or down wards in queue

So can you make it like VImusic.

### Why do you want this feature?

I want this feature because sometime certain songs comes in the queue which we forget names of and want to make them favourite but to make them favourite we have to first play those songs from the queue and then presss the heart icon and other things like if we want to download etc

So it would be a great idea to add this feature

### Additional information

![Screenshot_2023-09-20-14-40-29-081_com zionhuang music](https://github.com/z-huang/InnerTune/assets/78704469/a6151a85-7d90-45a1-bd2a-30bd3c9f69f5)

I am talking about this menu

**Comment by nvllz** [comment]
Yess, I miss that too! Would be really useful to enhance the queue management.

**Comment by torevald** [comment]
I miss this feature too!

**Comment by z-huang** [comment]
Now long click leads to multi-select, and there's a three-dot icon to open the menu.
