### ISSUE TITLE
The app closes after playing some songs

### ISSUE THREAD

**Issue by ZeroOVi** [z-huang/music#1077]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Start the app
2. Play some songs
3. It closes randomly

### Expected behavior

The app shouldnt close randomly

### Actual behavior

The app closing after listening some songs

### Logs

Where is the log file? I cant find it

### InnerTune version

0.5.3

### Android version

Android 7.0

### Additional information

0.5.0 works perfect

**Comment by z-huang** [comment]
> Please use `adb logcat` or other ways to provide logs. This field is strongly recommended to be filled. Without this information, it's likely that the developer is unable to take any meaningful action or provide further assistance.

As said in the issue submission form, I can't do anything without logs.

**Comment by ZeroOVi** [comment]
> > Please use `adb logcat` or other ways to provide logs. This field is strongly recommended to be filled. Without this information, it's likely that the developer is unable to take any meaningful action or provide further assistance.
> 
> As said in the issue submission form, I can't do anything without logs.

Where is the log file? In what folder the app save it?

I dont have pc to use adb
