### ISSUE TITLE
Ability to download music through mobile data

### ISSUE THREAD

**Issue by mizukaha** [z-huang/music#1082]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

The ability to download music through mobile data and not just wifi.

### Why do you want this feature?

Well, I don't have wifi often.

**Comment by filinux13** [comment]
? I never had any problem downloading using mobile data

**Comment by z-huang** [comment]
The app doesn't limit the download through Wi-Fi. Can you double check or provide more information?
