### ISSUE TITLE
Clear Queue

### ISSUE THREAD

**Issue by guleriaakshit** [z-huang/music#1088]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Hi, I just want to request if you can add a feature to clear the queue with one button click, thanks.

### Why do you want this feature?

It makes the playback experience nicer. 🙂

**Comment by z-huang** [comment]
You can clear queue by swiping down the player bottom sheet.

**Comment by guleriaakshit** [comment]
> You can clear queue by swiping down the player bottom sheet.

Thanks
