### ISSUE TITLE
Animated "remove search word" button.

### ISSUE THREAD

**Issue by max5354** [z-huang/music#109]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Will you add this type of animated "Remove Word" button. I know that normal button work only to remove words. But this animated "remove words" button looks just osm if you will add it. Overall it will increase design of app.

https://user-images.githubusercontent.com/90886938/173222458-a9c095a5-ff78-4097-aa1a-9b67b90b8cef.mp4

### Why do you want this feature?

It looks just osm.

**Comment by z-huang** [comment]
Sorry, but this animation can confuse users too. They may think the search is still loading. If the function of the button is to clear search text, it just doesn't need that animation. A static icon looks good enough, in my opinion.
