### ISSUE TITLE
Your app is being rebranded as Voxify on the playstore by a third party

### ISSUE THREAD

**Issue by egirlcatnip** [z-huang/music#1093]
I apologize for using a GitHub issue to let you know, as I found it to be the easiest way to contact you. I am not affiliated with them, I just stumbled across the app and recognized the direct similarity.
![Screenshot_20230929-125128_Google Play Store](https://github.com/z-huang/InnerTune/assets/26607304/1f8a7480-c106-43a4-a5f5-be625e3e9086)

An app with the name ``Voxify`` released on the Google playstore seems to be just a rebranding of your app, without credit. This seems like a thing you should be aware of. 

Playstore link:
https://play.google.com/store/apps/details?id=com.voxify

**Comment by chaoscalm** [comment]
@egirlcatnip Hello, please check also this: https://play.google.com/store/apps/details?id=com.zionhuang.music

**Comment by egirlcatnip** [comment]
@chaoscalm 
![Screenshot_20230929-145019_Google Play Store.png](https://github.com/z-huang/InnerTune/assets/26607304/70e87d84-5cd0-4061-b5e9-4dfef90292c6)

They do at least give credit..? Still, up to the dev to resolve. 👍

**Comment by SirPhilip3** [comment]
Sadly InnerTune has a GNU GPLv3 license that permits to all users to modify and redistribute the code so he can't really do anything about it  see : [GNU GPL FAQ's](https://www.gnu.org/licenses/gpl-faq.en.html#WhyDoesTheGPLPermitUsersToPublishTheirModifiedVersions) , [InnerTune License](https://github.com/z-huang/InnerTune/blob/dev/LICENSE)

**Comment by MrEisbear** [comment]
![Screenshot_20231027-144713_Google Play Store](https://github.com/z-huang/InnerTune/assets/75928720/00498a7e-eff9-4470-a613-5253054f414f)
Well they gave credit, when I was checking it, they removed it. 🤔

**Comment by z-huang** [comment]
Thankfully, the app is gone in Google Play.
