### ISSUE TITLE
Unable to play song from playlist on ofline

### ISSUE THREAD

**Issue by ghost** [z-huang/music#1095]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

When I was online, I downloaded some songs and added them all to a play list. When I clicked the songs to play but nothing occurred, I also pressed the play button on the play list, but nothing happened either.

### Why do you want this feature?

There is no reason to download the song if it doesn't not allowed to play offline

**Comment by Zaxx69** [comment]
It happened to me yesterday, i couldn't play a single song even though my whole playlist was downloaded

**Comment by z-huang** [comment]
Check it again on latest version.
