### ISSUE TITLE
Squiggly line

### ISSUE THREAD

**Issue by aaronsbytes** [z-huang/music#1099]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

A squiggly line as seen in googles material you concepts. 
https://github.com/galaxygoldfish/waveslider

### Why do you want this feature?

This is a beautiful design element that is implemented nearly nowhere. It would greatly compliment the apps ui.

**Comment by z-huang** [comment]
https://m3.material.io/components/progress-indicators/specs

Material 3 doesn't mention the squiggly process bar.
