### ISSUE TITLE
Download 256kbps opus song.

### ISSUE THREAD

**Issue by max5354** [z-huang/music#110]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

So i just played downloaded song from this app. And this downloaded song is without album art. And also downloaded songs bitrat is just 128kbps. So please add option to download 256kbps opus songs. And with album art also.

### Why do you want this feature?

I think we will get upto 256kbps listing experience if you will add option to download 256kpbs opus songs.
![20220612_132919](https://user-images.githubusercontent.com/90886938/173223315-11bfbd5f-289a-43e7-8678-591ad71dcfa8.jpg)

**Comment by z-huang** [comment]
YouTube doesn't provide 256kbps audio. Maybe logged in with YouTube Premium can get the 256kbps audio, but I haven't tried yet.
Normal user shouldn't access directly to the internal folder to get the audio file. You can wait for an export feature to produce audio files with ID3 tags corresponding to their metadata.

**Comment by max5354** [comment]
> YouTube doesn't provide 256kbps audio. Maybe logged in with YouTube Premium can get the 256kbps audio, but I haven't tried yet. Normal user shouldn't access directly to the internal folder to get the audio file. You can wait for an export feature to produce audio files with ID3 tags corresponding to their metadata.

I know that youtube doesn't provide 256kbps opus. But YouTube music provide 256kbps opus right?

**Comment by z-huang** [comment]
> But YouTube music provide 256kbps opus right?

No, neither.
