### ISSUE TITLE
Add to Library button for albums

### ISSUE THREAD

**Issue by candroid-man** [z-huang/music#1100]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

In the actions menu for an album, there should be a button to add the entire album to the library.

### Why do you want this feature?

Currently you have to enter the actions menu for every song in the album, and then click on "add to library". This gets really annoying, and it wouldn't be too bad if we had #695

**Comment by thornySoap** [comment]
There is even a "Library" chip in the "Albums" Screen, but it's totally useless right now.

**Comment by z-huang** [comment]
You can press like to the album, and it will show up in the library.
