### ISSUE TITLE
Why the app not responding?

### ISSUE THREAD

**Issue by ElBulbol** [z-huang/music#1103]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

I can't like or add any song toy library or to my playlist.
I should delete the app and reinstall it to make that app back normally, but after a while the app back again to the Sam bug.
:(

https://github.com/z-huang/InnerTune/assets/142834487/4d86a4a4-b36d-4f37-9f54-d4941bd03876

### InnerTune version

"0.5.4"

### Android version

Android 11

### Additional information

https://github.com/z-huang/InnerTune/assets/142834487/37cad8da-cae8-4ee9-8f48-9720f35d1dca

**Comment by z-huang** [comment]
Reopen an issue with logs if it still happens. Remember to use the latest version (0.5.6).
