### ISSUE TITLE
Login Feature does not recognize the currently select channel (subaccount)

### ISSUE THREAD

**Issue by Ceiridge** [z-huang/music#1105]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

I logged into my Google account with multiple youtube channels. It automatically logs me into my desired channel, which is **not the main/default channel** of the Google account. Even after switching back and forth, InnerTube only shows me the name and content (playlists) of the main/default channel.

### Expected behavior

InnerTube should show the name of the currently selected channel and should show the playlists, etc., of the selected channel.

### Actual behavior

InnerTube only recognizes the main channel.

### Logs

No

### InnerTune version

0.5.3 (Published Build)

### Android version

Android 11

### Additional information

This might be related to https://github.com/z-huang/InnerTune/issues/976 ?

**Comment by ayunami2000** [comment]
Same issue here. I was able to get it to login at all (but on the wrong channel) by finding a video that linked to Google and then searching for "YouTube desktop site" and going there.

**Comment by z-huang** [comment]
Move #976
