### ISSUE TITLE
Refetch song metadata

### ISSUE THREAD

**Issue by amnesiac-kid** [z-huang/music#1107]
### Checklist

- [ ] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [ ] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Change region and language to Japanese.
2. Search for an American Song that is displayed with Katakana and add it to your library.
3. Change your region and language again to English.

### Expected behavior

Artist name / song title should show in English again

### Actual behavior

Katakana artist name / song title is still being displayed, even if you remove it from your Library, stop the app and clear cache and redo a new search for the song.

### Logs

...

### InnerTune version

0.5.3

### Android version

13

**Comment by z-huang** [comment]
Done.
