### ISSUE TITLE
Personalized suggestion after logged in

### ISSUE THREAD

**Issue by Urbexed** [z-huang/music#1108]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Offer music and artists upon connection to the Google account (therefore based on the data linked to the account)

It would be good to also link the history and favorite music 

### Why do you want this feature?

So suggestions would be more helpful

**Comment by z-huang** [comment]
Move to #1409
