### ISSUE TITLE
A-B Repeat Loop Function

### ISSUE THREAD

**Issue by codewhizz** [z-huang/music#1110]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Just as the title says. The A-B Repeat function enables playback to a specific section repeatedly by setting the start point (A) and end point (B) for the section. Like in VLC Media Player and other music players.

### Why do you want this feature?

Its in many music players. For music listeners like me this feature would be so useful, or else I have to download song on my device alternatively and play in offline music player to use this feature.

### Additional information

![loop-video-a-b](https://github.com/z-huang/InnerTune/assets/74320321/62bbdbaf-c168-4aa8-9497-9f8920096635)

**Comment by z-huang** [comment]
Not planned, but contribution is welcome.
