### ISSUE TITLE
Add long-press interactions with song titles

### ISSUE THREAD

**Issue by headquarter8302** [z-huang/music#1112]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Similar to #1074, however this one encompasses the entire app.

Currently, InnerTune exclusively uses thw triple-dot menu button for invoking the bottom menu sheet. I would like to see a long press interaction being added to the app

### Why do you want this feature?

This would surely streamline and enhance the experience of users, while also bringing parity with other music apps

**Comment by z-huang** [comment]
Long-press will be multi-select in this app.
