### ISSUE TITLE
Add Feature Request

### ISSUE THREAD

**Issue by sharoon7171** [z-huang/music#1115]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Hey team! 🚀 Loving Inner Tune—awesome work! 🎵 Two quick things I'd love to see:

Shuffle Button: It'd be super cool to have a shuffle button in the player. 🔄 Being able to switch between shuffle and playing the next song from the current one would be fantastic!

Offline Song Search: Currently, I can only search for songs when I'm online. 🌐 It would be a game-changer if I could search for downloaded songs and library content even when I'm offline. 📲 That way, I can find the perfect tune no matter where I am.

Thanks a ton! 🙌 Looking forward to the future updates. 👀✨

### Why do you want this feature?

Hey team! 🚀 Loving Inner Tune—awesome work! 🎵 Two quick things I'd love to see:

Shuffle Button: It'd be super cool to have a shuffle button in the player. 🔄 Being able to switch between shuffle and playing the next song from the current one would be fantastic!

Offline Song Search: Currently, I can only search for songs when I'm online. 🌐 It would be a game-changer if I could search for downloaded songs and library content even when I'm offline. 📲 That way, I can find the perfect tune no matter where I am.

Thanks a ton! 🙌 Looking forward to the future updates. 👀✨

### Additional information

Hey team! 🚀 Loving Inner Tune—awesome work! 🎵 Two quick things I'd love to see:

Shuffle Button: It'd be super cool to have a shuffle button in the player. 🔄 Being able to switch between shuffle and playing the next song from the current one would be fantastic!

Offline Song Search: Currently, I can only search for songs when I'm online. 🌐 It would be a game-changer if I could search for downloaded songs and library content even when I'm offline. 📲 That way, I can find the perfect tune no matter where I am.

Thanks a ton! 🙌 Looking forward to the future updates. 👀✨

**Comment by sharoon7171** [comment]
Absolutely enjoying Inner Tune! 🌟 Quick thought: any chance we could crank up the audio quality a bit? 🎶 It would be awesome to have even clearer sound for an even better listening experience.

**Comment by z-huang** [comment]
The shuffle button and offline song search are already implemented. The audio quality is already the highest we can offer.

**Comment by sharoon7171** [comment]
offline songs working
but if we do not turn on internet images are not shown for all i think images are only in cache
if you can do something for that so that album art also downloaded

and when in offline mod we click next songs too much then app crashes

everything is about offline mod even after downloading songs we still need internet connection so that everything will be fine
