### ISSUE TITLE
App Crash 

### ISSUE THREAD

**Issue by sharoon7171** [z-huang/music#1120]
### Checklist

- [ ] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

I have downlaoded songs offline and when i play without internet connection downloaded songs that plays but no image is shown and when we press next or previous on app or locak screen, or from notfications app crashes and songs stop playing.

### Expected behavior

App crash when we click next and previous songs without internet connection
No Image shown when we play without internet connection it should show if we already downloaded song 

### Actual behavior

App crash

### Logs

I dont know how to get

### InnerTune version

0.5.3

### Android version

EMUI 12.0.0

### Additional information

i liked this app too much please fix this issue
also audio quality if it can be increased please incresae audio qulaity

**Comment by WrobotGames** [comment]
I'm also experiencing this issue. It makes the app basically useless for offline playback. Random crashes with screen on and off, and album covers disappearing. Android 13 - OneUI5.1

**Comment by z-huang** [comment]
Please provide logs.

**Comment by sharoon7171** [comment]
how to provide?

**Comment by sharoon7171** [comment]
![photo_2024-01-30_16-57-24 (2)](https://github.com/z-huang/InnerTune/assets/141925453/14f8c52c-9fd5-480a-a176-79acf7c9d226)
![photo_2024-01-30_16-57-24](https://github.com/z-huang/InnerTune/assets/141925453/c696ea23-cddd-41a2-b515-2cde9e84e1f7)

i just downloaded songs and i turned off internet
now images are not showing and when i click next songs if just 1-2 only then it works fine but if i press next more than that then app crashes

but with internet connection everything works fine

**Comment by z-huang** [comment]
It should be fixed.
