### ISSUE TITLE
Get to home more quickly

### ISSUE THREAD

**Issue by attilafekete73** [z-huang/music#1128]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

A small button on the search screen or at the bottom of the app that takes the user back to the home page.
It can be done by simply not hiding the "navigation bar" (home, songs, artists, albums, play lists) 

### Why do you want this feature?

I noticed that when I search for something, than I enter the search bar again to search for something else, and I do this a couple of more times, (because I am making a Playlist and I'm searching for the songs separately). When I then want to play a Playlist I created, I have to push back, back, back, back,....

**Comment by sanga000** [comment]
Second this. It'd also make it easier to navigate when inside a playlist, such as accessing the "songs" tab directly while being in a playlist (currently I'd have to click Back->Songs)

**Comment by z-huang** [comment]
Done. 6660e8b774303d2464f06b7c09f0768ecb19c014
