### ISSUE TITLE
Better Playlists

### ISSUE THREAD

**Issue by ann-dvlpr** [z-huang/music#1130]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

1. An option to export playlists to YouTube music's servers.
2. Auto-export of library tracks. (maybe option to enable/disable)
3. Synchronization of liked tracks. (to liked playlist in yt music)

### Why do you want this feature?

To 1. As an mp3 player lover, I need the to export the .mp3 files from music and use them to listen music from my player.
To 2. Imagine a situation where you found some cool music and now listen it at PC, you shall type the music track in. What if there is multiple tracks? That's getting annoying more and more.
To 3. Like 2, the link between yt music account and innertune is (maybe) home page, and ability to listen tracks which liked from yt music account. Why not letting user just like the tracks in both sides?

### Additional information

Since I named this enhancement "Better playlists" that fits with 3 additions related to them. And also I think I didn't broke the "one feature only" rule since it literally the same action - exporting tracks to YouTube music, but in different forms.

**Comment by z-huang** [comment]
Move to #1409
