### ISSUE TITLE
Radio and Random Picks from artists page stops working if pressed during a brief moment without connectivity

### ISSUE THREAD

**Issue by Andrexskin** [z-huang/music#1131]
### Checklist

- [x] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Example:
- Go to artists page
- Simulate a connectionless moment, activate airplane mode for example
- Press the Random Picks button or Radio from the artists page (Doesn't work, obviously)
- Activate connection again and come back online
- Press the button for Random pikcs / Radio again, it doesn't work and the same happens if you change artists page or come back to the same one

### Expected behavior

The app should try "again" after I press the button again (when I finally get Online) and start the radio or the random picks mode.

### Actual behavior

The buttons stops working

### Screenshots/Screen recordings

https://github.com/z-huang/InnerTune/assets/149478844/c64487df-36f1-49df-bd04-f48d2125a104

### Logs

I'd love to get one but I'm not sure how to get it on the phone, hopefully the video and the steps to reproduce will be enough

### InnerTune version

0.5.3

### Android version

Android 13

### Additional information

Device: Honor 90

**Comment by z-huang** [comment]
These buttons need internet to load songs.

**Comment by Andrexskin** [comment]
What I meant is that once you get online again they are still not working while being connected.
I know they need internet to load songs ^^'
Thank you for replying though.

**Comment by z-huang** [comment]
I checked it and it can work.

**Comment by Andrexskin** [comment]
I guess it's a problem with my device then, I should check with the new version since the issue was present in the older one (which was the only one available during the time).
Thank you.
