### ISSUE TITLE
Can't see Albums and Singles anymore

### ISSUE THREAD

**Issue by HiddenLeveI** [z-huang/music#1133]
Since the Android 14 update, when I click on an artists profile, I see some of their albums and singles, when I click on the arrow to see the rest of them lined up, ir just loads forever.

**Comment by HiddenLeveI** [comment]
It not ir

**Comment by RT5666** [comment]
I get the same issue. Android 14 using Foss apk.

**Comment by arcanemind-develop** [comment]
Same here on Android 13.

**Comment by HiddenLeveI** [comment]
Why'd the issue get closed? It's still going on. I am using GrapheneOS but that shouldn't be conflicting with a FOSS app.

**Comment by z-huang** [comment]
I though it was fixed in #1182. If not, please provide logs.

**Comment by HiddenLeveI** [comment]
So that guy's fork fixes it? I guess I should try it.
