### ISSUE TITLE
Add Google Assistant support

### ISSUE THREAD

**Issue by yqyu-uyqu** [z-huang/music#1135]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add support to ask Google to play music on InnerTune.

### Why do you want this feature?

I would like this so that I can more conveniently use InnerTune with my headphones, when I cannot use my phone.

**Comment by z-huang** [comment]
Duplicate of #111
