### ISSUE TITLE
USB C to 3.5mm audio/USB C adapter glitch

### ISSUE THREAD

**Issue by BobRossBoss79** [z-huang/music#1136]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Plug in usb c to 3.5mm/usb c adapter
2. Open innertunes
3. Play song
4. The play button triggers on and off continuously 

### Expected behavior

Should play normally through audio out

### Actual behavior

The play button cycles on and off rapidly creating choppy playback most the time. I can slide up on the app to put it in the app slider and it will either play or stop but not cycle.
I can go to a browser and play YouTube just fine. 

### Logs

Not sure exactly how to get those on an android (very new to android)

### InnerTune version

0.5.3

### Android version

Android 14

### Additional information

I’ve tried multiple adapters of the same type but not different type so far. I do have others on order and will try those.

**Comment by z-huang** [comment]
I don't think this issue can be fixed on my side, sorry.
