### ISSUE TITLE
OPTION TO DELETE SAME SONGS 

### ISSUE THREAD

**Issue by deadbreat** [z-huang/music#1142]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

This feature is good for the people who have downloaded same songs twice 

### Why do you want this feature?

Because i have made mistake

**Comment by z-huang** [comment]
Now it's impossible to download a song twice.

**Comment by deadbreat** [comment]
Thanks brother
