### ISSUE TITLE
Youtube curated playlists not showing tracks

### ISSUE THREAD

**Issue by dPandl** [z-huang/music#1144]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Open the App
2. Open any Youtube curated Playlist from the Homepage Artistpage or link (for example: https://music.youtube.com/playlist?list=RDCLAK5uy_kwJTdGJj4KpaItCZogif_xkH69VyeERKw)

### Expected behavior

The Tracks should be Displayed.

### Actual behavior

No Tracks are shown. Just the number of songs.

### Screenshots/Screen recordings

![IMG_20231114_173741](https://github.com/z-huang/InnerTune/assets/35048273/9a91388f-bfee-4ee1-9ef5-5ebbd720d350)

### Logs

Idk how to create a log sorry.

### InnerTune version

0.5.3

### Android version

Android 13

**Comment by unseenlarks** [comment]
this issue seems to be sorted, tested the above playlist and several others on version 0.5.10
