### ISSUE TITLE
App crash when going into content and clicking my name

### ISSUE THREAD

**Issue by 585381** [z-huang/music#1146]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Settings > content > my name • then it crashed

### Expected behavior

Open into my account

### Actual behavior

App stopped 

### Logs

```
type: crash
osVersion: google/shiba/shiba:14/UD1A.231105.004/2023111500:user/release-keys
package: com.zionhuang.music:19
process: com.zionhuang.music
processUptime: 0 + 0 ms
installer: com.android.packageinstaller

signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000000000000028

backtrace:
      #00 pc 0000000001991564  /vendor/lib64/egl/libGLES_mali.so (start_routine+132) (BuildId: 648db26098e5fbbd)
      #01 pc 00000000000daeac  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204) (BuildId: ec367bcc42a0769197eb58413b7349bd)
      #02 pc 000000000006fbf0  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: ec367bcc42a0769197eb58413b7349bd)


```

### InnerTune version

.5.3

### Android version

14

**Comment by z-huang** [comment]
Clear app data and try again. If the bug still exists, please provide logs. (The one you provided doesn't contain useful information.)
