### ISSUE TITLE
Make it possible to import Newpipe playlists

### ISSUE THREAD

**Issue by Pokemetti** [z-huang/music#115]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Make it possible to import playlists from a Newpipe export file.

### Why do you want this feature?

I have a quite big playlist accumulated in Newpipe (~500 songs) and would really like to transfer it over without having to individually search all the songs.

**Comment by z-huang** [comment]
It's up to NewPipe to provide a friendly way to export the playlist. Currently it's not feasible.

**Comment by Pokemetti** [comment]
Ok, thanks for the info
