### ISSUE TITLE
Where are the downloaded songs stored?

### ISSUE THREAD

**Issue by XxRiKxX** [z-huang/music#1150]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Cant find downloaded contents anywhere

### Expected behavior

Files stored in a normal folder

### Actual behavior

Nowhere to be founs

### Logs

Nothing

### InnerTune version

0.5.3

### Android version

13

### Additional information

I read some of the issues and the innertune debug you mentioned is nowhere to be found in your release. You should add a option to store it in a specified directory

**Comment by DarkCrypt** [comment]
Duplicate.

Downloaded songs are inaccessible from outside the app.

There are many closed issues about this and cache.
See: #1049, #1046, #1040, #1035, #987, #895, #893, #817, #813, #810, and #774.

**Comment by XxRiKxX** [comment]
Then how do I transfer the downloaded media to pc? I need to change my rom

**Comment by DarkCrypt** [comment]
I don't think this is possible. There is a backup and restore option but I'm not sure if that transfers downloaded songs.

Users that want to download and transfer songs as files will need to use a music downloader instead. This app is only intended to stream with the added ability for offline play.

**Comment by XxRiKxX** [comment]
The backup and restore just copies liked songs, playlists but not downloaded songs. its not storing files in thin air so they must be somewhere. this app is great but I dont get the point of not stroing them where we can actually see it

**Comment by DarkCrypt** [comment]
Right, the downloaded files are still in a folder. They're just inaccessible which was a decision made by the dev.

Users can still see which songs they downloaded within the app by going to Songs -> Downloaded tab. I know that's not the same as access to a folder but it is what it is.

What reasons would make z-huang decide to make this change?
1. Already been stated.
2. Avoid legal issues.

**Comment by dev232644** [comment]
> The backup and restore just copies liked songs, playlists but not downloaded songs. its not storing files in thin air so they must be somewhere. this app is great but I dont get the point of not stroing them where we can actually see it

Just put all the downloaded songs in a playlist
