### ISSUE TITLE
Add the way to share a playlist and download the liked titles

### ISSUE THREAD

**Issue by Richard38907** [z-huang/music#1151]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

The option "share" is missing for a personal playlist

⬇️The option "offline titles" is missing in the liked titles playlist
![Screenshot_20231119-102925_InnerTune](https://github.com/z-huang/InnerTune/assets/148692265/899189b9-742c-4ff7-8c2d-abab69be4193)
![Screenshot_20231119-102906_InnerTune](https://github.com/z-huang/InnerTune/assets/148692265/8973b6d9-3596-4089-a348-926fd338b847)

### Why do you want this feature?

▶️It's easier to share my personal playlist (hyperlink) across multiple devices.

💙Liked titles section is the playlist I use the most.

### Additional information
Offline Music:
(For example: When I take the train, there are a lot of tunnels that break the data connexion)-> music stopped🛑.
I use v0.5.3

**Comment by z-huang** [comment]
Move to #1368
