### ISSUE TITLE
Attempting to restore history with innertune on another device crashes

### ISSUE THREAD

**Issue by marknash22** [z-huang/music#1152]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Open the app
Click settings
Clock backup and restore
Click restore

### Expected behavior

Should be able to go into phones folder explorer and choose the innertune database

### Actual behavior

Crashes

### Logs

Adb logcat

### InnerTune version

0.5.3

### Android version

Android 12

**Comment by z-huang** [comment]
Log needed.
