### ISSUE TITLE
⚠️ APP LAUNCHED ON PLAYSTORE BY SOMEONE 

### ISSUE THREAD

**Issue by Yashvanth343** [z-huang/music#1154]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

https://play.google.com/store/apps/details?id=com.voxify

### Expected behavior

https://play.google.com/store/apps/details?id=com.voxify

### Actual behavior

https://github.com/z-huang/InnerTune

### Logs

adb logcat

### InnerTune version

0.5.3

### Android version

Android 13

**Comment by Yashvanth343** [comment]
Without proper credits

**Comment by Yashvanth343** [comment]
https://github.com/z-huang/InnerTune/assets/72242474/784b02d5-9d3b-45d3-b893-8e7a46fa5852

When I click the search in Voxify app it opens up in InnerTune

**Comment by Ishatix** [comment]
Another one has now been launched which uses the same package name as InnerTune:
https://play.google.com/store/apps/details?id=com.zionhuang.music

This results in it getting offered as an update in AuroraStore if you have InnerTune installed (even with the "Filter F-Droid apps" option enabled). I have reported this to Aurora here:
https://gitlab.com/AuroraOSS/AuroraStore/-/issues/1023

I guess both these apps should be reported to the Play Store for removal??

**Comment by aRandomMenno** [comment]
> 
> https://github.com/z-huang/InnerTune/assets/72242474/784b02d5-9d3b-45d3-b893-8e7a46fa5852
> 
> When I click the search in Voxify app it opens up in InnerTune

Wth who even does that... It's like stealing a bike to give it back the next day.

I also flagged both apps as inappropriate on the playstore as suspicious content. Or something like that.

**Comment by z-huang** [comment]
Thankfully, the app is gone in Google Play.

**Comment by nvllz** [comment]
> Another one has now been launched which uses the same package name as InnerTune: https://play.google.com/store/apps/details?id=com.zionhuang.music
> 
> This results in it getting offered as an update in AuroraStore if you have InnerTune installed (even with the "Filter F-Droid apps" option enabled). I have reported this to Aurora here: https://gitlab.com/AuroraOSS/AuroraStore/-/issues/1023
> 
> I guess both these apps should be reported to the Play Store for removal??

@z-huang this one with your package name is still online.
