### ISSUE TITLE
Crash when click on download

### ISSUE THREAD

**Issue by LeoQwant** [z-huang/music#1155]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Click on whatever download or delete dowloaded song button in the app.

### Expected behavior

Songs or albums should be downloaded

### Actual behavior

App crashes and when I reopen it songs are still "downloading" but it never stops

### Logs

 I don't find a way to get logs in this app

### InnerTune version

0.5.3

### Android version

EMUI 12.0.0 Huawei Mate 20 Lite

### Additional information

With both Foss and full version rrgg

**Comment by z-huang** [comment]
Please provide logs.
