### ISSUE TITLE
Search bar overlapping while scrolling through the songs list.

### ISSUE THREAD

**Issue by snjaynegi** [z-huang/music#1156]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1.open application.
2. Go to songs tab.
3. In songs tab select DOWNLOADED. 
Note:- Download atleast 20 songs.
4. Under DOWNLOADED scroll through the downloaded songs list.

### Expected behavior

Search bar should not be moving it should be static.
Library, Liked and Downloaded should be static and section below this containing list of songs should be scrollable/dynamic.

<img width=200 src="https://github.com/z-huang/InnerTune/assets/141922266/a1e3da35-346c-4db3-b1ef-aa292c69f477" />

### Actual behavior

The search bar is overlapping with filter i.e Library, Liked and Downloaded.

<img width=200 src="https://github.com/z-huang/InnerTune/assets/141922266/0dbe1451-ceb1-4ac9-b90d-4db7821ce432" />

### Screenshots/Screen recordings

<img width=200 src="https://github.com/z-huang/InnerTune/assets/141922266/4ca7a2f6-076a-4fbb-b362-6080389cf978" />
<img width=200 src="https://github.com/z-huang/InnerTune/assets/141922266/bc2e6a8b-96bc-44f5-afad-aa1aade758a1" />
<img width=200 src="https://github.com/z-huang/InnerTune/assets/141922266/3fe1608c-d233-4ab0-acab-561bd3604480" />

### Logs

<img width=200 src="https://github.com/z-huang/InnerTune/assets/141922266/cdcb4281-fafe-4b0c-9f0b-dbf6a61f4114" />

### InnerTune version

0.5.3

### Android version

Android 14

### Additional information

I have checked with the artists page also so this overlapping issue is present on both page i.e artists and songs.

**Comment by z-huang** [comment]
Should be fixed.
