### ISSUE TITLE
Add backup documentation

### ISSUE THREAD

**Issue by sioodmy** [z-huang/music#1157]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add documentation describing how backup files are processed.

### Why do you want this feature?

I want to make CLI/TUI client for youtube music with option to synchronize between my phone and desktop, without the need of using google account

**Comment by Malopieds** [comment]
The .backup is actually a zip file, unzip it you will find a song.db which is the database. You can now use it to synchronize between your phone and desktop using sqlite3.
Hope this help.

**Comment by sioodmy** [comment]
thanks
