### ISSUE TITLE
Use musixmatch instead for lyrics

### ISSUE THREAD

**Issue by abcdab3** [z-huang/music#1158]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Musixmatch as the lyrics provider

### Why do you want this feature?

Instead of the current lyrics provider which is very poor and not supported for multiple genres and language of songs, using musixmatch would be better

**Comment by akano12** [comment]
Bumping this

**Comment by z-huang** [comment]
Musixmatch API isn't available.

**Comment by abcdab3** [comment]
> Musixmatch API isn't available.

It is available its just that it requires a premium
