### ISSUE TITLE
Liked songs playlist

### ISSUE THREAD

**Issue by qraftyfied** [z-huang/music#1159]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add all songs that you liked to a Playlist called "Liked Songs" automatically, let user select a specific playlist in the settings (so the liked songs playlist from yt can be used for example)

### Why do you want this feature?

Almost every music player has that feature too and it is good to find your songs again

**Comment by z-huang** [comment]
You can filter liked songs in the songs tab. The liked and downloaded playlist existed before, but I decided to move them into the songs tab.
