### ISSUE TITLE
Select multiple songs

### ISSUE THREAD

**Issue by Pokemetti** [z-huang/music#116]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Currently you can only select one song/entry and, for example, add it to your playlist. It would be nice to be able to select multiple songs and add them all to your playlist.

### Why do you want this feature?

I want to be able to add multiple songs I've already heard and know, this would just be convenient for that.

**Comment by AqilCont** [comment]
This would be really helpful to me! I want to download multiple songs in playlists sometimes and manually going through each one is not the most fun.
