### ISSUE TITLE
"Unknown error" while playing specific songs

### ISSUE THREAD

**Issue by Shardonnay** [z-huang/music#1160]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Search for the song "Killing In the Name"
2. Click on the song
3. Seek to a duration in the middle of the song
4. Song stops playing and it says "Unknown error"

### Expected behavior

Song plays without stopping.

### Actual behavior

Either you listen to the song and it skips the middle part or you try to seek to a duration in the middle of the song it the error message is shown.

### Screenshots/Screen recordings

![Screenshot_20231130-144809_InnerTune Debug](https://github.com/z-huang/InnerTune/assets/96491861/6376546f-c826-4e22-a2c3-eae8eb6c6c78)

### Logs

11-30 14:55:11.440 31979 31979 V MusicFXControlPanelReceiver: Package name: com.zionhuang.music.debug
11-30 14:55:11.440 31979 31979 V MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@1fb3a26, com.zionhuang.music.debug, 4081)
11-30 14:55:11.440 31979 31979 V MusicFXControlPanelEffect: closeSession(android.app.ReceiverRestrictedContext@1fb3a26, com.zionhuang.music.debug, 3969)
11-30 14:55:11.443 31997 31997 I SessionReceiver: Action: android.media.action.OPEN_AUDIO_EFFECT_CONTROL_SESSION; session: 4081; package com.zionhuang.music.debug
11-30 14:55:11.447 31979 31979 V MusicFXControlPanelReceiver: Package name: com.zionhuang.music.debug
11-30 14:55:11.447 31979 31979 V MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@1fb3a26, com.zionhuang.music.debug, 4081)
11-30 14:55:11.450 32024 32024 V MusicFXControlPanelReceiver: Package name: com.zionhuang.music.debug
11-30 14:55:11.450 32024 32024 V MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@c6c7981, com.zionhuang.music.debug, 4081)
11-30 14:55:11.450 32024 32024 V MusicFXControlPanelEffect: closeSession(android.app.ReceiverRestrictedContext@c6c7981, com.zionhuang.music.debug, 3969)
11-30 14:55:11.453 32046 32046 V MusicFXControlPanelReceiver: Package name: com.zionhuang.music.debug
11-30 14:55:11.453 32046 32046 V MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@c6c7981, com.zionhuang.music.debug, 4081)
11-30 14:55:11.453 32046 32046 V MusicFXControlPanelEffect: closeSession(android.app.ReceiverRestrictedContext@c6c7981, com.zionhuang.music.debug, 3969)
11-30 14:55:11.899 31979 31979 V MusicFXControlPanelReceiver: Package name: com.zionhuang.music.debug
11-30 14:55:11.899 31979 31979 V MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@1fb3a26, com.zionhuang.music.debug, 4081)
11-30 14:55:11.902 31997 31997 I SessionReceiver: Action: android.media.action.OPEN_AUDIO_EFFECT_CONTROL_SESSION; session: 4081; package com.zionhuang.music.debug
11-30 14:55:11.905 31979 31979 V MusicFXControlPanelReceiver: Package name: com.zionhuang.music.debug
11-30 14:55:11.905 31979 31979 V MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@1fb3a26, com.zionhuang.music.debug, 4081)
11-30 14:55:11.907 32024 32024 V MusicFXControlPanelReceiver: Package name: com.zionhuang.music.debug
11-30 14:55:11.907 32024 32024 V MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@c6c7981, com.zionhuang.music.debug, 4081)
11-30 14:55:11.911 32046 32046 V MusicFXControlPanelReceiver: Package name: com.zionhuang.music.debug
11-30 14:55:11.911 32046 32046 V MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@c6c7981, com.zionhuang.music.debug, 4081)
11-30 14:55:13.441 31979 31979 V MusicFXControlPanelReceiver: Package name: com.zionhuang.music.debug
11-30 14:55:13.441 31979 31979 V MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@1fb3a26, com.zionhuang.music.debug, 4081)
11-30 14:55:13.443 31997 31997 I SessionReceiver: Action: android.media.action.OPEN_AUDIO_EFFECT_CONTROL_SESSION; session: 4081; package com.zionhuang.music.debug
11-30 14:55:13.448 31979 31979 V MusicFXControlPanelReceiver: Package name: com.zionhuang.music.debug
11-30 14:55:13.448 31979 31979 V MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@1fb3a26, com.zionhuang.music.debug, 4081)
11-30 14:55:13.450 32024 32024 V MusicFXControlPanelReceiver: Package name: com.zionhuang.music.debug
11-30 14:55:13.451 32024 32024 V MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@c6c7981, com.zionhuang.music.debug, 4081)
11-30 14:55:13.458 32046 32046 V MusicFXControlPanelReceiver: Package name: com.zionhuang.music.debug
11-30 14:55:13.459 32046 32046 V MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@c6c7981, com.zionhuang.music.debug, 4081)
11-30 14:55:13.946 31979 31979 V MusicFXControlPanelReceiver: Package name: com.zionhuang.music.debug
11-30 14:55:13.946 31979 31979 V MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@1fb3a26, com.zionhuang.music.debug, 4081)
11-30 14:55:13.948 31997 31997 I SessionReceiver: Action: android.media.action.OPEN_AUDIO_EFFECT_CONTROL_SESSION; session: 4081; package com.zionhuang.music.debug
11-30 14:55:13.953 31979 31979 V MusicFXControlPanelReceiver: Package name: com.zionhuang.music.debug
11-30 14:55:13.953 31979 31979 V MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@1fb3a26, com.zionhuang.music.debug, 4081)
11-30 14:55:13.955 32024 32024 V MusicFXControlPanelReceiver: Package name: com.zionhuang.music.debug
11-30 14:55:13.955 32024 32024 V MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@c6c7981, com.zionhuang.music.debug, 4081)
11-30 14:55:13.957 32046 32046 V MusicFXControlPanelReceiver: Package name: com.zionhuang.music.debug
11-30 14:55:13.957 32046 32046 V MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@c6c7981, com.zionhuang.music.debug, 4081)
11-30 14:55:18.814  6407 11520 I MediaFocusControl: requestAudioFocus() from uid/pid 10270/32318 AA=USAGE_MEDIA/CONTENT_TYPE_MUSIC clientId=android.media.AudioManager@415b25aandroidx.media3.exoplayer.AudioFocusManager$AudioFocusListener@5308c8b callingPack=com.zionhuang.music.debug req=1 flags=0x0 sdk=33
11-30 14:55:18.826  6407  7537 I MediaSessionStack: onPlaybackStateChanged - Pushing session to top | record: com.zionhuang.music.debug/androidx.media3.session.id. (userId=0)
11-30 14:55:18.832 31979 31979 V MusicFXControlPanelReceiver: Package name: com.zionhuang.music.debug
11-30 14:55:18.832 31979 31979 V MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@1fb3a26, com.zionhuang.music.debug, 4081)
11-30 14:55:18.836 31997 31997 I SessionReceiver: Action: android.media.action.OPEN_AUDIO_EFFECT_CONTROL_SESSION; session: 4081; package com.zionhuang.music.debug
11-30 14:55:18.840 31979 31979 V MusicFXControlPanelReceiver: Package name: com.zionhuang.music.debug
11-30 14:55:18.840 31979 31979 V MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@1fb3a26, com.zionhuang.music.debug, 4081)
11-30 14:55:18.842 32024 32024 V MusicFXControlPanelReceiver: Package name: com.zionhuang.music.debug
11-30 14:55:18.842 32024 32024 V MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@c6c7981, com.zionhuang.music.debug, 4081)
11-30 14:55:18.843 32046 32046 V MusicFXControlPanelReceiver: Package name: com.zionhuang.music.debug
11-30 14:55:18.843 32046 32046 V MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@c6c7981, com.zionhuang.music.debug, 4081)
11-30 14:55:18.967 31979 31979 V MusicFXControlPanelReceiver: Package name: com.zionhuang.music.debug
11-30 14:55:18.967 31979 31979 V MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@1fb3a26, com.zionhuang.music.debug, 4081)
11-30 14:55:18.969 31997 31997 I SessionReceiver: Action: android.media.action.OPEN_AUDIO_EFFECT_CONTROL_SESSION; session: 4081; package com.zionhuang.music.debug
11-30 14:55:18.973 31979 31979 V MusicFXControlPanelReceiver: Package name: com.zionhuang.music.debug
11-30 14:55:18.973 31979 31979 V MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@1fb3a26, com.zionhuang.music.debug, 4081)
11-30 14:55:18.975 32024 32024 V MusicFXControlPanelReceiver: Package name: com.zionhuang.music.debug
11-30 14:55:18.975 32024 32024 V MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@c6c7981, com.zionhuang.music.debug, 4081)
11-30 14:55:18.978 32046 32046 V MusicFXControlPanelReceiver: Package name: com.zionhuang.music.debug
11-30 14:55:18.978 32046 32046 V MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@c6c7981, com.zionhuang.music.debug, 4081)
11-30 14:55:19.129  6407  6407 I NotificationService: Cannot find enqueued record for key: 0|com.zionhuang.music.debug|888|null|10270

### InnerTune version

0.5.3 FULL DEBUG from build debug apk #1186

### Android version

Android 13

### Additional information

It also happens with the InnerTune 0.5.3 FOSS version.

**Comment by z-huang** [comment]
Because this song has age restriction.
