### ISSUE TITLE
Integration with Invidious instances as an additional method

### ISSUE THREAD

**Issue by wnm210** [z-huang/music#1163]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add an option to use your desired Invidious instance instead of privacy-invasive YouTube server. Allow users to select instances from a list or add their own.

### Why do you want this feature?

I think that this feature will be widely used among users that don't want to be tracked by Google as Invidious routes their traffic through the  instance server. YouTube sees the requests of instance users as they were made by a single person. 

### Additional information

N/A

**Comment by wnm210** [comment]
Duplicate of #444

**Comment by z-huang** [comment]
Invidious lacks many essential features.

**Comment by wnm210** [comment]
What important features? Like the spyware?

**Comment by z-huang** [comment]
- Music search suggestions
- Queue info
- Radio
- ...and more
