### ISSUE TITLE
option to switch between phone speaker and wired headphones or wireless devices for audio output 

### ISSUE THREAD

**Issue by Partha-deuri** [z-huang/music#1165]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

There should be a switch icon on the media player which let us switch between phone speaker and other connected device for audio output .

### Why do you want this feature?

When I want to let someone else hear a song just for a little while
It's time consuming to disconnect the external device like wired earphone or any other wireless devices just to let others hear the song and then connect again after it is done. I want to switch between phone speaker and other connected device for audio output without actually disconnecting the other device

**Comment by z-huang** [comment]
As fas as I know, you can change the audio output device in the notification center.
<img src="https://github.com/z-huang/InnerTune/assets/39427017/49640757-fe22-4604-8f9b-de869172662e" width=200 />
(Picture from Internet)
