### ISSUE TITLE
Improvement: bring back ability to access downloaded music from the outside

### ISSUE THREAD

**Issue by anedroid** [z-huang/music#1167]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I noticed that v. 0.5.0 changelog states "Improved download experience" and this is where accessing downloaded content via SAF dissappeared. There are many issues regarding this (e.g. https://github.com/z-huang/InnerTune/issues/1150, https://github.com/z-huang/InnerTune/issues/1049, https://github.com/z-huang/InnerTune/issues/1046, https://github.com/z-huang/InnerTune/issues/1035) so it seems people are demanding this feature. For them the download experience got worsen, because they can't copy the files easily to PC.

### Why do you want this feature?

Playing in-app is nice, as long as users can export data and do whatever-they-want with it. And to be honest, this app is really nice and useful and I really like it, it's just such small thing reminds me of actions taken against users by Google and few other companies (incl. Spotify, Netflix, etc.) to limit their freedom by turning their ecosystems into walled gardens.

**What are you trying to achieve**? ToS compliant? Developing alternative clients already goes against ToS and that's perfectly fine. NewPipe, Invidious, Piped, loved by FOSS folks follow ToS neither, because Google's ToS is unethical and we don't need to go into contract with them. Also I think this app is not going to be taken off from Playstore, so... what the matter?

### Additional information

I see InnerTune internally stores files with suffix `.exo` (no idea what is it). Why don't convert it to opus or m4a on-demand or after downloading? You could at least store it in shared storage with more user-friendly names and formats and the metadata in it or in some json/xml/db/csv, so it might be backed up and restored without root access.

Sorry to ignore duplicates, but I think commenting on closed issues won't be noticed and this is the important case. In my opinion it's better to have proper download that to have option to log in – if it's Google banning OAUTH for apps with open download, there are apps with separate features for FOSS and proprietary variants.

**Comment by 7heMech** [comment]
I agree sucks to not be able to set downloaded music as my alarm.

**Comment by corval** [comment]
Se puede llegar a las descargas de archivos mp3, pero el detalles es que las guarda con un nombre alfanumérico lo que es dificil identificar el nombre de la canción. Pero es reproducible en cualesquier reproductor ajeno a InnerTune. Saludos

**Comment by 7heMech** [comment]
@corval in which directory does it save them?

**Comment by anedroid** [comment]
/data/user/0/com.zionhuang.music/files/download/0

**Comment by corval** [comment]
On my device:
[/storage/emulated/0/Android/data/com.zionhuang.music/files/media/]()1b6d7fda9a7d19752c188b757e033c4f

All files not identified, no extention.
But if you open by VLC, it will play like a normal sound file.![Screenshot_20240105-014746.png](https://github.com/z-huang/InnerTune/assets/9479398/3c773903-2ac4-4c20-95a5-8c17a2a4709a)

**Comment by anedroid** [comment]
Termux says it's a webm file.

**Comment by anedroid** [comment]
What Android version?

**Comment by PrimeTwister** [comment]
> On my device:
> [/storage/emulated/0/Android/data/com.zionhuang.music/files/media/]()1b6d7fda9a7d19752c188b757e033c4f
> 
> All files not identified, no extention.
> But if you open by VLC, it will play like a normal sound file.![Screenshot_20240105-014746.png](https://github.com/z-huang/InnerTune/assets/9479398/3c773903-2ac4-4c20-95a5-8c17a2a4709a)
> 
> 

Android verison and app? Are you rooted?

**Comment by 7heMech** [comment]
> On my device:
> [/storage/emulated/0/Android/data/com.zionhuang.music/files/media/]()1b6d7fda9a7d19752c188b757e033c4f
> 
> All files not identified, no extention.
> But if you open by VLC, it will play like a normal sound file.![Screenshot_20240105-014746.png](https://github.com/z-huang/InnerTune/assets/9479398/3c773903-2ac4-4c20-95a5-8c17a2a4709a)
> 
> 

I don't have files in Android data, only cache :(

**Comment by w3teal** [comment]
> > On my device:
> > [/storage/emulated/0/Android/data/com.zionhuang.music/files/media/]()1b6d7fda9a7d19752c188b757e033c4f
> > 
> > All files not identified, no extention.
> > But if you open by VLC, it will play like a normal sound file.![Screenshot_20240105-014746.png](https://github.com/z-huang/InnerTune/assets/9479398/3c773903-2ac4-4c20-95a5-8c17a2a4709a)
> > 
> > 
> 
> I don't have files in Android data, only cache :(

Same here..
![Screenshot_20240713_202538_Files.jpg](https://github.com/user-attachments/assets/1ad0d26c-6421-40ee-b8fa-ea8c4e6244dc)

**Comment by 7heMech** [comment]
I can't access files in data because Android updates have made it harder if not impossible to reach.

**Comment by z-huang** [comment]
If you want to access downloaded music, you can use YouTube downloader such as NewPipe. Most audio InnerTune downloads is in webm format, which is not easy to open and may need a converter to convert to mp3.

The reason why SAF disappeared is that exoplayer saves audio in chunks. One audio is split to many files. So, I can't just expose the directory for access. Though there may be ways to tackle it, it's not my first priority.

Anyway, contribution is welcome.
