### ISSUE TITLE
All sections except Videos (Songs, Albums, Singles) in homepage of an artist don't show any content.

### ISSUE THREAD

**Issue by TryingToUseLinux** [z-huang/music#1177]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Search for any artist who has enough albums/singles such that all are not visible in the homepage of the artist.
2. Click on the arrow to expand any section (Songs, Albums, Singles, Videos).

### Expected behavior

Each pane should show its respective content.

### Actual behavior

1. Songs pane shows a black screen.
2. Albums and Singles pane load indefinitely.
3. Videos pane works correctly.

### Screenshots/Screen recordings

https://github.com/z-huang/InnerTune/assets/150410641/f31a76d5-6d54-402f-a535-d99cd925a4ab

### InnerTune version

0.5.3

### Android version

Android 13

**Comment by Sagitee** [comment]
Today I encounter the same important issue, which didn't exist before. Maybe YT made some changes in their databases but I noticed that other YT music streamer apps like vimusic seems not to have been similarly affected.

**Comment by MLZ94** [comment]
It happens to me to and actually, it used to happen in the past and when you clean installed the app it used to get fixed, but if you restored a config, it was broken again. Now it just doesn't work no matter what. It's worth noting that the song section is meant to be a list usually, and when this bug happens, it's changed into carousel which make me think there's a problem with the content loaded from yt

**Comment by TryingToUseLinux** [comment]
Songs being displayed with a larger thumbnail is a relatively recent occurrence. Besides this making the song list broken, "view album" option is also no longer present (both when you long press on the song in the homepage, and when you play the song). This is a different bug, though they are likely related.

**Comment by MLZ94** [comment]
https://github.com/z-huang/InnerTune/issues/1048
It seems like this has already happen and it's due to a change in yt api response and zion fixed it once . No idea how to fix it this time personally

**Comment by Sagitee** [comment]
> issue 1048
It seems like this has already happen and it's due to a change in yt api response and zion fixed it once . No idea how to fix it this time personally

If I understand correctly, the mentioned fix came some days after the current version release, so it will be included in the next one.

**Comment by MLZ94** [comment]
> > issue 1048
> > It seems like this has already happen and it's due to a change in yt api response and zion fixed it once . No idea how to fix it this time personally
> 
> If I understand correctly, the mentioned fix came some days after the current version release, so it will be included in the next one.

Yes that's right, i just realized. Anyone has the lastest debug build ? It has expired on github action....

**Comment by Malopieds** [comment]
Should be fixed now. Waiting for approval/edit from maintainers. You can either wait for it to be pushed to master, build it yourself, or I can provide a build.

**Comment by MLZ94** [comment]
Thanks you for investigating the issue, unfortunately i don't think it's gonna be merged any soon as the owner doesn't seem to be active, so it would be great if you could provide a build🙏
Also just in case it has a chance to get merged you should squash all the 14 commits of the pr into 1 as only the lastest is actually the fix

**Comment by Malopieds** [comment]
Yes, I saw that later on. Should be squashed now. You can find [here](https://github.com/Malopieds/InnerTune/releases/download/debug/app-foss-release.apk) the link for the apk (it's the FOSS version). 
## CAUTION:
I did not change the version of the app or anything else, you may not be able to update from there. If you can't you'll have to delete the old app and install the new one. Remember to always backup your data, I would not be responsible for any loss of data.

**Comment by MLZ94** [comment]
Great job well done it's all good 👌
