### ISSUE TITLE
Ability to restore backup from ViMusic

### ISSUE THREAD

**Issue by at-oliverapps** [z-huang/music#1178]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I use vimusic as my goto music app it doesn't seem to get updated anymore as it is and I have alot of content inside vimusic

### Why do you want this feature?

I find innertune to be a better choice as it is now

**Comment by z-huang** [comment]
The database is not compatible.
