### ISSUE TITLE
Canciones de Artista

### ISSUE THREAD

**Issue by Arturo254** [z-huang/music#1180]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Actualize la alplicacion

### Expected behavior

No muestra las canciones de los artistas al meterme a su perfil y a la seccion de canciones

### Actual behavior

https://github.com/z-huang/InnerTune/assets/87346871/8d34a212-d8c7-4bcd-ae9e-49c26550f1c4

### Logs

![image](https://github.com/z-huang/InnerTune/assets/87346871/349f5793-d18c-4f31-82fe-00ea3488ba1d)

### InnerTune version

0.5.3

### Android version

Android 12,13,14

**Comment by TryingToUseLinux** [comment]
#1177 also includes this

**Comment by MLZ94** [comment]
If someone can grab a real log that works be helpful... I currently can't

**Comment by z-huang** [comment]
Fixed.
