### ISSUE TITLE
Request of INNERTUNE for PC 💻 user's 

### ISSUE THREAD

**Issue by paryagbansal131** [z-huang/music#1181]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### The Need
As you all know that, this app i.e.  _INNERTUNE_ helps us to listen music from youtube directly without any ads. And that is the main advantage of using this app, but this is only available for android device's. This app provides a very nice and easy to use user interface that makes _innertune _ very reliable and very adaptive for the users. And i but also another windows users also need to listen music without any advertisement  on PC , So i on the behalf of all them users now requesting this app i.e. _**INNERTUNE**_ for windows users .

### Why do we need it 
As a normal windows user i like to listen songs while working and doing something productive work, to do so i use youtube for listening music and as we all knows about the advertisements coming in-between ,that ads spoil the feel and so maintain that feel i started to use innertune on my mobile and need this on my windows machine. As this a great and an efficient to fulfill my and other windows user's need .
So kindly help and make a windows version available of this.................
please help and also give response regarding this matter.

**Comment by TryingToUseLinux** [comment]
Just use an ad blocker on your browser? Ublock origin is pretty good.
Alternatively see [beatbump.io](https://beatbump.io). ([Repo](https://github.com/snuffyDev/Beatbump))

**Comment by akano12** [comment]
https://github.com/th-ch/youtube-music

**Comment by kaneryu** [comment]
I'm working an Innertune for PC right now actually, and have been for some time. ETA is still a few months out from now though.

**Comment by TempWorld** [comment]
I support the idea, I would like to have InnerTune available on my PC too, to have the apps connected, since on PC I can use AdBlock on YouTube Music, but I would like to have the same app so that it is connected to the same account and the recommendations be the same

**Comment by DarkCrypt** [comment]
Just use the app on PC with an Android emulator like WSA.

**Edit:** Sadly, WSA will no longer be supported after March 5, 2025. Learn more at [Microsoft/WSA](https://github.com/microsoft/WSA/discussions/536) (GitHub) and [Microsoft Learn](https://learn.microsoft.com/en-us/windows/android/wsa/).

**Comment by TryingToUseLinux** [comment]
> Just use the app on PC with an Android emulator like WSA.

Even if you do this, your recommendations from the android client won't sync with the client on your pc. I don't see any benefit of doing this over using beatbump, or just youtube music with an adblocker.

**Comment by DarkCrypt** [comment]
> Even if you do this, your recommendations from the android client won't sync with the client on your pc.

Recommendations don't sync with an account? So why would a PC version make a difference?

**Comment by filinux13** [comment]
> Even if you do this, your recommendations from the android client won't sync with the client on your pc. 

You can create a backup and restore in innertune. I use bluestacks emulator but it should work on other emulators.

>I don't see any benefit of doing this over using beatbump, or just youtube music with an adblocker.

I have all my music in innertune playlists and i am too lazy to bring the to YouTube music (it sucks) so its easier to just use an emulator.
