### ISSUE TITLE
Displaying the album name instead of the artist's name

### ISSUE THREAD

**Issue by ghost** [z-huang/music#1184]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1) Search any title in the search bar
2) Click on a song of the "Titles" section

### Expected behavior

It should normally display the Artist name as the "Artist of the song"

### Actual behavior

It actually display the name of the Album as the "Artist of the song"

### Screenshots/Screen recordings

https://github.com/z-huang/InnerTune/assets/50982832/74524a67-e2e1-4238-bfc4-8fd932e44fc7

### Logs

Doesn't need it.

### InnerTune version

0.5.3

### Android version

Android 14

**Comment by Malopieds** [comment]
Hi, it is fixed in the pr linked before. [Here](https://github.com/Malopieds/InnerTune/releases/download/debug-2/app-foss-debug.apk) is the link for downloading the latest debug build.
I will (may be soon) drop some update on an official build on my branch with some changes if you're interested.

**Comment by ghost** [comment]
Hey @Malopieds
Your work is very interesting! :D

**Comment by ghost** [comment]
> Hey @Malopieds Your work is very interesting! :D

Merci chef pour ton boulot ;)

**Comment by Malopieds** [comment]
Should be (totally, for now) fixed in my latest PR.
You can find a version [here](https://github.com/Malopieds/InnerTune/releases/download/debug-2/app-foss-release.apk)

**Comment by Malopieds** [comment]
> Hey @Malopieds Your work is very interesting! :D

Merci haha

**Comment by ghost** [comment]
> > Hey @Malopieds Your work is very interesting! :D
> 
> Merci haha

C'est normal !
