### ISSUE TITLE
Image cache limit doesn't update

### ISSUE THREAD

**Issue by 7heMech** [z-huang/music#1186]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Go to settings/storage
2. Change max cache size for images

### Expected behavior

Visual graph and limit should be updated

### Actual behavior

Visual graph (and limit?) don't get updated.

### Screenshots/Screen recordings

![ResizedImage_2024-01-02_05-27-40_2339](https://github.com/z-huang/InnerTune/assets/83923848/c1db785c-6fbb-48fd-a1e9-b9a4eb315296)

### Logs

I don't have adb 🙏

### InnerTune version

0.5.3

### Android version

Android 14

**Comment by z-huang** [comment]
It will take effect after you restart the app.
