### ISSUE TITLE
Delete option 

### ISSUE THREAD

**Issue by feelsavvy** [z-huang/music#1187]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add song delete option in playlist 

### Why do you want this feature?

.

**Comment by nvllz** [comment]
If you want to remove a song from the playlist, you can swipe it to the side when in unlocked mode (padlock icon).
