### ISSUE TITLE
Search music by url

### ISSUE THREAD

**Issue by hasanelfalakiy** [z-huang/music#1190]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Please, add a feature to search for music by URL, for example the URL from YouTube

### Why do you want this feature?

This feature will make it very easy, because searching by name will not find the music I want, this feature is like the NewPipe application, for example, when watching YouTube, click share then copy the url then paste the url in the NewPipe application search, the results will be found immediately

**Comment by Malopieds** [comment]
Hi, if you click share from an app, say youtube music in your browser, you should have the InnerTune option and it will redirect to the song/album/... that you shared. Starting from android 13, I think, you have the possibilities to "Open by default" an app when clicking a link. If you have youtube/youtube music application installed it can be a bit more tricky.

**Comment by hasanelfalakiy** [comment]
> Hi, if you click share from an app, say youtube music in your browser, you should have the InnerTune option and it will redirect to the song/album/... that you shared. Starting from android 13, I think, you have the possibilities to "Open by default" an app when clicking a link. If you have youtube/youtube music application installed it can be a bit more tricky.

I've tried it, there is an innertune option there but after I click on the music it doesn't open, it only goes to the front page of innertune

**Comment by DeadSecTr** [comment]
Yup...i can confirm that too

**Comment by z-huang** [comment]
You can share the music and open with InnerTune. I tested it and it was working.

**Comment by hasanelfalakiy** [comment]
> You can share the music and open with InnerTune. I tested it and it was working.

I still can't do it that way
