### ISSUE TITLE
songs not showning in artist tab

### ISSUE THREAD

**Issue by itsmmt305** [z-huang/music#1191]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

move to an artist's page in innertune

### Expected behavior

top 5 songs shall be visible and clicking on songs header should navigate to list of all songs

### Actual behavior

yt music songs dont show; only yt music videos

### Screenshots/Screen recordings

https://github.com/z-huang/InnerTune/assets/94820934/5cd71c20-da5e-4de9-bde7-7a3fd1913ac6

### Logs

sorry

### InnerTune version

0.5.3

### Android version

Android 13 | MIUI 14

**Comment by nvllz** [comment]
It's already fixed with https://github.com/z-huang/InnerTune/pull/1182, but we need @z-huang to merge it.

**Comment by itsmmt305** [comment]
im sorry i only checked open issues. i guess we can close this then?
