### ISSUE TITLE
Custom value of audio pitch (like NewPipe or YMusic)

### ISSUE THREAD

**Issue by ghost** [z-huang/music#1194]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Hey!
So here's a feature suggestion which afaik pretty easy to implement too. Which is adjustment of audio pitch on decimal levels. Here's what I mean:

![Screenshot_20240105-133034_InnerTune](https://github.com/z-huang/InnerTune/assets/90166733/3fe982a4-6328-4598-8792-fcc68c28e75c)
![Screenshot_20240105-133037_InnerTune](https://github.com/z-huang/InnerTune/assets/90166733/33be558b-b9b7-45cd-8815-9c3dc2c78e03)

Currently when you press the +/- button, the pitch adds or substracts by one. However it would be far more useful to increment/decrement the value by a small unit.

Here's how YMusic or NewPipe/LibreTube do it:

![Screenshot_20240105-133210_YMusic](https://github.com/z-huang/InnerTune/assets/90166733/35ca2191-8fc8-426f-9014-a872a61994d1)
_(pitch increases to 1.02 instead of 1.1)_

Thanks.

### Why do you want this feature?

It will enhance the usability of this app.

**Comment by z-huang** [comment]
I think setting the step of the pitch to one semitone is better for people who like to sing.

**Comment by bouncytorch** [comment]
> I think setting the step of the pitch to one semitone is better for people who like to sing.

i think a compromise to this would be to enable direct editing of the pitch value but leave the +/- semitone step. Because there are loads of people whod like to fine tune their music, but can't due to... this.

The step on the pitch adjust buttons can be whatever you want, just make the actual value field editable in the case someone does want to fine tune
