### ISSUE TITLE
Deletion of a song from a playlist

### ISSUE THREAD

**Issue by sudorogar** [z-huang/music#1195]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

There is currently no way to remove once added song in a playlist.

### Why do you want this feature?

Some song feels like shit on listening second time.

**Comment by nvllz** [comment]
If you want to remove a song from the playlist, you can swipe it to the side when in unlocked mode (padlock icon).

**Comment by Username1-a** [comment]
Perhaps, also adding a little "Delete" or "Remove from playlist" option (in addition to editing padlock) to song's 3-dot menu inside a playlist would make it more streamlined UX-wise (instead of swiping all the way to the top to unlock the editing padlock and remove that particular song, after all there's an options to "remove downloaded" and "remove from library" in 3-dot menu, so why not)

But unfortunately looks like the dev closed the similar issue that mentions this: https://github.com/z-huang/InnerTune/issues/1187

Here's some mockup image:
![294791755-e0951838-e7a0-45b3-ae3f-20c5c07292cd (2)](https://github.com/z-huang/InnerTune/assets/47947180/a26c8b02-bba6-4e71-b11c-c3fb6ef9947d)

**Comment by pdimu** [comment]
Hey, @Username1-a what did you use for designing that, illustrator or something? I'd like to use the tool so that I could make only one 'Library' tab, not three (I mean, a 3-in-1 tab with songs, artists and albums)

**Comment by Username1-a** [comment]
@okgamr Sorry, that was just an edited screenshot in some image editor

**Comment by nvllz** [comment]
@Username1-a Are you still using InnerTune? We both stopped contributing as it become stale, but wonder if you still enjoy the app :D

I personally do. But lack of so many things I've spent my time on is kinda heartbreaking. Maybe one day they'll make a release.. Hahah.

**Comment by Username1-a** [comment]
@nvllz Yeah, I still use InnerTune, some parts of the app aren't loading ofc, but in general it's still usable for finding the new music and I just like it's minimal and streamlined UI

You might be interested in an updated InnerTune Fork by Malopieds (https://github.com/Malopieds/InnerTune), it has some UI changes, but afaik it has no issues with loading different app parts

**Comment by nvllz** [comment]
Yeah, I also noticed some modules to be broken, but just love this app. 

For the updated fork - shame I can't install it next to the original Innertune to check it out; it would make me download the songs again which is not worth it as long as this one works. But I'm kinda sad we gave our heart and it's all for nothing.

Take care, maybe one day..

**Comment by macharia22** [comment]
What's exactly going on?

**Comment by pdimu** [comment]
> @okgamr Sorry, that was just an edited screenshot in some image editor

oh, i thought you may have used illustrator or inkscape. i think i will use inkscape to do the tab. thanks anyways
**_BUT_** can you say what image editor?

**Comment by z-huang** [comment]
> Perhaps, also adding a little "Delete" or "Remove from playlist" option (in addition to editing padlock) to song's 3-dot menu inside a playlist would make it more streamlined UX-wise (instead of swiping all the way to the top to unlock the editing padlock and remove that particular song, after all there's an options to "remove downloaded" and "remove from library" in 3-dot menu, so why not)
> 
> But unfortunately looks like the dev closed the similar issue that mentions this: #1187
> 
> Here's some mockup image: ![294791755-e0951838-e7a0-45b3-ae3f-20c5c07292cd (2)](https://private-user-images.githubusercontent.com/47947180/295967647-a26c8b02-bba6-4e71-b11c-c3fb6ef9947d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3NzM5OTMsIm5iZiI6MTcyMjc3MzY5MywicGF0aCI6Ii80Nzk0NzE4MC8yOTU5Njc2NDctYTI2YzhiMDItYmJhNi00ZTcxLWIxMWMtYzNmYjZlZjk5NDdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDEyMTQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4NTdlZTU2ZDZlNmMzZjRiZTQ3Mzc5N2QyZTJiZDU2ZDMzODUwMjBiZDkxN2FlZWUwYTFjMWYxNzJiOTliNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bpnF2uDJVsv5Q7_Icli9f-lxgnYjgPWF_QMgpL_rIhE)

I agree to your suggestion. However, due to implementation complexity, I didn't add this at first. I'll consider adding this button.

**Comment by z-huang** [comment]
Added in a542b82f76bf52568b6cc347d551aeff8b3093c3
