### ISSUE TITLE
Colour of Explore won't change if you go to the tab after searching anything

### ISSUE THREAD

**Issue by nikhilCad** [z-huang/music#12]
Title is little confusing. Here are steps

1. Go to explore tab. Icon turns blue
2. Search anything on explore
3. Keeping the search as is switch to any other tab on the bottom like artist, songs etc.
4. Now go back to explore tab
5. You will see it's icon won't turn blue even if it's the current tab

**Comment by z-huang** [comment]
Interesting... It may have something to do with the navigation system. I'll try to dig into the cause.
