### ISSUE TITLE
view artist

### ISSUE THREAD

**Issue by senolfndk** [z-huang/music#1200]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

When I click on view the artist, the page cannot be displayed.

### Expected behavior

When I click on view the artist, the page cannot be displayed.

### Actual behavior

When I click on view the artist, the page cannot be displayed.

### Screenshots/Screen recordings

![Screenshot_20240111-190757_InnerTune](https://github.com/z-huang/InnerTune/assets/52818836/a0b04124-b3df-458d-98eb-486be34a6b56)

### Logs

When I click on view the artist, the page cannot be displayed.

### InnerTune version

0.5.3

### Android version

android 12

**Comment by owenconnorz** [comment]
Check the new debug version dude may off been fixed @senolfndk

**Comment by z-huang** [comment]
Please check again or provide logs.

**Comment by senolfndk** [comment]
> Lütfen tekrar kontrol edin veya günlükleri sağlayın.

I'm not an expert on logs
