### ISSUE TITLE
Can't get songs, singles and albums from an artist

### ISSUE THREAD

**Issue by attilafekete73** [z-huang/music#1203]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Go to any artist page, then when you click on the albums for the list of the artist's albums, it is just seems like it's loading, but no matter how much I wait, it doesn't load. It's the same with singles and songs, however the videos seem to load as the should. 

### Expected behavior

It should load the songs, singles, albums of the artist

### Actual behavior

Doesn't load

### Logs

"" 

### InnerTune version

0.5.3

### Android version

Android 13

**Comment by z-huang** [comment]
Please provide logs.

**Comment by attilafekete73** [comment]
Where can I get the logs? This is the only reason I didn't provide them

**Comment by tankaye09** [comment]
Experiencing this issue too

**Comment by BrenoQGC** [comment]
I'm also having this issue on my Redmi note 7
