### ISSUE TITLE
Navigation bar always visible.

### ISSUE THREAD

**Issue by Shaglok** [z-huang/music#1204]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Keep the down bar (home, songs, artista, etc) always visible or availabe with a gesture.

### Why do you want this feature?

If you browse into a lot of artists, songs, albums, etc it's to hard top return to the Home. If you viewed 17 artists, for example, you need to press (or swipe) "back" 17 times.

**Comment by anxiouslelimo** [comment]
This is a major usability improvement. Please implement.

**Comment by fallenjedi13** [comment]
It is a necessity as it would make navigation streamlined and intuitive. Right now, getting back to the home page is a tedious task after multiple searches.

**Comment by oguzsout** [comment]
Hey @anxiouslelimo , Let's say you have opened 17 screens and you want to return to the home screen? If you long press the back key on the current screen, it will return to the home screen.

**Comment by z-huang** [comment]
If you long press the back button, you can go to the home screen. Available in debug version.

**Comment by ghost** [comment]
@z-huang 

> If you long press the back button, you can go to the home screen. Available in debug version.

Does the said functionality work when [the gesture navigation ](https://developer.android.com/develop/ui/views/touch-and-input/gestures/gesturenav)  (Android 10+; the suggested default) is enabled?
