### ISSUE TITLE
Shuffle all music in your YTmusic account library

### ISSUE THREAD

**Issue by B9I4EveLiSA** [z-huang/music#1205]
### Checklist

- [x] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Is it possible to fetch data from ["Library"](https://music.youtube.com/library)? Would be awesome if you could shuffle all music from your account library. Cause for now only playlists are available, right?

### Why do you want this feature?

Its actually the only reason I am not using any YTmusic clients, except the official one. As far as I know, there is no (open source) app that has this feature.

### Additional information

What I did in the past is I would shuffle all songs, that are in my library and then create a new playlist out of that queue. Then you can access that playlist as always. Downside of that is that its only 25 songs long and would not be updated until you do it manually.

**Comment by B9I4EveLiSA** [comment]
Can someone please at least explain why this is not yet possible to implement?
Because I haven't even looked at the code, if its just an API limitation..
But I want this feature so bad, that I would do a fork and try to make this myself. So if you have anything to say, everything would be helpful.
Thanks in advance!

**Comment by z-huang** [comment]
Move to #1205
