### ISSUE TITLE
Some Featured Playlists Does Not Load

### ISSUE THREAD

**Issue by anxiouslelimo** [z-huang/music#1208]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Search for Pop Biggest Hits
2. Go to Featured Playlists Tab
3. Open Pop's Biggest Hits/Classis Feel-Good Pop

### Expected behavior

The playlist should load

### Actual behavior

The playlist does not load

### Logs

Nil

### InnerTune version

0.5.3

### Android version

Android 11

### Additional information

Suspecting that the number of songs in the playlist maybe causing the issue. On trying all the playlists with less than 100 songs load as expected. No playlists > 105 songs load. Some playlists with 105 songs load others doesn't.

**Comment by anxiouslelimo** [comment]
After reinstall the issue did not appear. Curiously i did a restore from backup and issue popped up again. Backup is not corrupted in my understanding because I got all my settings and playlists back. Uninstalled and manually created my entire playlists, artists and albums again. The issue does not seem to happen.

**Comment by anxiouslelimo** [comment]
Took a backup. Cleared the storage from Settings -> Apps. Restored the backup. Issue did not happen. Closing the issue.

**Comment by Bananaguns2** [comment]
What about 2,100+? I can't get my playlist to load from YouTube
