### ISSUE TITLE
Dev gone?

### ISSUE THREAD

**Issue by DeadSecTr** [z-huang/music#1215]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Is this a another abandoned project like similar apps?
Last update is a good half year ago...

### Expected behavior

Update this great app and please fix the bugs

### Actual behavior

Many bugs and missing futures

### Logs

None

### InnerTune version

0.5.3

### Android version

13

**Comment by Kass401** [comment]
The last debug version was 2 days ago...

**Comment by DeadSecTr** [comment]
Where can i find it?

**Comment by Kass401** [comment]
The very first link in the checklist you were supposed to check.

**Comment by DarkCrypt** [comment]
> The very first link in the checklist you were supposed to check.

And/or by clicking on the Actions tab.
