### ISSUE TITLE
New type of Dynamic theme

### ISSUE THREAD

**Issue by owenconnorz** [z-huang/music#1217]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Dynamic theme like simpmusic 

![Screenshot_20240121_080613_SimpMusic](https://github.com/z-huang/InnerTune/assets/96526481/ababb2c0-9035-4d4d-ab1e-c70cffc9fe03)

### Why do you want this feature?

The colours make the app pop out more instead of the dull colors already.

### Additional information

Also the mini player looks like this 

![Screenshot_20240121_080631_SimpMusic](https://github.com/z-huang/InnerTune/assets/96526481/80e03e44-cc4f-4193-a4e1-94a90b14c74a)

**Comment by pdimu** [comment]
I don't really think it's a good idea. Ok, maybe some themes for the player would be great (Oto Music has this), but the mini player is just perfect, nothing has to be changed there

**Comment by owenconnorz** [comment]
It already has a dynamic theme; I'm just adjusting the colors of that theme, as they don't stand out like most players.

**Comment by pdimu** [comment]
> It already has a dynamic theme; I'm just adjusting the colors of that theme, as they don't stand out like most players.

explain please, i can't understand what you are trying to say

**Comment by z-huang** [comment]
Not planned.
