### ISSUE TITLE
Telegram group 

### ISSUE THREAD

**Issue by feelsavvy** [z-huang/music#1218]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Can you create a telegram channel for connect with you 

### Why do you want this feature?

Can you create a telegram channel for connect with you

**Comment by owenconnorz** [comment]
It won't happen I asked about a discord server before but got a straight no! But would be so much easier to connect github to the discord sever and add features and bug reports on there so github doesn't get so many duplicate issues and also having a couple of moderators to keep the sever clean but I guess it's his choice.

**Comment by feelsavvy** [comment]
> It won't happen I asked about a discord server before but got a straight no! But would be so much easier to connect github to the discord sever and add features and bug reports on there so github doesn't get so many duplicate issues and also having a couple of moderators to keep the sever clean but I guess it's his choice.

Ok i understand

**Comment by nvllz** [comment]
Check out the [Discussions](https://github.com/z-huang/InnerTune/discussions) tab.

**Comment by feelsavvy** [comment]
No reason
