### ISSUE TITLE
Songs are not showing

### ISSUE THREAD

**Issue by feelsavvy** [z-huang/music#1219]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Go to artist profile
2. Click on songs(Blank)
3. Click on Singles(Blank)

### Expected behavior

Showing blank 

### Actual behavior

Showing blank

### Screenshots/Screen recordings

https://github.com/z-huang/InnerTune/assets/101614657/1206487a-df5c-4e0f-97da-be9704906b2f

### Logs

I can't do

### InnerTune version

0.5.3

### Android version

Android 13

**Comment by z-huang** [comment]
Fixed in #1182.

**Comment by thehiderrr** [comment]
Now what can I do, you didn't fix my issue?

**Comment by feelsavvy** [comment]
> Fixed in #1182.

I don't understand can you explain me

**Comment by z-huang** [comment]
Please try the latest debug version. It should be fixed.

**Comment by feelsavvy** [comment]
> Please try the latest debug version. It should be fixed.

Ok thanks
