### ISSUE TITLE
Delete/Remove option in Playlist 

### ISSUE THREAD

**Issue by feelsavvy** [z-huang/music#1221]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Give an option to delete/Remove songs in playlist

### Why do you want this feature?

Because I mistakenly add some wrong song in wrong playlist so that's why I need the option to remove

**Comment by owenconnorz** [comment]
Click the padlock then swipe to remove

**Comment by nvllz** [comment]
As said above. If you mean a bottom menu option, it's a duplicate https://github.com/z-huang/InnerTune/issues/1195.

**Comment by feelsavvy** [comment]
> Click the padlock then swipe to remove

Can you show me with a image

**Comment by feelsavvy** [comment]
> As said above. If you mean a bottom menu option, it's a duplicate #1195.

Thank you now I understand
