### ISSUE TITLE
Artist song list is blank

### ISSUE THREAD

**Issue by sancho1952007** [z-huang/music#1227]
### Checklist

- [x] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Search for an artist.
2. Open the artist's profile.
3. Click in the songs button.
4. Wait for the skeleton loading animation to end

### Expected behavior

Songs should be displayed.

### Actual behavior

It remains blank.

### Screenshots/Screen recordings

![image](https://github.com/z-huang/InnerTune/assets/73981314/dd0d12bb-af8f-42e4-94f2-67bdf0458d62)

### Logs

I don't have the logs :(

### InnerTune version

0.5.3

### Android version

Android 11, 14

### Additional information

I faced this issue on my old phone (Tecno, Android 11) and new phone (Samsung, Android 14) as well.

**Comment by owenconnorz** [comment]
Try the latest debug version @sancho1952007

**Comment by sancho1952007** [comment]
> Try the latest debug version @sancho1952007 

I installed the latest version from F Droid

**Comment by owenconnorz** [comment]
Use github actions page for the debug the fix hasn't been released yet

**Comment by Malgotra** [comment]
Innertune is fantastic app. I know @z-huang put a lot of effort to making it even better and also he is a busy person. But this bug annoying many users since couple of months which already fixed some weeks ago in debug version. But not every user download Innertune from GitHub. Some people download it from f-droid and izzydroid. I bet many users even doesn't have GitHub account. So please users like me deserves a little bug fix update.

**Comment by sancho1952007** [comment]
Sorry guys, unfortunately, I don't know how to debug APKs. I mostly work with full-stack work. Also am not sure how to get a debug APK from GitHub Actions.

I love the app so I would like to help if provided with how to do it.

**Comment by owenconnorz** [comment]
https://github.com/z-huang/InnerTune/actions/runs/7601255364/artifacts/1183893090

Or 


https://github.com/z-huang/InnerTune/actions/runs/7601255364

**Comment by sancho1952007** [comment]
It doesn't open after installation. The splash screen loads and then the app closes.

**Comment by owenconnorz** [comment]
Ohh strange try clearing data and force close

**Comment by sancho1952007** [comment]
> Ohh strange try clearing data and force close 

I tried all of these several times but still doesn't work.

It is strange.

But I think its an issue with the API or something.

**Comment by Spaceshiprace** [comment]
@owencz1998
I'm facing a similar issue but with albums section its just keep loading..
See
![Screenshot_2024-02-08-16-15-49-324_com zionhuang music_1](https://github.com/z-huang/InnerTune/assets/156727749/a109d9be-bec4-4429-98fc-97e6572f6ce6)

**Comment by z-huang** [comment]
Fixed in #1295.
