### ISSUE TITLE
Scrolling song titles

### ISSUE THREAD

**Issue by remissao** [z-huang/music#1229]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Long titles are impossible to visualize on the app. The titles should automatically scroll like in the example below from another app

https://github.com/z-huang/InnerTune/assets/4529190/0e1e49e2-7c80-4f08-af61-e5718245eb5a

### Why do you want this feature?

I want to be able to read the entire title of a song I don't know

**Comment by owenconnorz** [comment]
What app is that @remissao

**Comment by emlopes** [comment]
> What app is that @remissao 

Libretube
https://github.com/libre-tube/LibreTube

**Comment by owenconnorz** [comment]
Oh cool thanks mate

**Comment by Malopieds** [comment]
If anyone is interested, it has been implemented [here](https://github.com/Malopieds/InnerTune/commit/ba67f261265f82b9c12083f61aac7e5f92e1190f)
