### ISSUE TITLE
Default content country settings not working

### ISSUE THREAD

**Issue by W1zardK1ng** [z-huang/music#1234]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

New release albums and Mood and Genres in home page are not being show as per the Default content country setting. Its showing based on the IP address. When using a VPN its showing results of the country set by VPN.

### Expected behavior

When Default content country option is set, the app should show New release albums and Mood and Genres in home page based on it.

### Actual behavior

New release albums and Mood and Genres in home page is showing details based on the IP address of the phone.

### Logs

na

### InnerTune version

0.5.3

### Android version

Android 14

**Comment by z-huang** [comment]
See #1473.
