### ISSUE TITLE
Bug on artist page

### ISSUE THREAD

**Issue by Shi-Min-Yeoh** [z-huang/music#1235]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Go to certain song artist page
2. Press songs of artist
3. List of songs doesn't show
4. Press albums of artist
5. List of albums doesn't show
6. Press singles of artist
7. Singles of artist doesn't show

### Expected behavior

It should show list of songs, albums, and singles of artist

### Actual behavior

But it either keep loading or show empty pages

### Screenshots/Screen recordings

![Screenshot_20240211_103332](https://github.com/z-huang/InnerTune/assets/127620100/383042b4-d02e-436e-9023-c47af6cde1e8)
![Screenshot_20240211_103312](https://github.com/z-huang/InnerTune/assets/127620100/53a4295c-c03a-4394-b9cf-8513e7ef2a7a)
![Screenshot_20240211_103305](https://github.com/z-huang/InnerTune/assets/127620100/6c1e2886-5c5a-4bbf-9a92-6c0785549e94)

### InnerTune version

0.5.3

### Android version

Android 12

**Comment by Richard38907** [comment]
Same problem for me

**Comment by paulusversluis** [comment]
Same for me

**Comment by KaiwanGailan** [comment]
Same.

**Comment by heschy2** [comment]
Same for me. Worked a few months ago, so it must be a regression.

**Comment by heschy2** [comment]
Also, this seems to be related (of not a duplicate) to #1227

**Comment by z-huang** [comment]
Fixed.
