### ISSUE TITLE
Add songs to yt playlist

### ISSUE THREAD

**Issue by pablo03v** [z-huang/music#1237]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add songs to a playlist from my account not the device)

### Why do you want this feature?

Cause I listen to my playlists ob more than one device

### Additional information

Ideally the playlists would sync to the device playlists and be kept in sync with yt playlists

**Comment by owenconnorz** [comment]
@pabloscloud 
What like this app 

https://github.com/maxrave-dev/SimpMusic

**Comment by pabloscloud** [comment]
Possible, just love the design of InnerTune. SimpMusic looks trash tbh lol

**Comment by pablo03v** [comment]
Possible, just love the design of InnerTune. SimpMusic doesn't look like sth I would like to use

**Comment by z-huang** [comment]
Move to #1237
