### ISSUE TITLE
sync liked albums with account

### ISSUE THREAD

**Issue by gmankab** [z-huang/music#1239]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

can you please add liked albums synchronization with account

### Why do you want this feature?

because i have lot of liked albums and without sync i need to find every album and like it again

**Comment by DD3Boh** [comment]
I just wrote something like this request, although it's not finished yet (at least not in the way I'd want to do it).
As of now with this patch you'd be able to see saved albums when opening the "Account" section.

Here's a link to the patch: https://github.com/DD3Boh/InnerTune/commit/d31952d8782c74b8a51ace83bec9e05e794be810

**Comment by gmankab** [comment]
thank you

can you please build apk?

**Comment by z-huang** [comment]
Move to #1409
