### ISSUE TITLE
Explore tab enhancement

### ISSUE THREAD

**Issue by NR8124** [z-huang/music#124]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description
https://beatbump.ml/
![image](https://user-images.githubusercontent.com/88180887/174531813-7b8a6032-edf5-4280-a463-38fd56fa3977.png)

https://music.youtube.com/explore
![image](https://user-images.githubusercontent.com/88180887/174532477-7934267f-26a8-4cc6-983f-52d4fc5b6292.png)

https://beatbump.ml/ is also a similar project which includes these suggestions and explore features
also the official ytmusic have something similar...
can you implement these things in your explore tab 
i.e. i just want some suggestions, genre etc in the explore rather than just going and searching ....

### Why do you want this feature?

These suggestions and that genre category in explore tab will make app more convenient, useful  and will be 1 step more closer to all the other streaming services like YTmusic etc

### Additional information

Love your work and hard work ❤🙌

**Comment by z-huang** [comment]
This issue is close to #43. Now I'm working on a new YouTube library to get YTM home and explore page information.
