### ISSUE TITLE
waiting for new version

### ISSUE THREAD

**Issue by Kabuki1212** [z-huang/music#1241]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

waiting for new version

### Why do you want this feature?

to work

### Additional information

waiting new version

**Comment by DeadSecTr** [comment]
Dont expect further updates for innertune imho...

**Comment by Spaceshiprace** [comment]
> Dont expect further updates for innertune imho...

why ?

**Comment by DeadSecTr** [comment]
Cuz dev has abandoned this

**Comment by owenconnorz** [comment]
I think he is busy with university or something. I am not sure if it is his last year, but maybe he will continue later on.

**Comment by DeadSecTr** [comment]
Thats ok...i understand...but any statemant or else from dev where be helpfull....

Btw...last version is 6months... Donno....

**Comment by Spaceshiprace** [comment]
6 months its too much fr, wish he continue asap...

**Comment by DeadSecTr** [comment]
Yes hope so

Innertune is or was the best Music Stream app with the nicest looking imho

**Comment by owenconnorz** [comment]
Iv gone to Simpmusic for now as it syncs with youtube music which was handy for me and has loads more features.

**Comment by NikunjK8** [comment]
Same here. Innertune has the the cleanest UI and best UX (it's so smooth, also notice the animations) compared to other yt music apps.

**Comment by DeadSecTr** [comment]
Guys try Harmony Music!

It comes with Piped sync...give it a try...cuz innertune is dead

**Comment by NikunjK8** [comment]
> Guys try Harmony Music!
> 
> It comes with Piped sync...give it a try...cuz innertune is dead

There are more options. RiMusic is a direct fork of ViMusic with many more features and same interface as Harmony/Vi. It also has the fastest development cycle and gets updates every week. SimpMusic has Spotify like playing screen and lyrics.

Also i don't think Innertune is dead and dev might return. He did came back once before. I've tried dozen of ytmusic apps and Innertune still has the best UX among them.

**Comment by rikuf2** [comment]
Last commit to main was literally 2 months ago. I don't think that's abandoning since people have other things to do than update an app that doesn't even need updating.

**Comment by siggi1984** [comment]
As long as development is at a standstill, you can use a fork, e.g. this one (has just released a new version)

https://github.com/Malopieds/InnerTune/releases/tag/v0.5.5

**Comment by kacperwyczawski** [comment]
@Kabuki1212 this is not an appropriate feature request. Please make it more focused on a concrete feature or close it.

**Comment by DeadSecTr** [comment]
Or try Harmony Music (it comes with app and PC Prog.)

**Comment by pdimu** [comment]
How many of you know @z-huang in real life?

**Comment by z-huang** [comment]
I'll release a new version soon!

**Comment by NikunjK8** [comment]
The G.O.A.T is back 👑
