### ISSUE TITLE
 Crash when trying to share artist profile page

### ISSUE THREAD

**Issue by lemon-hope** [z-huang/music#1248]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Go to artist profile page / channel 
2. Click on share button and the application will crash.
 

### Expected behavior

Be able to share the artist profile page by providing the link to the page without crashing.

### Actual behavior

The application will crash and stop unexpectedly.

### Screenshots/Screen recordings

![Screenshot_20240](https://github.com/z-huang/InnerTune/assets/104698909/67f80fc6-673f-4e50-a1e8-08b1b3ad89af)

### Logs

As a simple user, I don't know how to get log files. 

### InnerTune version

0.53

### Android version

Tested on Android 13

**Comment by Malopieds** [comment]
I cannot reproduce it. I will need some logs to know exactly what happened.
To do so, you can install [android debug bridge (adb)](https://developer.android.com/tools/adb) depending on your machine. Enable it on you device. Once everything is done you can type this command : `adb logcat -d | grep 'com.zionhuang.music' -B 100 -A 100 > log` it will produce a file called log. Send it here for further examination.

**Comment by z-huang** [comment]
Closed for inactive.
