### ISSUE TITLE
Pls Add some Extra new feature pls

### ISSUE THREAD

**Issue by kr812** [z-huang/music#1256]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Pls add some advance extra features in this app btw 1000 times thanks for making this app

### Why do you want this feature?

You are amazing man

### Additional information

Nice app but pls add some extra features

**Comment by DeadSecTr** [comment]
What feautures?

**Comment by z-huang** [comment]
Please specify features.
