### ISSUE TITLE
dark fork

### ISSUE THREAD

**Issue by IzzySoft** [z-huang/music#1257]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

you might want to take a look at https://github.com/Arturo254/InnerTune – a fork that seems to have removed all attribution, but forgot to change its packageName.

### Why do you want this feature?

n/a

**Comment by ikanakova** [comment]
Auturo254 doesn't even feel like it's doing anything wrong - https://github.com/Arturo254/RiMusic/issues/3#issuecomment-2041486557

**Comment by z-huang** [comment]
Thankfully he added attribution to readme, and he is considering rebranding.

**Comment by MarcusNilo** [comment]
Even though he added attribution, I find this practice dishonest.

**Comment by whistlingwoods** [comment]
Questions are being asked https://github.com/Arturo254/InnerTune/issues/103
