### ISSUE TITLE
大佬，可以提供youtube v1接口的api文档吗，感谢🙏

### ISSUE THREAD

**Issue by aikorola** [z-huang/music#1258]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

youtube v1 api接口

### Why do you want this feature?

想进行二次开发

**Comment by z-huang** [comment]
You can take a look at the `innertube` module. It shows how to use the response from youtube.
