### ISSUE TITLE
sync history with yt music

### ISSUE THREAD

**Issue by farahalibrahim** [z-huang/music#1259]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

when playing a track it should be added to yt music history not to local history only

### Why do you want this feature?

I started fully depending on innertune rather than yt music original on my phone yet for my pc i am gorced to use yt music but all listening history on my phone isn't visible 

### Additional information

it is already implemented in simpmusic but i love the general ui of innertune way over simpmusic
![Screenshot_20240407_081956_SimpMusic](https://github.com/z-huang/InnerTune/assets/160879171/84b86637-de72-4145-b092-11f8af140420)

**Comment by z-huang** [comment]
Move to #1409
