### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by RANGARIRAIMUTOMBO** [z-huang/music#1261]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

make the app allow us to play and download video please 

### Why do you want this feature?

its just go to hve music and musical video in one app

**Comment by z-huang** [comment]
Duplicate of #1006

**Comment by SiddhantRakh** [comment]
> Duplicate of #1006

Is z-huang finally back?
