### ISSUE TITLE
Auto sync playlist, library, likes, etc. when launch app.

### ISSUE THREAD

**Issue by IlIllIl** [z-huang/music#1263]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add a option to enable autosync in setting

### Why do you want this feature?

Automatically update contents like rss feeds.

**Comment by z-huang** [comment]
Well, you can swipe down in home screen to refresh contents. If you're referring to syncing with YouTube account, there're already issues about that, and I'm considering it.
