### ISSUE TITLE
Shuffle songs after playing a song you choose

### ISSUE THREAD

**Issue by VihaanToTheRescue** [z-huang/music#1264]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

The app is great, but it can be improved by adding a shuffle button in the now playing interface where there are options for repeating the song but not for shuffling the playlist after you have heard the song. So what I am suggesting is when you play a song you like and then you wanna shuffle your playlist. You can do it by pressing that button. That feature can be implemented in the same button as the repeat button. 

### Why do you want this feature?

I like hearing songs after I have heard a song that's my favorite. So please consider adding this feature
Thank you. 

### Additional information

![Screenshot_20240418-121402~2](https://github.com/z-huang/InnerTune/assets/88080742/e2c978df-9b1b-488e-b9c0-caba7d2fe016)
Adding a shuffle button there will be helpful

**Comment by nvllz** [comment]
I think you can accomplish this by tapping the queue icon (the first one on the bottom bar) and shuffling from there. If you mean shuffling only the remaining songs, my bet is that's too niche to be considered.

**Comment by VihaanToTheRescue** [comment]
I am very sorry. I did not look for the button there. Sorry for the inconvenience
