### ISSUE TITLE
There are no songs in the profile, singles remain loading etc.

### ISSUE THREAD

**Issue by sonisaltiner** [z-huang/music#1266]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Greetings. I am experiencing bugs, as you can see in the video I have attached the link to, which you can view by downloading. The link is reliable, rest assured.

[https://ufile.io/jsw4rlnl](https://ufile.io/jsw4rlnl)

### InnerTune version

0.5.3

### Android version

Android 9

### Additional information

Huawei MRD-LX1 tried on device.

**Comment by yeaimgoinghome** [comment]
Same problem on Samsung a51 4g

**Comment by Arqueria** [comment]
Same issue on Samsung S20 and Samsung Tablet S9 Ultra. A related issue seems to be: I can no longer sync my playlists from Youtube, and my playlists from youtube do not load when going through Home -> Account -> some playlist.

**Comment by d4f5409d** [comment]
Same issue here since months, OnePlus 8, Android 13, latest Innertune version.

**Comment by z-huang** [comment]
Fixed.
