### ISSUE TITLE
App opens all YouTube links from discord by default, can't seemingly stop it. 

### ISSUE THREAD

**Issue by Cosmic-Downpour** [z-huang/music#1267]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1:open discord app.
2:click on a YouTube link and select open, or from within an embedded player, click the YouTube logo to switch to (ideally) a browser/app version of YouTube to continue watching the video. 

### Expected behavior

It should open the YouTube link in YouTube (*the YouTube app) or the default system browser to continue watching the video natively through YouTube's services, allowing you to read and post comments, and view the video description (as opposed to an embedded video)

### Actual behavior

It opens the innertune app instead, on the default page, not at all opening the link. This makes it difficult to open YouTube videos from discord, leading to you instead needing to copy the link, and paste it into the browser instead to open it. 

### Logs

(Can't find any mention of logs in the settings? I apologize if this would be helpful, I'm a novice just trying to report an issue as best I can)

### InnerTune version

0.5.3

### Android version

14

### Additional information

I have the default YouTube app disabled, as well as YouTube music; I have Firefox set as my default browser and expect it to open links, including YouTube links, by default. I have the ability for innertune to open links disabled under default app settings, and I don't see an option to set what apps should open what in discords settings, so I'm at a complete loss. This has only been an issue when innertune is installed.
My assumption is that some part of innertune flags itself as capable of opening links for YouTube (YouTube.com), not just YouTube music (music.youtube.com), despite the fact it cannot open video links. 

(edit in brackets with asterisk for clarification)

**Comment by RedNas74** [comment]
I tried it on my tablet. But Youtube opens for me normally. Have you set all Youtube links to the Youtube app in settings?

**Comment by Cosmic-Downpour** [comment]
As I said in my bug report, I have the default YouTube app disabled, and I use Firefox browser to watch YouTube. I have open links disabled in the settings for innertune, and the problem only exists when innertune is installed. Firefox does not have a setting to set it as the default for YouTube links, and discord doesn't allow you to set what apps it should open links with. So it comes down to innertune somehow flagging itself as an app for opening YouTube links, and because I can't set Firefox as a default to open YouTube links, and I actively have inner tune set to not open links on its own, so somehow discord and other apps are picking up that innertune is a default for opening YouTube links without a setting to change it. I'm on an unmodified pixel 6a running android 14 on the latest version of inner tune. 

I don't think it should be seen as unusual that I have the official YouTube app disabled, when I'm also using inner tune (a non standard YouTube music app) as well; and the biggest problem for me is that inner tune is handling YouTube link opening, but can't actually open YouTube links, leading to a dead end interaction that's bugged.

**Comment by uwu-gl** [comment]
Likes you're using AOSP-Based ROM
Try this:
Settings -> Apps -> See all [number] apps -> InnerTune -> Open by default.
Close all the switches and try again.

**Comment by uwu-gl** [comment]
What's more, I think this isn't InnerTune's issue

**Comment by Cosmic-Downpour** [comment]
> Likes you're using AOSP-Based ROM Try this: Settings -> Apps -> See all [number] apps -> InnerTune -> Open by default. Close all the switches and try again.

I wouldn't be making this thread if I hadn't already done this. It only happens when innertune is installed, I even installed an alternative video app, grayjay, and set it to open YouTube links, with all link opening permissions disabled for innertune, and it still somehow forces priority and opens YouTube links by default.

**Comment by Cosmic-Downpour** [comment]
> Likes you're using AOSP-Based ROM Try this: Settings -> Apps -> See all [number] apps -> InnerTune -> Open by default. Close all the switches and try again.

These are literally the steps I already described taking in my bug description.

**Comment by Ribelio** [comment]
I've noticed this same issue on different types of Embedded links like trailers in a trakt frontend app called Cinexplore. 

I do have a default youtube links app enabled yet this one opens instead and never "plays" said link, it'll only open the default home tab.

**Comment by Cosmic-Downpour** [comment]
> I've noticed this same issue on different types of Embedded links like trailers in a trakt frontend app called Cinexplore.
> 
> I do have a default youtube links app enabled yet this one opens instead and never "plays" said link, it'll only open the default home tab.

Yep, it seems to be the same issue. I'm starting to realize it's not just discord that does it, and I even installed grayjay and set it to my default YouTube player, and innertune is still opening YouTube links when it shouldn't be, and can't actually complete, as it just opens the app at the home page, but can't actually play YouTube links.

**Comment by ThomasBaruzier** [comment]
Hey,

Same issue here. HyperOS 1.0.
I feel like the only way around this problem would be to either enable youtube or make an app that does the forwarding.

My situation is the same as yours. I use firefox to watch my videos, and youtube is disabled because of privacy concerns and battery usage.

I also disabled opening links for Innertune in the settings:

![Screenshot_2024-06-08-23-01-12-638_com android settings](https://github.com/z-huang/InnerTune/assets/119688458/470e4efb-9596-44c3-81b7-3492306a78b5)

That didn't work.

I investigated the issue further by blocking discord from opening other apps. Surprisingly, Discord is trying to open InnerTune directly, instead of trying to launch the link through a more generalized process that would take it to Firefox.

![Screenshot_2024-06-08-23-06-20-948_com discord-edit](https://github.com/z-huang/InnerTune/assets/119688458/fe3f2bc1-6e30-4107-99ef-d5b5ed249357)

Also, InnerTune isn't set as a default app in any of the proposed categories:

![Screenshot_2024-06-08-23-19-29-925_com android settings](https://github.com/z-huang/InnerTune/assets/119688458/53c222b8-b490-4612-94e6-c5f53a2b6597)

Regarding other apps such as Whatsapp or Microsoft Teams, they behave correctly. But I remember that some other apps besides Discord do have this issue, so that points that there is a potential issue regarding InnerTune's identity to the Android system.

Thanks for this app btw. Other than that, it is really cool 😄

**Comment by z-huang** [comment]
This app just registers some url schemes it can open (https://github.com/z-huang/InnerTune/blob/b495c839ac25e3ce69a2c25708249b70bfb33e25/app/src/main/AndroidManifest.xml#L61C17-L76C56). The decision-maker of which app to open the link should be Android.

**Comment by ghost** [comment]
> This app just registers some url schemes it can open (https://github.com/z-huang/InnerTune/blob/b495c839ac25e3ce69a2c25708249b70bfb33e25/app/src/main/AndroidManifest.xml#L61C17-L76C56). The decision-maker of which app to open the link should be Android.

Would removing these lines and building the app by ourselves fix this issue?

**Comment by z-huang** [comment]
Yes, of course.
