### ISSUE TITLE
ability to block explicit songs

### ISSUE THREAD

**Issue by EspadaV8** [z-huang/music#1271]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

It would be great to stop explicit songs from being queued.

### Why do you want this feature?

Listening to music with children around and occasionally a song will get queued that is less than appropriate for their ages 😅

**Comment by pdimu** [comment]
2nd choice, use headphones 🎧

**Comment by EspadaV8** [comment]
> 2nd choice, use headphones 🎧

LOL. Doesn't work when you're playing it on Bluetooth for everyone to listen to.

Use case is like listening to music with people over. Don't want... WAP to suddenly come on (random extreme just as an example).

**Comment by pdimu** [comment]
💀 you right bro. Then I guess it would be useful to have this as a feature. At least an "E" sign would be useful

**Comment by YellowRoseCx** [comment]
I think thr opposite would also be helpful. Some songs have radio and explicit versions, it'd be nice to be able to default to the explicit version. Maybe a toggle switch

**Comment by z-huang** [comment]
If an explicit song is in an album, which is better: hide the song, or show the song, but make it unable to click.

**Comment by EspadaV8** [comment]
@z-huang if you're browsing, probably making it unclickable would be best. If you're listening and viewing the queue, I'd expect to not show the songs at all. If you're looking at a presaved playlist, then they would be unclickable.

**Comment by hindr86** [comment]
@z-huang this is a screenshot of how another popular music streaming service handles explicit music within their app.

![Screenshot_20240816-224528](https://github.com/user-attachments/assets/8d507e18-cc99-4d4a-9254-48606f920a0c)

Personally, this setting being added would be a game changer for me.

**Comment by EspadaV8** [comment]
YouTube Music has just the one setting

![Screenshot_20240817-135741](https://github.com/user-attachments/assets/86b49c72-8a55-4323-89b3-1773d116a218)

I'm not sure how that behaves within the app though (if it just hides songs everywhere, or makes some of them unclickable).

**Comment by EspadaV8** [comment]
Oh my gosh. That's amazing @z-huang . As soon as this makes into a release I'll be giving it a go. Thank you 🙏

**Comment by z-huang** [comment]
Thanks!
Note that album songs won't be filtered out because local database doesn't does store explicit information.
You can try debug build first!

**Comment by EspadaV8** [comment]
Downloaded that and installed it.

- Opened app and see this

![Screenshot_20240818-003713](https://github.com/user-attachments/assets/69e43bda-8bbf-4e67-9881-f53e6acf6fd0)


- Enable new setting

![Screenshot_20240818-003726](https://github.com/user-attachments/assets/2a968eae-5d20-461a-9c4f-850bb1eed708)

- Go back to home page and those explicit songs are still present, and they can be clicked on, playing them still works.

- Search for something that lists explicit songs, I searched for Eminem, and it doesn't list any that are tagged as explicit.

- Got to an album and like you said, that does continue to list the explicit songs.

Seems to work really well. Thanks again. Is it possible to stop an explicit song from being played if it is clicked on, so even though they are shown on an album page, it won't allow it to be played?

**Comment by z-huang** [comment]
> Go back to home page and those explicit songs are still present, and they can be clicked on, playing them still works.

**Comment by z-huang** [comment]
> Go back to home page and those explicit songs are still present, and they can be clicked on, playing them still works.

Refresh needed.

> Is it possible to stop an explicit song from being played if it is clicked on, so even though they are shown on an album page, it won't allow it to be played?

When displaying album songs, they are first stored into local database, and as I said, local database doesn't contain explicit information. Therefore, the app doesn't know if the song is explicit in album screen.
