### ISSUE TITLE
New release albums based on country, not feed

### ISSUE THREAD

**Issue by pdimu** [z-huang/music#1274]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [ ] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Going on the home tab
2. Seeing bad music I don't listen on YT Music

### Expected behavior

Gets music from the current country but not the recent listened music

### Actual behavior

Nothing wrong, but the genre of the music

### Screenshots/Screen recordings

I mean, the new release albums are based on the country, and I only have bad music from bangers in this country
![Screenshot_2024-05-18-11-49-15-147_com.zionhuang.music.jpg](https://github.com/z-huang/InnerTune/assets/128509556/c0eee26a-9f30-4fd0-a49e-1c10cc2520c8)

May SpMp look better, but I'd like the new release albums to match the feed, not the country 

A taste of SpMp:
![Screenshot_2024-05-18-11-47-33-032_com.toasterofbread.spmp.jpg](https://github.com/z-huang/InnerTune/assets/128509556/e43f6027-85ae-43eb-ad51-e3a647f311f8)

### Logs

No

### InnerTune version

Latest - F-droid downloaded

### Android version

Android 12, MIUI 13 (total trash tbh)

### Additional information

Make the check boxes not absolutely necessary, or you won't know if the user properly looked for an original issue (I didn't but that's another story) - also I found out that in an edot these are no longer absolutely necessary

**Comment by z-huang** [comment]
New release albums are fetched from https://music.youtube.com/new_releases/albums, and I don't have control of the contents. Now I've revamped the home screen and it will recommend music based on your listen history. Also, the section of new release albums is moved to the bottom of the home screen, so if you don't like that section, just don't scroll to the very bottom :)
