### ISSUE TITLE
Crash when trying to download

### ISSUE THREAD

**Issue by SamuelGomer** [z-huang/music#1275]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Choose a album or song
2. Click on the respective download button
3. Crash

### Expected behavior

It should just download, it worked perfectly before but suddenly it crashes. I've already tried to completely reset and reinstall the app, sadly still not working.

### Actual behavior

The app crashes instantly, when I reopen it the chosen album shows the circular progress bar spinning endlessly.

### Logs

I hope this is it, the log was pretty long.

05-19 16:38:58.275  1061  3257 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.zionhuang.music/.MainActivity bnds=[829,831][988,990]} from uid 10018 on display 0
05-19 16:38:58.329  1061  3267 I ActivityManager: Start proc 4299:com.zionhuang.music/u0a100 for activity com.zionhuang.music/.MainActivity
05-19 16:38:58.367  4299  4299 W System  : ClassLoader referenced unknown path: /data/app/com.zionhuang.music-1/lib/arm64
05-19 16:38:58.589  4299  4299 D NetworkSecurityConfig: No Network Security Config specified, using platform default
05-19 16:38:58.595  1061  2253 D ConnectivityService: requestNetwork for uid/pid:10100/4299 NetworkRequest [ TRACK_DEFAULT id=7, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ]
05-19 16:38:58.596  1061  2168 D ConnectivityService: rematching NetworkAgentInfo [WIFI () - 100]
05-19 16:38:58.596  1061  2168 D ConnectivityService:  network has: [ Transports: WIFI Capabilities: NOT_METERED&INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&FOREGROUND LinkUpBandwidth>=1048576Kbps LinkDnBandwidth>=1048576Kbps SignalStrength: -38]
05-19 16:38:58.596  1061  2168 D ConnectivityService:   checking if request is satisfied: NetworkRequest [ TRACK_DEFAULT id=7, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ]
05-19 16:38:58.596  1061  2168 D ConnectivityService: currentScore = 0, newScore = 20
05-19 16:38:58.596  1061  2168 D ConnectivityService: rematch for NetworkAgentInfo [WIFI () - 100]
05-19 16:38:58.596  1061  2168 D ConnectivityService:    accepting network in place of null
05-19 16:38:58.596  1061  2168 D ConnectivityService: sending new Min Network Score(20): NetworkRequest [ TRACK_DEFAULT id=7, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ]
05-19 16:38:58.596  1061  2168 D ConnectivityService: Network NetworkAgentInfo [WIFI () - 100] was already satisfying request 6. No change.
05-19 16:38:58.596  1061  2168 D ConnectivityService: Network NetworkAgentInfo [WIFI () - 100] was already satisfying request 1. No change.
05-19 16:38:58.596  1061  2168 D ConnectivityService: sending notification AVAILABLE for NetworkRequest [ TRACK_DEFAULT id=7, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ]
05-19 16:38:58.599  2454  2454 D PhoneSwitcherNetworkRequstListener: got request NetworkRequest [ TRACK_DEFAULT id=7, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ] with score 20
05-19 16:38:58.609  1061  2764 I ActivityManager: Killing 3173:android.process.media/u0a9 (adj 906): empty #17
05-19 16:38:58.621  1061  3258 E WindowManager: App trying to use insecure INPUT_FEATURE_NO_INPUT_CHANNEL flag. Ignoring
05-19 16:38:58.627  1061  1086 D ActivityManager: cleanUpApplicationRecord -- 3173
05-19 16:38:58.712  4299  4304 I art     : Do partial code cache collection, code=24KB, data=30KB
05-19 16:38:58.712  4299  4304 I art     : After code cache collection, code=22KB, data=29KB
05-19 16:38:58.712  4299  4304 I art     : Increasing code cache capacity to 128KB
05-19 16:38:58.783  4299  4304 I art     : Do partial code cache collection, code=52KB, data=61KB
05-19 16:38:58.783  4299  4304 I art     : After code cache collection, code=52KB, data=61KB
05-19 16:38:58.783  4299  4304 I art     : Increasing code cache capacity to 256KB
05-19 16:38:58.897  4299  4326 I Adreno  : QUALCOMM build                   : ce5aeb9, I750f7f2fa6
05-19 16:38:58.897  4299  4326 I Adreno  : Build Date                       : 03/24/17
05-19 16:38:58.897  4299  4326 I Adreno  : OpenGL ES Shader Compiler Version: XE031.09.00.03
05-19 16:38:58.897  4299  4326 I Adreno  : Local Branch                     : 
05-19 16:38:58.897  4299  4326 I Adreno  : Remote Branch                    : quic/LA.BF64.1.2.3_rb1.11
05-19 16:38:58.897  4299  4326 I Adreno  : Remote Branch                    : NONE
05-19 16:38:58.897  4299  4326 I Adreno  : Reconstruct Branch               : NOTHING
05-19 16:38:58.905  4299  4326 I OpenGLRenderer: Initialized EGL, version 1.4
05-19 16:38:58.905  4299  4326 D OpenGLRenderer: Swap behavior 1
05-19 16:38:58.924  4299  4304 I art     : Do full code cache collection, code=97KB, data=121KB
05-19 16:38:58.924  4299  4304 I art     : Starting a blocking GC JitCodeCache
05-19 16:38:58.924  4299  4304 I art     : After code cache collection, code=84KB, data=65KB
05-19 16:38:58.925  4299  4304 I art     : Compiler allocated 6MB to compile void y0.g.a(char, float[])
05-19 16:38:58.983  4299  4304 I art     : Do partial code cache collection, code=100KB, data=93KB
05-19 16:38:58.984  4299  4304 I art     : After code cache collection, code=97KB, data=91KB
05-19 16:38:58.984  4299  4304 I art     : Increasing code cache capacity to 512KB
05-19 16:38:58.986  4299  4304 I art     : Compiler allocated 6MB to compile void j5.q.a(i5.y, i5.v, p0.f, e0.i, int, int)
05-19 16:38:59.009  4299  4299 D Compose Focus: Owner FocusChanged(true)
05-19 16:38:59.016  4299  4299 I ExoPlayerImpl: Init 812f70c [AndroidXMedia3/1.1.1] [sumire, Xperia Z5, Sony, 25]
05-19 16:38:59.255  4299  4304 I art     : Do full code cache collection, code=228KB, data=237KB

### InnerTune version

0.5.3

### Android version

Android 7.1.2

**Comment by z-huang** [comment]
Does it still happen?

**Comment by SamuelGomer** [comment]
@z-huang Everything works now as expected. Thank you!
