### ISSUE TITLE
Remove a single song from a playlist is not possible

### ISSUE THREAD

**Issue by Szakul59** [z-huang/music#1277]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Go to any playlist and remove one song

### Expected behavior

No option exists to "remove song from this playlist"

### Actual behavior

No option is available to remove a song from a playlist 

### Logs

Don't know what you asking for here, I am not a dev

### InnerTune version

0.5.3 FOSS

### Android version

Android 14

### Additional information

Thank you.

**Comment by Sensex00** [comment]
Hey can you give me my answer does every song you listen come appear in library because mine is not

**Comment by Szakul59** [comment]
Hi Sensex00,

Go to the play list, under the "shuffle" button you have the little lock
🔒. Unlock it. Then you can wipe a song you wish to remove.

Regards,

Lukasz

**Comment by Sensex00** [comment]
I mean in songs section in navbar songs I play not automatically present in its library I have to manually add to library button it there any any settings to do by default

**Comment by pdimu** [comment]
@Szakul59 you swipe the song. It's that simple

**Comment by Szakul59** [comment]
Yes, but, you have to unlock the playlist first

**Comment by pdimu** [comment]
**if** it is locked
