### ISSUE TITLE
Library automation and cache support 

### ISSUE THREAD

**Issue by Sensex00** [z-huang/music#1279]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add settings option to automatically add song which I have played show in library otherwise I have done it manually by clicking on add to library button

Cache system is broken like how do I find out song I listen have cached and add a way to see cache percentage like in apps similar vimusic rimusic 

### Why do you want this feature?

Both features comes in very handy like I have to just listen not doing anything manually I have shifted from these two apps add these two features these are very good 

### Additional information

You take all the information from vimusic vitune rimusic all these they are same like fork
Take these for example thank you 
![Screenshot_2024-05-24-22-06-50-607_it fast4x rimusic](https://github.com/z-huang/InnerTune/assets/168848690/7aa2426b-5c9f-466d-84cd-e6b7f8d00c22)

https://github.com/z-huang/InnerTune/assets/168848690/d5cecf7c-73e4-4d5a-a46c-0f2323befe07

As you can see in the video similar to vimusic by clicking on cover cache percentage can be seen

**Comment by z-huang** [comment]
Currently the app is not designed to show cache percentage for each song. I think a normal user doesn't need to check this information. However, you can check the total cache size in settings.
As for adding songs to library automatically, user can check their listen history and find their loved songs.

**Comment by Sensex00** [comment]
At least you can something do about library automation to add every song played in the Library without manually clicking on add to Library you can make an option in settings

**Comment by z-huang** [comment]
Okay, I'll take into consideration.

**Comment by aneesh1122** [comment]
> Okay, I'll take into consideration.

Adding cache percentage info would be pointless but could you create a new category "cached" beside downloaded and list all the cached songs?

**Comment by Sensex00** [comment]
> > Okay, I'll take into consideration.
> 
> Adding cache percentage info would be pointless but could you create a new category "cached" beside downloaded and list all the cached songs?

Ok Right as long as stats for nerds is available its good
