### ISSUE TITLE
Slideup window in player bottom sheet

### ISSUE THREAD

**Issue by owencz1998** [z-huang/music#128]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Integrate 3 tabs in on slide up window with all this content with swipe up then left or right to change tab.

![Screenshot_20220703-143216](https://user-images.githubusercontent.com/96526481/177042446-d3a0ba77-5ce3-4d3b-9dd0-ba0a54e8c873.jpg)

![Screenshot_20220703-143308_Music Debug](https://user-images.githubusercontent.com/96526481/177042277-f48b134c-c047-4984-a6ba-2abeb3fdcb25.jpg)

### Why do you want this feature?

Looks nice and and easier way to select a songs lyrics and ect on the media player window

### Additional information

Sorry for trying to explain it lol not really good at that.

**Comment by z-huang** [comment]
Yes, I'm going to implement this, after browse and search feature is done. But maybe it won't be a bottom sheet, I will think if there's other way to show these data.

**Comment by owencz1998** [comment]
No worries bro thanks 🙏
