### ISSUE TITLE
Add download feature

### ISSUE THREAD

**Issue by Fan-Bob** [z-huang/music#1283]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

add download music

### Why do you want this feature?

download is good for poor child in poor network area.

### Additional information

.

**Comment by macharia22** [comment]
How about any cross-fading options?

**Comment by z-huang** [comment]
Already exists.

**Comment by bazilbycom** [comment]
> Already exists.

It is downloading in data/app directory and not internal storage/.. We need a custom location support
