### ISSUE TITLE
Add background playback function to play simultaneously with other media playback clients

### ISSUE THREAD

**Issue by Fan-Bob** [z-huang/music#1284]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add background playback function to play simultaneously with other media playback clients

### Why do you want this feature?

Add background playback function to play simultaneously with other media playback clients

### Additional information

Add background playback function to play simultaneously with other media playback clients

**Comment by z-huang** [comment]
Not planned.
