### ISSUE TITLE
When a song is paused and moved to next/previous song, then the next song is also paused

### ISSUE THREAD

**Issue by Subikesh** [z-huang/music#1288]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

1. Select a song with some songs in the queue.
2. Pause current song
3. Move to the next/previous song.

Here, the expected behavior is that the next song starts playing. But the next song is also in paused state. 

### Why do you want this feature?

I think the accessibility is better if when moving to next song, it should start playing. The behavior is like this in spotify or YT music. 
I especially face this issue when using earphone gestures, if i unknowingly press pause instead of pressing next, I have to press next, and also unpause.

**Comment by z-huang** [comment]
Fixed in ff2ecdc93a050271086132624b5625831dc16a17
