### ISSUE TITLE
Multiple bluetooth speakers

### ISSUE THREAD

**Issue by jakobsn** [z-huang/music#1291]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I wish I could play songs from the application on multiple Bluetooth devices. From a previous experience I believe I was able to play on multiple speakers, but I can't figure out where to find that option. Is it possible to make this feature more visible or guide me to it if it exists?

### Why do you want this feature?

To play from multiple speakers in different rooms.

**Comment by z-huang** [comment]
This feature belongs to Android OS level, not the app level that I can resolve, from my understanding.
