### ISSUE TITLE
Album and Playlists API Changes

### ISSUE THREAD

**Issue by AbuTar** [z-huang/music#1295]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Open Innertune
Press on Account
Select a Playlist

### Expected behavior

Playlists load and I can download, add to queue, save to playlist etc....

### Actual behavior

The playlist doesn't load and I can't do anything 

### Screenshots/Screen recordings

![image](https://github.com/z-huang/InnerTune/assets/135345483/5fd1e3f2-31ee-4848-8374-b7f6a42384fa)

### Logs

gxh

### InnerTune version

0.5.3

### Android version

14

**Comment by BioTheHuman** [comment]
Yep, same.

I can't sync or import new playlists.

Still able to play a playlist already downloaded though

**Comment by Richard38907** [comment]
Same here. I tested on several yt music streaming apps, impossible to load these pages anymore since yesterday. There are a lot of comments about it.

You can use New Pipe at the moment to play them, it works for me. 

https://newpipe.net/#download

Just share the playlist from yt music with new pipe and the playlist will appear.

**Comment by 1seco** [comment]
Happens in other situations too. Going to an artist's account, and tapping the arrow to see more albums (or anything else for that matter) causes this problem, and nothing is loading, nor I see any network traffic (shown through a setting on my phone, updated ev sec.), instead one has to know the album name beforehand to search, maybe an inital ~4-6kb incoming data and nothing later. 
![Screenshot_20240622-162253_InnerTune_1](https://github.com/z-huang/InnerTune/assets/71955406/f5c575b2-7ae3-4cf4-bcba-ece6a490497a)

Cropped image of attempting to find more albums from an artist

**Comment by Malopieds** [comment]
Hi all, youtube updated their api, that's why. I'm currently working on a fix. I have successfully fixed the albums and playlists not loading. Have you seen this bug anywhere else?

Edit:
Maybe change the title to something more explicit since it's not an import issue

**Comment by AbuTar** [comment]
Any ideas for a better title? Youtube API issue etc....

**Comment by Malopieds** [comment]
> Any ideas for a better title? Youtube API issue etc....

What about Album and Playlists API changes?

**Comment by AbuTar** [comment]
Ok got it

> > Any ideas for a better title? Youtube API issue etc....
> 
> What about Album and Playlists API changes?

**Comment by Deemitry88** [comment]
Will you push and release the update soon ? I wanted to show the app to a friend

**Comment by Malopieds** [comment]
> Will you push and release the update soon ? I wanted to show the app to a friend

It's already pushed, I will try to release later today if I have time or tomorrow. If you just want to show it to a friend you can download [this](https://github.com/Malopieds/InnerTune/actions/runs/9627001158/artifacts/1627813334) version (it's a bit more laggy because it's debug)

**Comment by AbuTar** [comment]
> > Will you push and release the update soon ? I wanted to show the app to a friend
> 
> It's already pushed, I will try to release later today if I have time or tomorrow. If you just want to show it to a friend you can download [this](https://github.com/Malopieds/InnerTune/actions/runs/9627001158/artifacts/1627813334) version (it's a bit more laggy because it's debug)

Thanks for the hard work; I've been using the app as my go-to Spotify alternative. I'm interested though how you're able to roll out updates so quickly; I'm getting better at coding rn (start uni next year) and it seems like a very short amount of time spent on what seems like a big issue

**Comment by Malopieds** [comment]
> I'm interested though how you're able to roll out updates so quickly; I'm getting better at coding rn (start uni next year) and it seems like a very short amount of time spent on what seems like a big issue

I'm finishing my third year of computer science in a 5 year diploma, but doing side project is what gets you more experience imo. But it's not always easy to do both at the same time. This issue was not that big, it can seems huge because of the size of the json sent from youtube music, but the more you deal with it, the "easier" it gets (even though it's never fun, they're doing everything they can to stop people from using third party apps)

Anyway, [here](https://github.com/Malopieds/InnerTune/releases/tag/v0.5.7-rc2) is the link for the latest version.

**Comment by AbuTar** [comment]
Thanks! Hope everything goes well

**Comment by AbuTar** [comment]
Liked songs work for me now but my other playlists still aren't loading

**Comment by Malopieds** [comment]
> Liked songs work for me now but my other playlists still aren't loading

You mean Top playlist and offline playlists? Or playlist you made yourself? Both are working for me, if you have screenshot/if you want to open issue in my repo

**Comment by AbuTar** [comment]
> > Liked songs work for me now but my other playlists still aren't loading
> 
> You mean Top playlist and offline playlists? Or playlist you made yourself? Both are working for me, if you have screenshot/if you want to open issue in my repo

Playlists I've made in youtube music (besides my liked songs), for example nina Mix won't play ( A playlist made in yt music) but liked songs does work
![Screenshot_20240622_204543_InnerTune](https://github.com/z-huang/InnerTune/assets/135345483/df95b067-308c-4d24-8824-4870ecfb44ce)
![Screenshot_20240622_204527_InnerTune](https://github.com/z-huang/InnerTune/assets/135345483/86357b79-4525-44bb-9fd1-553d9d27e475)
![Screenshot_20240622_204520_InnerTune](https://github.com/z-huang/InnerTune/assets/135345483/b3689cb5-97b9-452f-a399-bca4f3fe4ad3)

**Comment by Malopieds** [comment]
> Playlists I've made in youtube music (besides my liked songs), for example nina Mix won't play ( A playlist made in yt music) but liked songs does work

Oh you mean the one linked to your account? Yeah I haven't thought of those ones since I don't use google. I'll make sure to correct this

**Comment by AbuTar** [comment]
Thanks! It doesn't have to be immediate though, I'm OK with just my liked songs for a while. Feel free to take your time

**Comment by ReallyYug** [comment]
> > Playlists I've made in youtube music (besides my liked songs), for example nina Mix won't play ( A playlist made in yt music) but liked songs does work
> 
> Oh you mean the one linked to your account? Yeah I haven't thought of those ones since I don't use google. I'll make sure to correct this

Do you know when you will be done with fixing that?

**Comment by Germsicle** [comment]
> ### Checklist
> * [x]  I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
> * [x]  I've checked that there is no open or closed issue about this bug.
> * [x]  This issue contains only one bug.
> * [x]  The title of this issue accurately describes the bug.
> 
> ### Steps to reproduce the bug
> Open Innertune Press on Account Select a Playlist
> 
> ### Expected behavior
> Playlists load and I can download, add to queue, save to playlist etc....
> 
> ### Actual behavior
> The playlist doesn't load and I can't do anything
> 
> ### Screenshots/Screen recordings
> ![image](https://private-user-images.githubusercontent.com/135345483/341905390-5fd1e3f2-31ee-4848-8374-b7f6a42384fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMzA3OTAsIm5iZiI6MTcxOTEzMDQ5MCwicGF0aCI6Ii8xMzUzNDU0ODMvMzQxOTA1MzkwLTVmZDFlM2YyLTMxZWUtNDg0OC04Mzc0LWI3ZjZhNDIzODRmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyM1QwODE0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODQ0ODNhNjZlM2M0MGEyMmIxMGM1NTRiYTMwYzUzYzQ4MDI5YzIzOTBhY2FmZmYyMDVlYjAxNTEzN2I1Yjg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qfeBp2v9xhWchyuSc7X3UdkNfOo9Jh2KOuYJV4mv7KQ)
> 
> ### Logs
> gxh
> 
> ### InnerTune version
> 0.5.3
> 
> ### Android version
> 14
> 
> ### Additional information
> _No response_

Same issue here....came here to check if it's been reported. Thanks OP

**Comment by Germsicle** [comment]
I had originally downloaded through droidify and didn't realize it was a much different version! I discovered the backup and restore option and decided to fresh install through github and WOWZERS! Totally different home screen than the droidify version, plus the bug fix woo! You have been busy and i LOVE this newer version even more! You rock!!! Thanks for all your work! Love this app!

**Comment by Malopieds** [comment]
> Do you know when you will be done with fixing that?

This is now fixed.
> Will this update be sent to droidify?

I don't handle that.

> I downloaded your fix but when installing it says cannot install due to conflicting api package with my guess that it has to be updated through droidify itself?

F-Droid are building the packages with their keys iirc, and since F-Droid and I don't have the same key, long story short you can't.

> I don't want to uninstall and lose all my settings and improted playlists etc :/ thanks for all your work! Love this app!

You can export them, it should save the playlists and settings (just not the downloaded songs). If you have another phone/emulator you can try to see if everything works well (there should be no problem if you export your data in the settings => backup and restore) .

In addition, to have an update on F-Droid you must have one from this repo and not mine. Plus F-Droid repos take some time to update, it's often better to take them directly from github or use apps that fetch it for you, for example [Obtainium](https://github.com/ImranR98/Obtainium).

**Comment by Germsicle** [comment]
Oops I just updated my comment didn't realize you would respond  so fast 🤗 all good! Thanks a million

**Comment by AbuTar** [comment]
Is this the top apk the one that's gully fixed 
![Screenshot_20240623_093946_Chrome](https://github.com/z-huang/InnerTune/assets/135345483/af7e8b82-32db-427c-bba3-c7719f69bcaa)

**Comment by Malopieds** [comment]
> Oops I just updated my comment didn't realize you would respond so fast 🤗 all good! Thanks a million

Haha no problem !

> Is this the top apk the one that's gully fixed

Yep, I wrote it in the Edit !

**Comment by d4f5409d** [comment]
@Malopieds can you add yours to Izzyondroid repo?

**Comment by AbuTar** [comment]
> > Oops I just updated my comment didn't realize you would respond so fast 🤗 all good! Thanks a million
> 
> Haha no problem !
> 
> > Is this the top apk the one that's gully fixed
> 
> Yep, I wrote it in the Edit !

Thanks a ton! Can I mark this issue as done now?

**Comment by Malopieds** [comment]
> @Malopieds can you add yours to Izzyondroid repo?

I don't do this, I think it has to be the maintainer of izzy to do this. But since the package is the same I don't think he would.

> Can I mark this issue as done now?

No, since it's not resolved here

**Comment by MehRad13** [comment]
I also have playlists issue. IT only shows the Album of the song I downloaded or seen, but doesn't show the album if didn't download it, played it or seen it. 

![Screenshot_20240623-142039](https://github.com/z-huang/InnerTune/assets/75393420/5f2f8621-b11f-44bb-943e-0c0022b99335)
![Screenshot_20240623-142046](https://github.com/z-huang/InnerTune/assets/75393420/8f8a2dc4-e59c-460f-ae0b-5cbf7a3e8089)

**Comment by wglee99** [comment]
> I also have playlists issue. IT only shows the Album of the song I downloaded or seen, but doesn't show the album if didn't download it, played it or seen it.
> 
> ![Screenshot_20240623-142039](https://private-user-images.githubusercontent.com/75393420/342063928-5f2f8621-b11f-44bb-943e-0c0022b99335.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNDc0MjgsIm5iZiI6MTcxOTE0NzEyOCwicGF0aCI6Ii83NTM5MzQyMC8zNDIwNjM5MjgtNWYyZjg2MjEtYjExZi00NGJiLTk0M2UtMGMwMDIyYjk5MzM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDEyNTIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNGQ4NTUzM2UzNTc0ZDY3YzFkOTVmNzhmMjBkMWFiOTU2MjA4MmJjMjk5Y2VmNzQ4YWJkOTYzNjJmY2Q0NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qy8BEahqaeVfQB020WJySE-eq0VQrHWiMxEFIKL9l3w) ![Screenshot_20240623-142046](https://private-user-images.githubusercontent.com/75393420/342063941-8f8a2dc4-e59c-460f-ae0b-5cbf7a3e8089.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNDc0MjgsIm5iZiI6MTcxOTE0NzEyOCwicGF0aCI6Ii83NTM5MzQyMC8zNDIwNjM5NDEtOGY4YTJkYzQtZTU5Yy00NjBmLWFlMGItNWNiZjdhM2U4MDg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDEyNTIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3MzQwMDQ0N2NiYWFlYzIxOGU4YWM4MjczOTQ0NjlmMzYzYWVkMDQwOTUzY2E3YjdlZjhmMjViYzY4MDY5YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-Qr-J-PqvcsDGWK9cNbD1tR8WFzivX7r1Ohju89il3M)

Hello! @Malopieds has fixed the issue in his fork and released a working version I presume. Do check out his version! On a side note, @Malopieds would you mind going into a little more detail regarding the API changes from Youtube and the changes you made to the code (for educational purposes)? Appreciate it!

**Comment by d4f5409d** [comment]
> > @Malopieds can you add yours to Izzyondroid repo?
> 
> I don't do this, I think it has to be the maintainer of izzy to do this. But since the package is the same I don't think he would.

I think you have to get in touch with izzy. I am not sure how this works, but izzy's repo is different from F-Droid, not so strict. @IzzySoft 
I am sure you could resolve this, the app is in need of updates. Currently it's broken and unusable. I guess @z-huang doesn't have the time anymore to do it, so it's a blessing you could do the work.

**Comment by Malopieds** [comment]
> On a side note, @Malopieds would you mind going into a little more detail regarding the API changes from Youtube and the changes you made to the code (for educational purposes)? Appreciate it!

I started a discussion on my repo, feel free to ask questions [there](https://github.com/Malopieds/InnerTune/discussions/122)

> I think you have to get in touch with izzy. I am not sure how this works, but izzy's repo is different from F-Droid, not so strict. @IzzySoft
I am sure you could resolve this, the app is in need of updates. Currently it's broken and unusable. I guess @z-huang doesn't have the time anymore to do it, so it's a blessing you could do the work.

Let's see

**Comment by d4f5409d** [comment]
@Malopieds thank you in advance, our hero. 🫡

**Comment by IzzySoft** [comment]
> can you add yours to Izzyondroid repo?

Huh? Why? Why "add it"? It [is there](https://apt.izzysoft.de/fdroid/index/apk/com.zionhuang.music/) for more than 2 years already (since 2022-04-09). What do I miss here?

**Comment by ReallyYug** [comment]
@IzzySoft I think that person is talking about @Malopieds's repo not this repo

**Comment by IzzySoft** [comment]
Ah – sorry, had no time to follow the entire thread. Specific question then please :wink:

**Comment by Malopieds** [comment]
> Ah – sorry, had no time to follow the entire thread. Specific question then please 😉

I opened an issue on my repo for more clarity !

**Comment by zulfikarmu** [comment]
Hold the playlist and play it, it will be play the song. Click bottom left to see all playlists.
![Screenshot_20240624-125909](https://github.com/z-huang/InnerTune/assets/82703582/fd742175-40cc-40f0-8068-e00f71417979)
![Screenshot_20240624-125919](https://github.com/z-huang/InnerTune/assets/82703582/7f45963b-3593-4179-b521-e0e21f20dd64)

**Comment by Nitin927** [comment]
Album are not opening

**Comment by ReallyYug** [comment]
@Nitin927 are you using @Malopieds's forked version?

**Comment by 7heMech** [comment]
Hey, is there a way to update f-droid, sorry if you talked about that, I didn't read everything.

**Comment by Germsicle** [comment]
> Hey, is there a way to update f-droid, sorry if you talked about that, I didn't read everything.

Yeah they answered it... they don't control fdroid so no. But you can backup your settings and install the updated version above

**Comment by mikwee** [comment]
Albums that aren't hearted still don't open on @Malopieds's version

**Comment by Malopieds** [comment]
> Albums that aren't hearted still don't open on @Malopieds's version

I can assure you it does work. Please use the right version (the pre-release one, fix-login).

**Comment by mikwee** [comment]
@Malopieds Thanks. For future reference, the fix-login APK is inside v0.5.7-rc2.

**Comment by 7heMech** [comment]
> > Albums that aren't hearted still don't open on @Malopieds's version
> 
> I can assure you it does work. Please use the right version (the pre-release one, fix-login).

It works does crash sometimes, but does work 👍

**Comment by Malopieds** [comment]
> It works does crash sometimes

How so? Could you fill an issue in my repo maybe?

**Comment by 7heMech** [comment]
> > It works does crash sometimes
> 
> How so? Could you fill an issue in my repo maybe?

Well for example when you swipe it away on the apps screen, or when you put a sleep timer and turn of screen after a minute it stops playing (bit doesn't crash) and can't play anymore.

**Comment by Malopieds** [comment]
@7heMech please open an issue on my repo with logs and screenshots/scresnrecord otherwise I can't and won't help.

**Comment by Henry-Hiles** [comment]
Any chance of the fix being upstreamed?

**Comment by d4f5409d** [comment]
> Any chance of the fix being upstreamed?

Barely any. Only if @z-huang becomes available online.

**Comment by 7heMech** [comment]
> > Any chance of the fix being upstreamed?
> 
> Barely any. Only if @z-huang becomes available online.

If you open his profile you can see 4th of July commit in private repo

**Comment by d4f5409d** [comment]
> If you open his profile you can see 4th of July commit in private repo

💀💀💀

**Comment by 7heMech** [comment]
> @7heMech please open an issue on my repo with logs and screenshots/scresnrecord otherwise I can't and won't help.

Sorry for not getting back at you with this, but the issue has been resolved in your newer releases, thanks.

**Comment by z-huang** [comment]
The bug has been fixed. Thanks @Malopieds for the fix!

Sorry guys, I've been busy recently and hardly have time to work on this project. I still plan to maintain the project, though. I'll check the issues for other bugs and make a release!
