### ISSUE TITLE
Queues not working as intended

### ISSUE THREAD

**Issue by AbuTar** [z-huang/music#1297]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Essentially, anytime I select to add a song (any song from anywhere) to the queue it doesn't actually work. Not sure if this is a bug for just me or if it's this way for everyone. I also couldn't find a bug report on this so sorry if I've repeated something. ( a feature to view an actual queue might also be a nice thing to integrate whilst working on the issue)

### Expected behavior

When pressing add song to queue, songs are added to a queue to be played next 

### Actual behavior

Nothing happens 

### Logs

l

### InnerTune version

0.5.7-rc-2

### Android version

Android 14

### Additional information

Using an S23+

**Comment by Sunilr001** [comment]
From where you Downloaded this version 0.5.7-rc-2 ?

**Comment by AbuTar** [comment]
Check the thread below this one on github, something about playlists not loading

**Comment by Richard38907** [comment]
It snap fork

**Comment by z-huang** [comment]
> 0.5.7-rc-2

You're using other's fork.
