### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by Fan-Bob** [z-huang/music#1298]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

![Screenshot_20240629-160025_InnerTune](https://github.com/z-huang/InnerTune/assets/139612414/a68ce832-5bcf-419f-b6bd-31f22c279e1f)
Can't load playlist

### Expected behavior

![Screenshot_20240629-160025_InnerTune](https://github.com/z-huang/InnerTune/assets/139612414/a68ce832-5bcf-419f-b6bd-31f22c279e1f)
Can't load playlist

### Actual behavior

![Screenshot_20240629-160025_InnerTune](https://github.com/z-huang/InnerTune/assets/139612414/a68ce832-5bcf-419f-b6bd-31f22c279e1f)
Can't load playlist

### Screenshots/Screen recordings

![Screenshot_20240629-160025_InnerTune](https://github.com/z-huang/InnerTune/assets/139612414/a68ce832-5bcf-419f-b6bd-31f22c279e1f)
Can't load playlist

### Logs

![Screenshot_20240629-160025_InnerTune](https://github.com/z-huang/InnerTune/assets/139612414/a68ce832-5bcf-419f-b6bd-31f22c279e1f)
Can't load playlist

### InnerTune version

0.5.3

### Android version

Android 14

### Additional information

![Screenshot_20240629-160025_InnerTune](https://github.com/z-huang/InnerTune/assets/139612414/a68ce832-5bcf-419f-b6bd-31f22c279e1f)
Can't load playlist

**Comment by choozn** [comment]
Same issue with albums.

**Comment by choozn** [comment]
Duplicate of https://github.com/z-huang/InnerTune/issues/1295

**Comment by Nitin927** [comment]
Bro pls fix it fast

**Comment by choozn** [comment]
A solution for the bug is provided in the linked duplicate.

**Comment by WHONEYR** [comment]
> Uma solução para o bug é fornecida na cópia vinculada.

Where do I get this copy?

**Comment by choozn** [comment]
https://github.com/Malopieds/InnerTune/releases/

**Comment by z-huang** [comment]
Duplicate of #1295
