### ISSUE TITLE
Inconsistent Liked Songs Sorting: Added Songs Appear Mid-List, Not Newest First

### ISSUE THREAD

**Issue by Ahamed07** [z-huang/music#1299]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1.Open the music streaming app.
2.Locate a song you want to like.
3.Tap the heart icon to like the song.
4.Navigate to the "Liked Songs" section in the library.
5.Observe that the liked song is added in the middle of the list, not at the top.
6.if applicable, verify that the sorting by date is not working correctly.

### Expected behavior

this should add to the top of the liked song in the library

### Actual behavior

Instead of adding it to the top it adds to the middle or the lower part of the list

### Logs

-

### InnerTune version

0.5.7

### Android version

Android 14

### Additional information

i used the restore file from the original innertunes.

**Comment by Malopieds** [comment]
Hi, you're using the wrong repo...
Please see [this](https://github.com/Malopieds/InnerTune/issues/160)

**Comment by Ahamed07** [comment]
thanks for pointing it , i just complete forget and posted it on this repo . in your's it say it is solved and it should work . does the fix is live or will it release  with the future version ?

**Comment by Malopieds** [comment]
> does the fix is live or will it release with the future version

Next release !
