### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by Me0wzz** [z-huang/music#130]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Supporting Proxy makes user on YTM-restricted-country use this app more convinient.

### Why do you want this feature?

Youtube Music isn't available on some countries.
When searching items, There is no items on Songs/Videos tab unless I use Proxy/VPN. It's quite inconvinient to play songs now.

**Comment by z-huang** [comment]
Can you try this: [app-debug.zip](https://github.com/z-huang/music/files/9168257/app-debug.zip)? Does this work? (Restart the app after setting proxy to take effect)

**Comment by Me0wzz** [comment]
Using app with Proxy option works well. Thanks for the great feature!

**Comment by HikaruIchijyo** [comment]
> Using app with Proxy option works well. Thanks for the great feature!

Do u have any proxy url or sonething fr me to chk

**Comment by Me0wzz** [comment]
@HikaruIchijyo use Orbot as HTTP Proxy

**Comment by mukesh77700** [comment]
I want proxy url
