### ISSUE TITLE
YoutubeSponsorBlock integration?

### ISSUE THREAD

**Issue by kdg00** [z-huang/music#1301]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

There are a lot of songs on youtube with non music parts in them, an SponsorBlock has a filter for them

### Why do you want this feature?

It would be nice if it would just skip these parts

**Comment by filinux13** [comment]
Duplicate of #495 

Just use the radio version of the song
