### ISSUE TITLE
show new album release display can't play

### ISSUE THREAD

**Issue by hasanelfalakiy** [z-huang/music#1313]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

not yet, I can't reproduce it 

### Expected behavior

can be played directly

### Actual behavior

just endless loading placeholder displays

### Screenshots/Screen recordings

![IMG_20240805_215908](https://github.com/user-attachments/assets/ccb43d36-a91f-4849-9cd0-764e33836b8a)

### Logs

nothing 

### InnerTune version

0.5.4

### Android version

Android 11

**Comment by z-huang** [comment]
I didn't encounter this problem. Can you share logs?

**Comment by hasanelfalakiy** [comment]
> I didn't encounter this problem. Can you share logs?

where is the log?

**Comment by duraki** [comment]
Same for me

**Comment by hasanelfalakiy** [comment]
> Same for me

even in the search results the album section also cannot be opened and played

**Comment by z-huang** [comment]
https://developer.android.com/tools/logcat

**Comment by hasanelfalakiy** [comment]
> https://developer.android.com/tools/logcat

my computer is too old and slow to run android studio

**Comment by z-huang** [comment]
Please update to 0.5.8.
Closing for inactive.

**Comment by hasanelfalakiy** [comment]
> Please update to 0.5.8.
> Closing for inactive.

I have updated to 0.5.8 but it still doesn't work

**Comment by z-huang** [comment]
I need logs.
