### ISSUE TITLE
Add lyrics source 

### ISSUE THREAD

**Issue by adilurrhmn** [z-huang/music#1314]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add this source 

https://lrclib.net/

### Why do you want this feature?

lrc collection is awesome 👍 

And facing one problem, If I close the app from the background still showing in notification bar . I mean is didn't kill the notification

**Comment by nvllz** [comment]
I support this idea! It's implemented in the Malopieds fork and works much better than KuGou. (https://github.com/Malopieds/InnerTune/commit/7ccbf3c89ff2c038bc04c0d09a26d6c517053aa8, https://github.com/Malopieds/InnerTune/commit/37bc55942e0d243240a8458718ff06c3f64ea3c2).

&nbsp;

> And facing one problem, If I close the app from the background still showing in notification bar . I mean is didn't kill the notification

I noticed the same thing, @adilurrhmn. You might want to write a separate issue ticket about it.

**Comment by z-huang** [comment]
Added in 8d5785b20c06dc64e6453b666dbdf9b37c5a54e7
Credit: @Malopieds
