### ISSUE TITLE
Error with the search bar in playlists 

### ISSUE THREAD

**Issue by WHONEYR** [z-huang/music#1316]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Go to one of your playlists, search for a song and press the result 

### Expected behavior

the music you searched for can be selected and played 

### Actual behavior

When you click on a searched song it plays the song in the order of your playlist instead of the one you wanted 

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/db54d533-f486-4277-affe-f964b2375e72

### Logs

I don't know how to answer that 

### InnerTune version

0.8.4Stable

### Android version

Android 14

**Comment by z-huang** [comment]
0.8.4... you're using @Arturo254 's fork. You should create an issue in his repo.
