### ISSUE TITLE
Display warning when adding a song you already added to a playlist

### ISSUE THREAD

**Issue by fukin-fuk** [z-huang/music#1317]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

When you try to add a song that is already on a playlist, display a warning pop-up informing you of such thing and presenting the option to "cancel" or to "add anyways", in a similar fashion to Spotify.

### Why do you want this feature?

I don't want to check every time if I already put a song on a playlist. This warning would be a huge help to manage big playlists, as they grow and you find new songs that fit into them or remember ones that you do not know if they are already there. I do not create playlists in the app because of this.

**Comment by AndreVero** [comment]
Hi @z-huang ,

I have created a pull request to address this issue. You can find it here: https://github.com/z-huang/InnerTune/pull/1322

**Comment by z-huang** [comment]
Added in 80e1ed7637f9fb18668bae65e849a7bf6f354551
