### ISSUE TITLE
View album and view artist not showing

### ISSUE THREAD

**Issue by Joel198500** [z-huang/music#1320]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

.

### Expected behavior

It should open and show me what is requested 

### Actual behavior

It does not open it stays lagy

### Screenshots/Screen recordings

![Screenshot_20240807_050517_InnerTune](https://github.com/user-attachments/assets/7def5c02-af16-41a8-8a2e-70cf4f575028)
![Screenshot_20240807_050512_InnerTune](https://github.com/user-attachments/assets/490c426b-11c5-46bc-bc21-fbaee21019ea)

### Logs

I dont know them

### InnerTune version

0.5.0

### Android version

Android 12

### Additional information

If its because a new version please send the apk for it and please tell me how can i transfer all my songs to the new Version or if i have to download them all again.
Thank you very much

**Comment by z-huang** [comment]
Download new version here: https://github.com/z-huang/InnerTune/releases/tag/v0.5.4
