### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Joel198500** [z-huang/music#1321]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Can you please how i can tranfer all my songs without needing to download all again 

### Why do you want this feature?

. 

### Additional information

.

**Comment by z-huang** [comment]
You can install the new version apk directly, and it will automatically migrate. However, make a backup first in case.
