### ISSUE TITLE
Option to hide unnecessary panels on the home page

### ISSUE THREAD

**Issue by 7heMech** [z-huang/music#1327]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I would like to have a setting which can stop fetching and hide the useless stuff below in the home page which aren't related to what you listen like:
- New Release Albums
- Mood and Genres

### Why do you want this feature?

I've been realizing the hits the world listens to are pretty much music which I don't like, and I don't want to fetch them, or see them.

### Additional information

![ResizedImage_2024-08-08_21-55-23_1350.png](https://github.com/user-attachments/assets/cad8bbab-b452-48eb-a286-8b0a3c829be8)

**Comment by Malopieds** [comment]
Hi, I don't think this feature is on this repo, are you sure it's not from mine?

**Comment by 7heMech** [comment]
> Hi, I don't think this feature is on this repo, are you sure it's not from mine?

Yeah, seems like I did get confused indeed, didn't know they were different in that aspect, but the official app has something similar:
- new release albums
- moods and genres 

Edited issue accordingly.

**Comment by 7heMech** [comment]
@Malopieds in your version maybe you should move them to the explore page.

**Comment by Malopieds** [comment]
New releases and moods and genre are already there in my fork

**Comment by 7heMech** [comment]
> New releases and moods and genre are already there in my fork

I mean the other "discovery" things you've added which I first  mentioned in the issue like summer hits.

**Comment by z-huang** [comment]
Home screen was revamped, so you won't see that two sections unless you scroll to the bottom.
