### ISSUE TITLE
Volume of Songs Noticeably Lower

### ISSUE THREAD

**Issue by Blastorix** [z-huang/music#1328]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Simply play any song in InnerTune
2. Cross-check volume of song with other streaming apps (in this case, YouTube Music)

### Expected behavior

The volume of the song should be the same level.

### Actual behavior

The volume of songs played on InnerTune are noticeably softer than in other apps (i.e., YouTube Music).

### Screenshots/Screen recordings

![Screenshot_2024-08-08-15-07-02-89_f4703f2d42345ac28c56f11a6100c500](https://github.com/user-attachments/assets/8b53af3a-ea72-4801-a4e8-ca12c99a4316)

### Logs

N/A (I don't know how to do that on my smartphone)

### InnerTune version

0.5.4

### Android version

Android 14

### Additional information

The volume of any audio is at 70% when checking the details of the songs played. There should be a way to increase it to 100%.

**Comment by ruskcoder** [comment]
I think your volume slider (when you open up the 3 dots menu) might be low, if not bugged. Maybe try clearing app data through settings?

**Comment by Blastorix** [comment]
Oh, I just saw that and the volume spiked significantly! Thank you so much; I'll close this thread.
