### ISSUE TITLE
songs are not playing

### ISSUE THREAD

**Issue by senolfndk** [z-huang/music#133]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

songs are not playing

### Expected behavior

songs are not playing

### Actual behavior

songs are not playing

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/52818836/178585362-a2d885ad-539c-4c0a-9603-18fea69b320f.mp4

🤔

### Logs

songs are not playing

### Music version

0.3.1

### Android version

android 11

**Comment by z-huang** [comment]
`feature/innertube` is still in development. You can't play songs yet.

**Comment by senolfndk** [comment]
ok
