### ISSUE TITLE
Playlist won't update

### ISSUE THREAD

**Issue by CodyLax** [z-huang/music#1330]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

When you pressed the refresh button, it doesn't update the playlist.
It only happens when you log in to the app.

### Expected behavior

Update the playlist by pressing the refresh button.

### Actual behavior

Refuses to update playlist.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/4a22b56f-5d11-4cb7-b353-e7bf8e12938f

### Logs

_No information_

### InnerTune version

0.5.4

### Android version

Android 10

**Comment by siggi1984** [comment]
Same problem
