### ISSUE TITLE
Radio queue empty

### ISSUE THREAD

**Issue by Richard38907** [z-huang/music#1333]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

https://github.com/Malopieds/InnerTune/issues/291

### Expected behavior

https://github.com/Malopieds/InnerTune/issues/291

### Actual behavior

https://github.com/Malopieds/InnerTune/issues/291

### Logs

[logcat.txt](https://github.com/user-attachments/files/16560497/logcat.txt)

### InnerTune version

All InnerTune versions and forks

### Android version

Tested on 9, 13 and 14

**Comment by Meow-141** [comment]
I've got the same issue. I had downloaded innertune a few days back and it worked fine but now I have this issue as well. Would love to see this fixed soon.

**Comment by Malopieds** [comment]
From what I've seen, it seems that the WatchEndpoint from the playQueue needs a playlistId. I don't know what's best between having another field in the database to have it later, or re-fetching either way (but that would be on the menu).
I'm waiting for any hint on what's best from z-huang!

**Comment by z-huang** [comment]
Changing the type of `PlaylistPanelRenderer.playlistId` from `String` to `String?` seems to solve the issue.

> From what I've seen, it seems that the WatchEndpoint from the playQueue needs a playlistId.

Can you elaborate more?

**Comment by Malopieds** [comment]
> Changing the type of PlaylistPanelRenderer.playlistId from String to String? seems to solve the issue.

Yeah it does. I wasn't able to find anywhere to start looking at, and innertube is still a shady part where I still don't understand everything x)

> Can you elaborate more?

I was looking for a way to add the playlistId somewhere and when I added it to the WatchEndpoint it was working, but you solution is by far better.

**Comment by z-huang** [comment]
Will make a hotfix release soon.
