### ISSUE TITLE
Force stops while searching lyrics

### ISSUE THREAD

**Issue by Ashokis20** [z-huang/music#1336]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Play the song
2. Click the lyrics option
3. Click ok
4. It exists the app

### Expected behavior

Should stay in the app and work properly

### Actual behavior

It exits the app completely.. 

### Screenshots/Screen recordings

![Screenshot_2024-08-09-22-59-58-09_f4703f2d42345ac28c56f11a6100c500](https://github.com/user-attachments/assets/4ed8e4fe-1fed-4375-85eb-0629913f45fc)

### Logs

![Screenshot_2024-08-09-22-59-58-09_f4703f2d42345ac28c56f11a6100c500](https://github.com/user-attachments/assets/2803a26c-e315-41c5-a900-51c4c2accb7b)

### InnerTune version

0.5.5

### Android version

Android 13

### Additional information

After a second of showing list of lyrics.. it force stop (closes).. i mean it exits the app

**Comment by Richard38907** [comment]
Same crash here on v 0.5.5 too

**Comment by nero-0** [comment]
Crashing for me too, latest version.

**Comment by firezt** [comment]
Can confirm the crashes after updating to the latest release (0.5.5)

**Comment by kottaro123456** [comment]
v0.5.5_full_arm64-v8a
Me too.
Apparently the app crashes when you turn on the lyrics from KUGOU.
It doesn't seem to matter whether the getting lyrics from LRCLIB is on or off.

**Comment by z-huang** [comment]
Seems that the bug only occurs in release version. Debug version is not affected.
