### ISSUE TITLE
Can we please make it for windows too?

### ISSUE THREAD

**Issue by Ashokis20** [z-huang/music#1337]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I want to use this software in windows too.. because most of the people working on pc..

### Why do you want this feature?

For so many peoples want and mine too

**Comment by nvllz** [comment]
As stated in https://github.com/z-huang/InnerTune/issues/1181, I think it will never happen.

**Comment by z-huang** [comment]
I won't do that because the loading is too heavy. Contribution is welcome.
