### ISSUE TITLE
Minor improvement when searching for lyrics manually

### ISSUE THREAD

**Issue by firezt** [z-huang/music#1339]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Display the total track time, album and artist name above or below the lyrics provider's name for a better selection of which lyrics are most suitable for the selected song, similar to how it's shown when searching directly on lrclib.net website.

### Why do you want this feature?

Because it's a bit complicated to find the best lyrics for the selected track the way it is now, only displaying the lyrics timings and the provider's name. I believe this improvement would make the process of finding the right lyrics much simpler, coherent and visually pleasing.

### Additional information

Example of a song search result on the lrclib.net website:
![sample](https://github.com/user-attachments/assets/a4c96191-776c-440e-85c7-c99bb3ed9a16)

Thanks for reading.

**Comment by z-huang** [comment]
Why I made "search lyrics" is that some lyrics have time shift, so I need to know the timestamp of each lyrics to get the right one. By viewing the very first lines of the lyrics, I can know which one is the right song, so I think there's no need to display song title and artist.

**Comment by firezt** [comment]
A song can have several versions and varying vocal timings throughout, which is why you might find different lyrics with different timestamps when you search. Therefore, starting at the "right" time does not necessarily keep you in sync until the end of the song, so displaying the total track time makes it easier. The rest of the suggested metadata is basically for the same reason (e.g., same song, different artists in it), in addition to improving aesthetics.

**Comment by z-huang** [comment]
> Therefore, starting at the "right" time does not necessarily keep you in sync until the end of the song, so displaying the total track time makes it easier.

Most lyrics error is due to starting time mismatch.

Since InnerTune searches lyrics by the song name and artist, there's more probability of getting different songs with the same name than getting different song name. And it's easier to recognize songs by their lyrics, which is more precise. You cannot differentiate lyrics of different languages if you just look at lyrics metadata, right?

I won't do this in the near future, but there's still possibility that I suddenly want to change the lyrics search UI :)
