### ISSUE TITLE
Minimized player disappears after changing theme while playing a song.

### ISSUE THREAD

**Issue by lokicalmito** [z-huang/music#135]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Play any song (this also happens when nothing is playing, but the real inconvenience is when a song is playing);
2. Go to the settings;
3. Change the theme to any theme;
4. The minimized player is now gone.

### Expected behavior

The minimized player should remain visible and accesible after changing the theme. 

### Actual behavior

It disappeard and I can't access it until I play another song manually.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/107685698/179225498-3e4ad376-83f0-4e8f-86d8-2ef28b5abcea.mp4

### Music version

0.3.1

### Android version

Android 10

**Comment by z-huang** [comment]
It's not happening in my phone. 🤔

**Comment by lokicalmito** [comment]
I made sure I reinstalled the latest version and it's still happening. I honestly don't know, I wonder how many people can replicate this bug tho.

**Comment by owencz1998** [comment]
Iv just checked and it does the same with me play a song then change the theme then the mini player disappears but the song is still playing but really it's not a issue for me as I won't be changing the theme constantly  :)

**Comment by lokicalmito** [comment]
> Iv just checked and it does the same with me play a song then change the theme then the mini player disappears but the song is still playing but really it's not a issue for me as I won't be changing the theme constantly :)

I agree, it's not a big issue, but it's an minor inconvenience when it happens. I just think that this not the expected behavior.

**Comment by owencz1998** [comment]
Very true he's working on big features atm and hopefully the download issue will be fixed soon as that's driving me crazy haha 😁

**Comment by z-huang** [comment]
I used the emulator and this bug didn't happen.

**Comment by owencz1998** [comment]
Mine is not doing it anymore dude think somehow you magical fixed to some how 😂😂
