### ISSUE TITLE
Proper support for Android's internal backup APIs

### ISSUE THREAD

**Issue by lucasmz-dev** [z-huang/music#1353]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

At the moment, InnerTune sends data from downloaded songs/cache into Android backups. e.g. made by [Seedvault.](https://github.com/seedvault-app/seedvault)

### Why do you want this feature?

It is nice to have InnerTune be properly backed up by Seedvault (or with Google's backup tool) 

### Additional information

Same as https://github.com/Malopieds/InnerTune/issues/226

**Comment by z-huang** [comment]
Can you check if the fix is correct?

**Comment by lucasmz-dev** [comment]
I tried with the debug APK generated by GitHub and the backup still seems to be bigger than expected. App data says 21MB and on Seedvault also says 21MB. I'll do further testing later today, but I would expect similar size to the file backups

**Comment by lucasmz-dev** [comment]
Already commented on the other issue, but the limit for G Backups are apparently 25MB, more than that and they just get ignored. So I would've hit the limit there.

Seedvault's 50MB, or unlimited if you toggle that in the settings though I usually don't because it can get quite big with InnerTune *and* other apps.

**Comment by z-huang** [comment]
How to see the backup size for an app?

**Comment by lucasmz-dev** [comment]
@z-huang Unfortunately I only know with Seedvault but IIRC there is *some* way to check with Google's, but I might be wrong. On Seedvault, after doing a backup, click on the status of the backup and that will show you the apps and how much data they're taking up.

**Comment by z-huang** [comment]
I don't have Seedvault and Google doesn't tell me the backup size.

> I'll do further testing later today, but I would expect similar size to the file backups

How about downloading many songs and check if the size grows?

**Comment by lucasmz-dev** [comment]
Yep.  After downloading songs it reaches the limit and Seedvault warns that it went over the limit and such doesn't backup.

**Comment by z-huang** [comment]
Please check again, thanks!

**Comment by lucasmz-dev** [comment]
Unfortunately it seems the issue's still there :(
Also tried the new release 0.5.6, and that has the same issue :/

Thank you for your work trying to fix this though :/

**Comment by lucasmz-dev** [comment]
Let me check something real quick. I have device-to-device backup enabled, it pretends I'm transferring between devices because more apps allow backups this way.

**Comment by lucasmz-dev** [comment]
Ah it was that. :woman_facepalming: 

Backup is just 500kB now.

You probably *could* change this behavior but this is mostly fine AFAIK.

Edit: I *personally* would prefer it has these rules on with D2D mode, considering InnerTune can also get quite big and having the transfer between devices get slower would also kind of suck.
