### ISSUE TITLE
Pure black mode will make the miniplayer quickly change from black to bottom bar color.

### ISSUE THREAD

**Issue by frutejuise** [z-huang/music#1359]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [x] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Have pure black mode on
Click on any song when none are in the background
The miniplayer stays black for a split second.
Or dismiss full sized player
Mini player will be black for a split second.
Or leave settings
Again the miniplayer flashes black.

### Expected behavior

The miniplayer should be the color the full sized player was, or should seamlessly change to a new color.

### Actual behavior

The miniplayer is black for less than a second before changing to the same color as the bottom bar.

### Screenshots/Screen recordings

![Screenshot_20240812-125346](https://github.com/user-attachments/assets/438f938e-c966-4957-a6df-2abb61b75c04)

### Logs

![Screenshot_20240812-125346](https://github.com/user-attachments/assets/b804c876-6123-4b3e-a931-7bf87b11e18d)
![Screenshot_20240812-125336~2](https://github.com/user-attachments/assets/8d689064-2705-4af2-9e24-ed67486a4c4f)
![Screenshot_20240812-125331~2](https://github.com/user-attachments/assets/6d7998d8-797f-497c-9382-c6ce5adf7ef3)
![Screenshot_20240812-124626~2](https://github.com/user-attachments/assets/ccaf8731-8aed-4fd0-8d05-0f6f13ca9d7f)

### InnerTune version

0.5.6

### Android version

Android 14

**Comment by nvllz** [comment]
Yeah this thing is buggy as hell, no idea why the repo owner wanted it to be colored in black theme :/

**Comment by z-huang** [comment]
Can you try out this: 6ea31359dc2f99cc5607a9b0221c57a1cf291971? Is this better?

**Comment by frutejuise** [comment]
How can I apply the change?

**Comment by z-huang** [comment]
Download apk here: https://github.com/z-huang/InnerTune/actions/runs/10397178703

**Comment by frutejuise** [comment]
It's exactly the same, but super laggy
https://github.com/user-attachments/assets/d72818e5-8fd5-4a05-a7a6-19cca769fa51

**Comment by z-huang** [comment]
But when you play a song with the queue is empty, the mini player doesn't when color. Only when you drag it up will it change to black.

**Comment by frutejuise** [comment]
Ya, I think, I found this which may explain something, but I have no coding knowledge;
https://github.com/user-attachments/assets/fc348e20-ac77-40d3-85cb-be899ec831ec

When it's above the bar, it's black, but when it's stuck to the bar, it's the same color. During the animation when the mini player drops, it instantly changes color when it's stationary

**Comment by ganairm** [comment]
same thing happens to me... annoying as hell... hope this is fixed in the upcoming build

**Comment by z-huang** [comment]
> Ya, I think, I found this which may explain something, but I have no coding knowledge;
> https://github.com/user-attachments/assets/fc348e20-ac77-40d3-85cb-be899ec831ec
> 
> When it's above the bar, it's black, but when it's stuck to the bar, it's the same color. During the animation when the mini player drops, it instantly changes color when it's stationary 

Is this okay? Because people want pure black when the player is expanded.

**Comment by frutejuise** [comment]
My only idea for a fix is to make some kind of gradient or transition, I see that the text is different on the mini player and full size player so maybe you could change the transparency of the full sized player to make the appropriate color mini player get darker the higher it is on the screen, but by the time it's stationary, it would be the bottom bar's color... Maybe?

**Comment by frutejuise** [comment]
And I've just had pure black mode off and I've been fine with it, but making a change like I said would make the app a lot more fluid and seem less. Nothing urgent tho, just for cosmetics.

**Comment by frutejuise** [comment]
It looks great! Thank you so much
