### ISSUE TITLE
Idk there is nothing shown in songs/video/album

### ISSUE THREAD

**Issue by HikaruIchijyo** [z-huang/music#136]
While in playlist & channels it does show results screenshots attached i am on v0.3.1
![Screenshot_2022-07-17-18-28-33-656_com.zionhuang.music.jpg](https://user-images.githubusercontent.com/38470944/179400748-f0c345b9-dc88-4146-a7d9-4b83a10c61b9.jpg)
![Screenshot_2022-07-17-18-28-29-118_com.zionhuang.music.jpg](https://user-images.githubusercontent.com/38470944/179400758-09a7173f-b4d2-4c68-ab93-976e724b0baf.jpg)
![Screenshot_2022-07-17-18-28-26-187_com.zionhuang.music.jpg](https://user-images.githubusercontent.com/38470944/179400764-07092cbb-da91-4469-a65c-5db3aa0cec59.jpg)

**Comment by z-huang** [comment]
Does this bug still occur after restart, reconnecting internet, etc?

**Comment by HikaruIchijyo** [comment]
> Does this bug still occur after restart, reconnecting internet, etc?

Yep
I tried multiple times

Playlist & channel is working fine

**Comment by HikaruIchijyo** [comment]
> Does this bug still occur after restart, reconnecting internet, etc?

Also i have question it doesnt handle local music right?

**Comment by z-huang** [comment]
> Also i have question __it__ doesnt handle local music right?

Sorry, I don't understand the question. What's __*it*__?

**Comment by HikaruIchijyo** [comment]
> > Also i have question __it__ doesnt handle local music right?
> 
> Sorry, I don't understand the question. What's __*it*__?

I mean to say local music files stored in device?

Cuz currently i have like 50+ music files in some folders but nothing is found in the app.

Also in app permissions it doesnt show storage permission etc.

I am using miui13 btw

**Comment by z-huang** [comment]
Oh yes. This app doesn't handle local music. But you can take a look at #3. We *may* have this feature.

**Comment by HikaruIchijyo** [comment]
> Oh yes. This app doesn't handle local music. But you can take a look at #3. We *may* have this feature.

Got it thanks alot

If u need any information or any testing for this bug lemme know

**Comment by z-huang** [comment]
Is this due to region restriction by YT Music?

**Comment by HikaruIchijyo** [comment]
> Is this due to region restriction by YT Music?

Nah

Then y is playlist & channel working?

Also there shouldnt be any region restriction  i tried opening ncs too playlist & channel working ok while other 3's no

**Comment by owencz1998** [comment]
Could u do a screen record of the behaviour of the app also what device are you using mate

**Comment by owencz1998** [comment]
Have u tired this as well 

https://github.com/z-huang/music/suites/7487565308/artifacts/307324637

**Comment by HikaruIchijyo** [comment]
> Could u do a screen record of the behaviour of the app also what device are you using mate 

Ok
I am on redmi note 10s miui 13

**Comment by HikaruIchijyo** [comment]
> Have u tired this as well 
> 
> https://github.com/z-huang/music/suites/7487565308/artifacts/307324637

Nope lemme try

**Comment by owencz1998** [comment]
No problem mate

**Comment by HikaruIchijyo** [comment]
> Could u do a screen record of the behaviour of the app also what device are you using mate 

Here is the recording
https://user-images.githubusercontent.com/38470944/180619278-68c42a9a-a697-4d16-becd-92aa8c253ecd.mp4

**Comment by owencz1998** [comment]
OK and did u try the version iv sent dude

**Comment by HikaruIchijyo** [comment]
> Have u tired this as well 
> 
> https://github.com/z-huang/music/suites/7487565308/artifacts/307324637

Here is the screen record for this version

https://telegra.ph/file/1368c923c1adac7a32b5e.mp4

**Comment by HikaruIchijyo** [comment]
> OK and did u try the version iv sent dude 

Yep recording sent below

**Comment by owencz1998** [comment]
Are you able to connect to a WiFi dude or have u tried a vpn very strange mate haha

**Comment by HikaruIchijyo** [comment]
> Are you able to connect to a WiFi dude or have u tried a vpn very strange mate haha 

I am using data and about wifi yeah i tried it on that too it's same

About vpn i will chk later

**Comment by owencz1998** [comment]
Looks like a restriction to me not 100% haha but if u delete the version iv sent u and add this version in the settings there's a proxy setting if u can find one and test different proxy servers you never know haha

https://github.com/z-huang/music/files/9168257/app-debug.zip

**Comment by HikaruIchijyo** [comment]
> Is this due to region restriction by YT Music?

I am not sure i tested it with vpn now everything is working
While if i turn vpn off only playlist & channel working i guess this is yt music restriction

**Comment by HikaruIchijyo** [comment]
> Looks like a restriction to me not 100% haha but if u delete the version iv sent u and add this version in the settings there's a proxy setting if u can find one and test different proxy servers you never know haha
> 
> https://github.com/z-huang/music/files/9168257/app-debug.zip

I tedted with vpn it works while without vpn only playlist & channels work

**Comment by owencz1998** [comment]
Yeah definitely a restriction look at that version iv sent if u look online for a free proxy server add it In the settings and hopefully that will fix your issue and won't require an vpn bro

**Comment by HikaruIchijyo** [comment]
> Yeah definitely a restriction look at that version iv sent if u look online for a free proxy server add it In the settings and hopefully that will fix your issue and won't require an vpn bro
> 
> 

Thanks

**Comment by owencz1998** [comment]
No problem happy to help not the developer of this app of course but I like to try and help as much as I can 😁

**Comment by z-huang** [comment]
Thanks @owencz1998 for helping!
Close the issue and refer to #130.

**Comment by owencz1998** [comment]
No worries dude happy to help anytime :)
