### ISSUE TITLE
In version 0.5.6 searchbar, header and bottom toolbar background are too bright grey in black theme

### ISSUE THREAD

**Issue by Username1-a** [z-huang/music#1361]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Looks like there's some visual inconsistency in latest version - searchbar, header and bottom toolbar background color are too bright grey compared to the rest of the app in black theme (In previous versions it looked fine (maybe would be neat to have it even darker than that))

### Expected behavior

Those UI components should be darker in black theme for more visual consistency

### Actual behavior

ㅤ

### Screenshots/Screen recordings

![Screenshot_20240812-201735_InnerTune~2](https://github.com/user-attachments/assets/271fd421-9697-4d37-be43-df6c4118d551)
![Screenshot_20240812-201630_InnerTune~2](https://github.com/user-attachments/assets/712331f7-9b60-4136-b7c0-85b182845573)

### Logs

ㅤ

### InnerTune version

0.5.6

### Android version

Android 13 QPR 3

### Additional information

It's probably due to updated Material Components, google changed some stuff a year ago, so it's probably needs some tweaking. 

As another example of the negative side of those changes, since Android 12 debut to mid-late-2023 all Material You/Monet supported apps had fully dynamic Monet background that follows the system Monet background set by the apps like Repainter or Colorblendr or by Custom ROMs Monet settings (so you could easily had Black Amoled theme in ALL Monet supported apps, even if developer didn't gave such an option in the app itself), after updated m3 components apps no longer follow system Monet background brightness set by Custom ROM or Repainter, so it's usually stays grey in dark mode, unless there is a separate option for black theme in the app
 
InnerTune thankfully has a separate Black theme toggle, but since some changes have been made looks like some UI components are still a bit off in the latest version

**Comment by Richard38907** [comment]
I was wondering the same thing. I prefer the older one. Please fix these "light grey" UI elements.

**Comment by Richard38907** [comment]
Related to #1376

**Comment by z-huang** [comment]
Move to #1376
