### ISSUE TITLE
search some words will cause crash

### ISSUE THREAD

**Issue by internet-coffee** [z-huang/music#1365]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

search 「鹿乃子乃子」

### Expected behavior

search successfully 

### Actual behavior

application cruch

### Screenshots/Screen recordings

Uploading Screen_Recording_20240813_101124_InnerTune.mp4…

### Logs

I don't know what it is

### InnerTune version

0.5.6

### Android version

Android 13(One UI 5.1)

**Comment by kottaro123456** [comment]
me too
App crash when search 「タ」（japanese katakana）.
I think this problem is caused by some Japanese letter.

**Comment by z-huang** [comment]
Fixed. Wait for a new release or use debug build.
