### ISSUE TITLE
Request the waved seek bar.

### ISSUE THREAD

**Issue by BandanSaowarot** [z-huang/music#1366]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Waved Seek bar in the now playing screen.

Add an options to select it in the Settings -> Player

### Why do you want this feature?

Giving the better experience to the user with a nicer look and feel.

**Comment by z-huang** [comment]
This project follows Material 3 guideline. https://m3.material.io/components/sliders/overview
