### ISSUE TITLE
Seek bar movement's enhancement

### ISSUE THREAD

**Issue by BandanSaowarot** [z-huang/music#1367]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Enhance the movement for the seek bar and it's knob, making it's move more smooth than before.

This will affect to the mini-player's progress bar's movement too.

### Why do you want this feature?

This will give the better experience to the user.

**Comment by z-huang** [comment]
Lack of specific description.

**Comment by BandanSaowarot** [comment]
For a specific description

I looked the seek bar's knob and the progress bar in the mini player.

Current, the knob is move one step on every 0.5 seconds. If you reduce the time per step, it will moved with more step per second, it'll more smoothly.
