### ISSUE TITLE
Repetitions in history section 

### ISSUE THREAD

**Issue by adithya-katuku** [z-huang/music#1369]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Open InnerTune app
2. Click on the history icon

### Expected behavior

The section shows the list of previously played songs. It is expected that if we previously listened a song in loop, the history section will list the song once.

### Actual behavior

But the song appears in the list as many times as it was run in the loop previously. 

### Screenshots/Screen recordings

![IMG_20240813_163057](https://github.com/user-attachments/assets/6a5e8766-de41-41cd-9cb0-0bf7ab2bc500)

### Logs

NA

### InnerTune version

0.5.6

### Android version

Android 12

**Comment by z-huang** [comment]
Thanks for reporting.

**Comment by adithya-katuku** [comment]
I don't think it is solved yet. Can you please check again? 

![Screenshot_2024-08-22-17-37-08-63_f4703f2d42345ac28c56f11a6100c500.jpg](https://github.com/user-attachments/assets/d7e70bf4-c0f0-4f33-ac94-0f6d9b48e2b3)

**Comment by adithya-katuku** [comment]
Is it possible to have the history such that it merges the current song's played 'history' into the new history entry if the old 'history' is within a threshold range or else make a new entry?

Let's say the played order was
--Latest first--

(A) -> [B C {A} F G B C A]

[...] - existing history
(A) - new entry into the 
{A} - entry within the threshold

The new history section should be
A B C F G B C A

I considered 4 as a threshold starting from the first index of the history just for demonstration.

I just had a thought, and I hope it doesn't come across the wrong way.

**Comment by z-huang** [comment]
> I don't think it is solved yet. Can you please check again?

Are you using debug build?
My fix is to merge "A, A, B, B" to "A, B".

**Comment by z-huang** [comment]
> Is it possible to have the history such that it merges the current song's played 'history' into the new history entry if the old 'history' is within a threshold range or else make a new entry?
> 
> Let's say the played order was --Latest first--
> 
> (A) -> [B C {A} F G B C A]
> 
> [...] - existing history (A) - new entry into the {A} - entry within the threshold
> 
> The new history section should be A B C F G B C A
> 
> I considered 4 as a threshold starting from the first index of the history just for demonstration.
> 
> I just had a thought, and I hope it doesn't come across the wrong way.

YouTube's logic: (latest first)

Full history:

- Today: A, B, C, A, B
- Last week: A, B, C, A, B

History you see:

- Today: A, B, C
- Last week: A, B, C

A song appears once in a category. Do you think this is better?

**Comment by adithya-katuku** [comment]
> 
> Are you using debug build?
>
Sorry, I was using it then. 
But I turned it off and the app is still behaving the same.

**Comment by adithya-katuku** [comment]
> YouTube's logic: (latest first)
> 
> Full history:
> 
> - Today: A, B, C, A, B
> - Last week: A, B, C, A, B
> 
> History you see:
> 
> - Today: A, B, C
> - Last week: A, B, C
> 
> A song appears once in a category. Do you think this is better?

>
Yeah I feel this is better.

**Comment by z-huang** [comment]
Done.
