### ISSUE TITLE
Be able to choose where to save downloaded music

### ISSUE THREAD

**Issue by KakarottoCake** [z-huang/music#137]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Instead of downloading the music to an arbitrary folder inaccessible to the user, be able to send the files to a specified folder (by the user), and allow it to be configurable by the user.

### Why do you want this feature?

I would like this feature because of an ease of managing my music for when I go on business trips.

**Comment by z-huang** [comment]
I'll do #117. If this solves your needs, you can close this issue.

**Comment by z-huang** [comment]
Close for being idle.

**Comment by z-huang** [comment]
SAF is used to export files, so you need to copy them out to let other apps find them.
