### ISSUE TITLE
Serious bug

### ISSUE THREAD

**Issue by Roxo7777** [z-huang/music#1371]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

https://drive.google.com/file/d/1JiEJLJhjGYM-Yff1ScfaOXZ8O4Yv-ln_/view?usp=drivesdk

This video shows the bug, which occurs when I click directly on the album (photo of the song) or name, where when clicking it leaves the application, when clicking on the extreme part of the right side, I can access the song/album

### Expected behavior

You should not leave the app unexpectedly, and play the music

### Actual behavior

Exited the app unexpectedly

### Screenshots/Screen recordings

I sent it once

### Logs

I couldn't get the debug unfortunately

### InnerTune version

0.5.6

### Android version

14

**Comment by z-huang** [comment]
Try the latest debug build.

**Comment by Roxo7777** [comment]
> Try the latest debug build.

I can't debug

**Comment by z-huang** [comment]
Move to #1381.
