### ISSUE TITLE
Suggested related songs are NO longer being added to current playlist

### ISSUE THREAD

**Issue by ecv80** [z-huang/music#1373]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Tap on a song

### Expected behavior

The song plays
After the song plays another random related song plays 

### Actual behavior

The song play
It stops playing or loops the same song

### Logs

-

### InnerTune version

0.5.4 from F Droid 

### Android version

Android 11

### Additional information

It used to always play other song automatically. Even tapping on radio doesn't do anything.

**Comment by Bruhhhhh555** [comment]
This. I cannot start a radio either, quick picks are basically useless. Because only one song will be on the queue. This is present in old and latest version. I am on Android 14.

**Comment by z-huang** [comment]
Use 0.5.6

**Comment by ecv80** [comment]
Thank you.

Sorry I thought you're the maintainer at F-Droid. It was updated 4 days ago to 0.5.4. F-Droid is the FOSS apk platform for Android. Imagine all the people who got this bad update!  And I can't figure out how to contact InnerTune maintainer at F-Droid to correct it!

**Comment by z-huang** [comment]
F-Droid needs a few days to update, so I recommend you to download in GitHub. I'm considering adding update checker, so you won't miss an update.
