### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by Guts951** [z-huang/music#1374]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

It would be great if there were more options to customize the player like changing the style of the play bar and choosing square album covers with no rounded edges.

### Why do you want this feature?

There are very few customization options in Innertune. It would complete an already almost perfect app.

**Comment by z-huang** [comment]
What is "changing the style of the play bar"?

**Comment by Username1-a** [comment]
Would be neat if there was an option to have minimalistic, thin line seekbar from the previous versions
![Screenshot_20240815-081206_Evolution X Launcher](https://github.com/user-attachments/assets/ec014d57-8717-4130-940f-f7b1b597455a)
Or something like this
![Screenshot_20240815-085248_Auxio](https://github.com/user-attachments/assets/bdfd348c-75ff-48f6-a2d6-8a52b936cbed)

**Comment by z-huang** [comment]
This project follows Material 3 guidelines, so the seek bar won't change.

**Comment by ruskcoder** [comment]
I think the new seek bar looks kind of bad 🤷. Could I be able to change from the new material 3 slider to the old one?
