### ISSUE TITLE
Make #1353 also apply to D2D backups

### ISSUE THREAD

**Issue by lucasmz-dev** [z-huang/music#1375]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Make Android backups that are device-to-device transfers also not include downloads, cache, etc such as what was done with #1353

### Why do you want this feature?

1. I believe this makes sense overall. Downloads can take gigs of storage, this would make a device-to-device transfer extra slow.
2. Seedvault has a D2D mode to backup more apps which I personally and many others naturally use since Seedvault backups are E2EE, this means that InnerTune either takes a bunch of storage, or isn't backed up.

### Additional information

![image](https://github.com/user-attachments/assets/f7920a94-da4b-4c99-b6cd-6bff83440b38)
![image](https://github.com/user-attachments/assets/bd913198-c146-4f63-aba5-b4664638a598)
![image](https://github.com/user-attachments/assets/0b2d353e-5709-4935-9f88-22af56f79548)

https://developer.android.com/identity/data/autobackup#xml-syntax-android-12

Most of the other apps seem to have similar rules in both for this.

Made this issue because it is an extension of #1353

**Comment by z-huang** [comment]
Okay. I'll add this.

**Comment by z-huang** [comment]
Give it a try.
Also, can you test for me if there's any playback issue when restoring the backup using D2D? Especially songs that are downloaded in the original phone but not in this phone.

**Comment by lucasmz-dev** [comment]
I'll try.

**Comment by lucasmz-dev** [comment]
> I'll try.

This was actually incredibly easy with Seedvault lol

Yeah, so the only issue is that the app still believes the songs to be downloaded when they're not, this doesn't cause any issues if you're online but the songs are not actually downloaded hence they can't be played offline. To fix this I just had to 'undownload' and then redownload the playlist.

Let me know if you need any help testing Android backups because I just got the cutest test envo lol

**Comment by z-huang** [comment]
Please try this one: 7b893df0701462bf919134022decf356ff5a3e83

I excluded exoplayer's database, so I think download information won't be transferred.

**Comment by lucasmz-dev** [comment]
Yep! Works as intended! Amazing!

Thank you for this / these fixes, I love your work with InnerTune!
