### ISSUE TITLE
Material 3 colors issues 

### ISSUE THREAD

**Issue by mostafaalagamy** [z-huang/music#1376]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Is this normal? The color of the search bar and the navigation bar has become a different colors from the app's background, and this is strange.

New colors

![Screenshot_2024-08-14-07-32-27-780_com zionhuang music-edit](https://github.com/user-attachments/assets/d0361db1-392a-47c7-8d69-d3b8a33836af)

It would be better if it was the same color like this. 

![Screenshot_2024-08-13-21-31-09-490_com dd3boh outertune](https://github.com/user-attachments/assets/6bbe4fa4-9bfd-403d-9793-c146133623a4)

### Expected behavior

__

### Actual behavior

__

### Logs

__

### InnerTune version

debug version

### Android version

13

**Comment by Richard38907** [comment]
Same here, this is weird

**Comment by z-huang** [comment]
It's correct according to material 3 guidelines, which has updated since Dec, 2023. It says search bar container color is `md.sys.color.surface-container-high` and navigation bar container color is `md.sys.color.surface-container`.

**Comment by Richard38907** [comment]
We think the old one was better. These "light grey" UI elements look bad.
Same report for Malopieds version here:
https://github.com/Malopieds/InnerTune/issues/311

**Comment by mostafaalagamy** [comment]
> It's correct according to material 3 guidelines, which has updated since Dec, 2023. It says search bar container color is `md.sys.color.surface-container-high` and navigation bar container color is `md.sys.color.surface-container`.

If all the colors in the app need to be changed to match each other, what should be done?

**Comment by ghost** [comment]
In my opinion, the ideal color is the one we had before the change. The whole app looks wrong to me now.

> It's correct according to material 3 guidelines, which has updated since Dec, 2023. It says search bar container color is `md.sys.color.surface-container-high` and navigation bar container color is `md.sys.color.surface-container`.

Following Google's rules so far has been great, but this change lowers the UI's cohesiveness, so I think you should consider making your own decision here as arguably your design looks more like Material 3 than Google's.

**Comment by mostafaalagamy** [comment]
> In my opinion, the ideal color is the one we had before the change. The whole app looks wrong to me now.
> 
> > It's correct according to material 3 guidelines, which has updated since Dec, 2023. It says search bar container color is `md.sys.color.surface-container-high` and navigation bar container color is `md.sys.color.surface-container`.
> 
> Following Google's rules so far has been great, but this change lowers the UI's cohesiveness, so I think you should consider making your own decision here as arguably your design looks more like Material 3 than Google's.

It's normal to follow the rules, but in the case of innertune, some colors were changed while others were not. If we follow Google's rules for the navigation bar and search bar, we should also follow them for the background and other colors to ensure everything is seamless and not weird.

For example, to clarify!

![Screenshot_2024-08-19-09-10-22-295_com.android.chrome-edit.jpg](https://github.com/user-attachments/assets/ff1434be-0618-44cb-8c09-f77d1898b96c)

![Screenshot_2024-08-19-09-01-03-357_com.android.chrome-edit.jpg](https://github.com/user-attachments/assets/7dca64e5-fd30-427b-af30-a361620a77ee)

**Comment by z-huang** [comment]
Good point! Added.

**Comment by mostafaalagamy** [comment]
> Good point! Added.

The colors are still different, something is missing.

![Screenshot_2024-08-19-16-41-48-514_com.zionhuang.music.debug.jpg](https://github.com/user-attachments/assets/3fb68e01-3b1d-437a-a59b-c0a6cc2b39dc)

**Comment by z-huang** [comment]
Where do you mean? I have changed background color to `Surface`.

**Comment by mostafaalagamy** [comment]
> Where do you mean? I have changed background color to `Surface`.

I know it has been changed, but the colors are still not harmonious and haven't changed properly. Look at Google Play or Google Phone, you'll see that the background color matches the navigation bar and the search bar but in different shades. However, in **our** case, you'll find that they are completely different from the background color even after the change. That's why I'm telling you that something is missing and hasn't been adjusted.


![Screenshot_2024-08-19-20-11-45-630_com.android.vending.jpg](https://github.com/user-attachments/assets/a466df7c-1bde-4c27-b693-0b71da7567d1)


![Screenshot_2024-08-19-20-13-50-674_com.zionhuang.music.debug-edit.jpg](https://github.com/user-attachments/assets/bc0b1f6a-b151-4071-8427-8afa9a3cf3e1)
 
color differences : 

1- search bar 
2- background 
3- circle box
4- Buttons
5- navigation bar

**Comment by z-huang** [comment]
@mostafaalagamy check out this one: 57428ce9af07474591aebb7dc91b2cc7c20643b5

**Comment by mostafaalagamy** [comment]
> @mostafaalagamy check out this one: 57428ce9af07474591aebb7dc91b2cc7c20643b5

I think it's better now than it was before. thanks!

**Comment by ghost** [comment]
I think my concern is exclusive to "Pure black" mode. Could you check that? In that mode the theme it looks wrong to me.

**Comment by z-huang** [comment]
Can you provide screenshots?

**Comment by ghost** [comment]
In the current version it looks like this:
![nmbhxahmxa5whijo](https://github.com/user-attachments/assets/c59abbc0-d5b0-4060-9028-434fe00e9d28)

In the previous version, the "Pure black" theme appeared as true black, which is consistent with the behavior of other Material 3 apps I use. Therefore, I suspect there may be an issue with the implementation of the "Pure black" theme in this version.

Additionally, it might be beneficial to consider utilizing the "Pure black" system theme to automatically adjust the theme based on the user's system settings. However, this is not the primary concern at the moment.
