### ISSUE TITLE
shuffle is not so random 

### ISSUE THREAD

**Issue by Wabski** [z-huang/music#1379]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

the shuffle button is not really random, always playing recent songs or played songs

### Expected behavior

needed to be random

### Actual behavior

not so random

### Logs

.

### InnerTune version

0.5.6

### Android version

android 13

**Comment by z-huang** [comment]
Do you mean the one in queue screen? This is totally random. I didn't do any trick on it.

**Comment by looowizz** [comment]
I think this might be talking about shuffle playing artists which is where ive found this to happen. I usually just click shuffle play then shuffle again in the queue page as a workaround. Still not a perfect solution as i dont think all the artist's songs get added to the queue but works well enough for me. :)

**Comment by Wabski** [comment]
the shuffle on downloaded songs, for example when tapping shuffle, in the first 1-50 queued songs it always plays either recent songs I'd played/downloaded or mostly songs that i have plenty on playtime. Its like shuffling my top 50 and just added 5 random songs in queue, i have 500+ songs downloaded. tapping shuffle again really doesn't work.

**Comment by z-huang** [comment]
@Wabski can you provide a screen recording about that?

**Comment by z-huang** [comment]
Closing for inactive.
