### ISSUE TITLE
Theme changes to pure black on light mode when dynamic theme and pure black is on and a song with a dark cover is playing

### ISSUE THREAD

**Issue by Z-ANESaber** [z-huang/music#1383]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Enable dynamic theme, Pure black and turn off dark theme
2. Play a song that has a dark cover 

### Expected behavior

Dynamic theme should stay in light mode.

### Actual behavior

Screen turns to pure black while the text also remains black.
Only the bottom navigation bar stays white

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/2ab8937a-fca0-4e8f-8005-156c290f2c60

### Logs

Unable to

### InnerTune version

0.5.6

### Android version

Android 14

**Comment by Richard38907** [comment]
Same thing on Malopieds'fork
https://github.com/Malopieds/InnerTune/issues/305

**Comment by Username1-a** [comment]
To clarify, it's introduced in latest version 0.5.6 (previous version 0.5.5 doesn't have that bug)
and playing any song with the image cover that triggers/enables dynamic theme produces this black background bug (cover can be light, dark, whatever)
