### ISSUE TITLE
Crash on Restore import

### ISSUE THREAD

**Issue by ProphetVII** [z-huang/music#1388]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

- Settings 》Backup and Restore 》Restore 》 Select your `InnerTune_*.backu`

### Expected behavior

App imports playlists.

### Actual behavior

- Playlist get restored from previous version.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/8f2ad024-6801-4b72-85d9-6f0cd4993288

### Logs

`TODO`

### InnerTune version

0.5.6

### Android version

Android 14

### Additional information

[InnerTune_20240815113336.zip](https://github.com/user-attachments/files/16627491/InnerTune_20240815113336.zip)

**Comment by ruskcoder** [comment]
How about, redownload the previous version, restore there, and update the app with the new version so your stored data stays. Umm I think the new InnerTune uses more storage elements that the old InnerTune is not compatible with. (just my guess)

**Comment by z-huang** [comment]
Your backup was created in Malopieds' fork. Use this tool https://github.com/7heMech/InnerTune-Backup-Fix to convert to a type which InnerTune supports.

**Comment by ProphetVII** [comment]
> Your backup was created in Malopieds' fork. Use this tool https://github.com/7heMech/InnerTune-Backup-Fix to convert to a type which InnerTune supports.

This worked like a charm. The file downloads with a backup a "backup" in the name of the file, this needs to be removed before importing.
