### ISSUE TITLE
Login  Google account doesn't work

### ISSUE THREAD

**Issue by Nolli20** [z-huang/music#1391]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1 go to settings
2  go to Content
3 click on login 
4 login with ur Google account 
5 Instead of redirecting you to innnertune, it will take you to a YouTube page

### Expected behavior

It would be nice if it worked 

### Actual behavior

He doesn't work

### Logs

.

### InnerTune version

0.5.7

### Android version

Android 13

**Comment by ruskcoder** [comment]
It works, but sometimes is buggy. If it leads you to YouTube, click your profile picture, scroll down to YouTube music, and click it. So basically find a way to reach YouTube music, and click back, and your login will work.

**Comment by itsmeteddyhere** [comment]
> It works, but sometimes is buggy. If it leads you to YouTube, click your profile picture, scroll down to YouTube music, and click it. So basically find a way to reach YouTube music, and click back, and your login will work.

this fixes the issue so perhaps there's just a redirection problem or something?

**Comment by z-huang** [comment]
Yes, you can say it that way. I will make the login flow more clear. Let's move to #1409.

**Comment by Luiz-Dinani** [comment]
I couldn't find the link to YouTube music scrolling down on my profile, so I searched for YouTube music channel and got the link to their website from one of the videos description, accessed it and the login worked
