### ISSUE TITLE
progress bar

### ISSUE THREAD

**Issue by senolfndk** [z-huang/music#1398]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

add wavy bar

### Why do you want this feature?

add wavy bar

### Additional information

![Screenshot_20240816-143520_InnerTune](https://github.com/user-attachments/assets/591638af-fd09-44dc-a800-6691ea9fe1f8)

**Comment by z-huang** [comment]
Is this a fork of InnerTune?

**Comment by senolfndk** [comment]
> Is this a fork of InnerTune?

Yes

**Comment by z-huang** [comment]
I'd like to know the link :)

**Comment by senolfndk** [comment]
> I'd like to know the link :)

https://github.com/Arturo254/InnerTune

**Comment by Roxo7777** [comment]
https://github.com/user-attachments/assets/f190316b-4680-4091-9152-2024674d9422

I prefer the notification progress bar, even.

**Comment by Roxo7777** [comment]
I much prefer this progress bar...
https://github.com/user-attachments/assets/65b057bf-37c9-460c-9263-8df7a7135d52

**Comment by Roxo7777** [comment]
I much prefer this progress bar...
https://github.com/user-attachments/assets/30d33b09-67e3-4a60-9059-b8d95f18ba75

**Comment by z-huang** [comment]
Duplicate of #1401
