### ISSUE TITLE
Support to audio scrobbler

### ISSUE THREAD

**Issue by airon90** [z-huang/music#14]
Good project! I'd like to have a native support to audio scrobblers, like ListenBrainz and Libre.fm

**Comment by z-huang** [comment]
I downloaded the Last.fm app. Most of the other music apps in my phone can be scrobbled, but my app can't. I've been trying to send broadcasts such as `com.android.music.*` to let other apps know what is playing, but in vain.
Are you using [SLS](https://github.com/simple-last-fm-scrobbler/sls) or any app to scrobble music?

**Comment by airon90** [comment]
No, I used SLS in the past, when I used Vanilla Music as music player. Then I started using NewPipe and SLS didn't recognize it as music player

**Comment by airon90** [comment]
I suggest you to implement it directly in your app as SLS is not maintained anymore.
Listenbrainz API: https://listenbrainz.readthedocs.io/en/latest/users/api/core/
Libre.fm API not available right now
Last.fm API: https://www.last.fm/api/scrobbling

**Comment by z-huang** [comment]
I found that [pScrobbler](https://github.com/kawaiiDango/pScrobbler) is an alternative of SLS. After 657722c3e2b109c2e6fe842a105cdb957740496e, this app can be recognized as a music app by pScrobbler. I prefer this feature to be provided by other apps since I want things to be as simple as possible.
