### ISSUE TITLE
Option to change between seek bars.

### ISSUE THREAD

**Issue by ruskcoder** [z-huang/music#1401]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

In my opinion, the new seek bar looks quite bad with the design style of the app. I would like to be able to change it to the old one, just the like and the dot, to make it look simple and neat. I think there also is another feature request for the squiggly seek bar, we could have an option to change between all 3. The new seek bar looks like a number slider to choose a range etc... not progress done. 

### Why do you want this feature?

I have gone to the point of using an older version because I personally don't like the complicated design of the new seek bar. 

### Additional information

Another good slider example is OuterTune's slider.

**Comment by Username1-a** [comment]
New seekbar is straight up hideous, I don't know wth google is doing with it's guidelines

**Comment by z-huang** [comment]
Done.

**Comment by ruskcoder** [comment]
> Done.

Can there be an option for the old default one? If that is too extra, it is fine,but having it would be quite nice.

**Comment by z-huang** [comment]
The old one is not possible because it's shipped with the _old_ material 3 library.

**Comment by ruskcoder** [comment]
Oh, that makes sense, thanks!
