### ISSUE TITLE
Selection of multiple songs in queue

### ISSUE THREAD

**Issue by ansarimohammed422** [z-huang/music#1402]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

1. I want queue endries selectable so that we can add multiple songs simultaneously to playlist

2. Add functionality like making whole queue into the playlist

3. And inside a queue when we longpress on a song that is not playing to go to its album or artist it is not possible so give 3 dot button insode queue songs for that

### Why do you want this feature?

Because it will make this app better

**Comment by z-huang** [comment]
Done.
