### ISSUE TITLE
Sync music data from innertune to your google account

### ISSUE THREAD

**Issue by radical4ever** [z-huang/music#1403]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Allow users to send their music listening history & other related stuff to their google account to sync their data

### Why do you want this feature?

personally for the youtube music recap, but it can be helpful to sync to other devices (like TV, PC, etc)

**Comment by ruskcoder** [comment]
Duplicate of #990

**Comment by radical4ever** [comment]
> Duplicate of #990

Ok,  I'm closing this
