### ISSUE TITLE
PC Support For InnerTune Users

### ISSUE THREAD

**Issue by kitodoescode** [z-huang/music#1410]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I want to request a PC version for Inner Tune as there is no other free pc streaming application with such good UI as of Inner Tune. I would highly appreciate a PC version of the app.

### Why do you want this feature?

Because some work is done on PC and people (including me) want to listen to songs while working and might not have smartphone lying around or just not want to listen using smartphone.

### Additional information

None

**Comment by kitodoescode** [comment]
Pls consider my request🥺🥺

**Comment by z-huang** [comment]
As long as synchronization with YTM is done, you can use YTM web on PC.
I don't have time to develop a new app on PC.
