### ISSUE TITLE
Add song in queue if start listening from library 

### ISSUE THREAD

**Issue by Megaantony00** [z-huang/music#1416]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Like spotify if you start to listening to songs from the library and the add another song in queue it won't go at the end of your queue ( so you have to skip all library songs if you want that one ) but right after the song that you are listening ( or other songs that you added in queue that aren't part of the library's one )

### Why do you want this feature?

If I start from to listen to songs from library it doesn't mean that I want to listen to all of them

**Comment by z-huang** [comment]
There's a "Play next" option!

**Comment by Megaantony00** [comment]
> There's a "Play next" option!

![Screenshot_20240820_111233_InnerTune](https://github.com/user-attachments/assets/ca8fc765-4cdf-4e3d-9ec1-1a0cc50ffdef)
Is this ? Because in this case in italian it means " play as "

**Comment by z-huang** [comment]
Yes, it is. This may be a translate error. If you can, please make a pull request to correct it, thanks!
