### ISSUE TITLE
Error in italian translation

### ISSUE THREAD

**Issue by Megaantony00** [z-huang/music#1418]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

![359435434-ca8fc765-4cdf-4e3d-9ec1-1a0cc50ffdef](https://github.com/user-attachments/assets/8582aa0c-f9ab-44db-a99b-8274d9adf975)
This button should be " Riproduci come successiva " or something like this ( I don't how to make a pull request btw )

### Why do you want this feature?

It's a translation error

**Comment by z-huang** [comment]
Oh, the translation is actually correct, but it's too long so that the third line is cropped.

**Comment by z-huang** [comment]
I'm planning to redesign the bottom menu sheet, so please live with it temporarily.
