### ISSUE TITLE
App auto-closes after a while of Inactivity

### ISSUE THREAD

**Issue by Blastorix** [z-huang/music#1419]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Open InnerTune
2. Play one song
3. Don't play any song for some time
4. Reopen app
5. App auto-closes

### Expected behavior

The app should just stay open and let me continue on as usual.

### Actual behavior

App auto closes, prompting me to open it again.

### Logs

N/A

### InnerTune version

0.5.7

### Android version

Android 14

**Comment by Blastorix** [comment]
I believe this has to do with the app being killed by the Android OS, so should I just allow the app to run in the background so it doesn't get killed?

**Comment by z-huang** [comment]
> I believe this has to do with the app being killed by the Android OS, so should I just allow the tap to run in the background so it doesn't get killed?

If this case, yes, you need to allow the app to stay in the background. There should be a settings somewhere in the OS.

**Comment by Blastorix** [comment]
Thanks, I'll give that a try. Hopefully it doesn't autoclose now...

**Comment by Blastorix** [comment]
Just tried to open the app again. It autoclosed.
