### ISSUE TITLE
Streaming music issue

### ISSUE THREAD

**Issue by owencz1998** [z-huang/music#142]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

A song 
Play the song or 2

### Expected behavior

Should play a the way through and the next song should start.

### Actual behavior

Play a song or 2
Cuts out sometimes in middle of song
Have to constantly tap the play button till it works 
Sometimes it won't allow the next track to start

### Logs

Will get a log as soon as I'm home

### Music version

0.4.0 innertube branch

### Android version

12

**Comment by Alliba** [comment]
What is version 4.0 innertube and where to get it?

**Comment by z-huang** [comment]
It's still in development. Debug apks are available in GitHub Actions.

@owencz1998 Is the bug not happening?

**Comment by owencz1998** [comment]
I'm going to wait to see once the app is not in debug stage as iv been told debug can cause issues on phones :) but I noticed that I get a error message saying something went wrong with music debug so I'm a little convinced it's the debug version 🙂

**Comment by z-huang** [comment]
That's OK.
