### ISSUE TITLE
Crashing when locking smartphone

### ISSUE THREAD

**Issue by Smuuuko** [z-huang/music#1421]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Same bug as here: https://github.com/Malopieds/InnerTune/issues/263 

I didn't see this bug in 0.5.3 version, only 0.5.4+ versions are affected
Bug appear only when there isn't any song open.

### Expected behavior

Nothing, especially not crashing :D

### Actual behavior

Crash as shown in video in link above

### Screenshots/Screen recordings

See link above

### Logs

See link above

### InnerTune version

0.5.4+

### Android version

tested on Android 11 and Android 14 

### Additional information

Hope you will smash that bug

**Comment by z-huang** [comment]
> Open innertune
Lock smartphone
Unlock smartphone

I tried this after clearing app data, but it didn't crash.

**Comment by unseenlarks** [comment]
can confirm. Android 13, InnerTune version 0.5.8.
would app logs help, and if so what's the best way to get them to you?
thank you.

**Comment by z-huang** [comment]
Can you try the latest debug build again? Thanks.

**Comment by unseenlarks** [comment]
tested latest debug build a few times, can't repro the crash anymore. thank you.
