### ISSUE TITLE
Notification pops up even clearing app from background.

### ISSUE THREAD

**Issue by Aaniket7** [z-huang/music#1424]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Go into the app..
Play any song...
pause the song...
Now when we clear the app from background running...it (Music player notification) should've closed as well ,but....
It just reappears/pops up...
That is kind off annoying bugg, plz fix this asap for smooth and uninterrupted experience...
Attaching a video...
Thanks in advance🙌

### Expected behavior

The app should be completely closed. 

### Actual behavior

It does not close from background...shows notification all of sudden.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/dbe56630-f1c4-45c6-bec1-3d8d59b7e584

### Logs

I cant fond it

### InnerTune version

0.5.8

### Android version

Android 14

**Comment by z-huang** [comment]
Can you try this patch (https://github.com/z-huang/InnerTune/actions/runs/10402583679?pr=1272)?

**Comment by Aaniket7** [comment]
Sorry i cant..

**Comment by Aaniket7** [comment]
> Can you try this patch (https://github.com/z-huang/InnerTune/actions/runs/10402583679?pr=1272)?

It's quite large file ...plz make it available for all

**Comment by Anonuser-code** [comment]
https://github.com/z-huang/InnerTune/discussions/1390#discussioncomment-10400184

Check this out mate

**Comment by z-huang** [comment]
> > Can you try this patch ([z-huang/InnerTune/actions/runs/10402583679?pr=1272](https://github.com/z-huang/InnerTune/actions/runs/10402583679?pr=1272))?
> 
> It's quite large file ...plz make it available for all

This is a debug build, so the file size is large. Can you test for a while? If it's okay, I'll merge this PR.

**Comment by Aaniket7** [comment]
> [#1390 (reply in thread)](https://github.com/z-huang/InnerTune/discussions/1390#discussioncomment-10400184)
> 
> Check this out mate

Didn't work!

**Comment by Anonuser-code** [comment]
> > [#1390 (reply in thread)](https://github.com/z-huang/InnerTune/discussions/1390#discussioncomment-10400184)
> > 
> > Check this out mate
> 
> Didn't work!

https://github.com/user-attachments/assets/604dcb6e-cd3e-4626-bc68-1d55e0b124e8

That work on me. I dunno.

**Comment by z-huang** [comment]
I added an option in the settings to stop music service when the app is cleared from tasks.

**Comment by Aaniket7** [comment]
> I added an option in the settings to stop music service when the app is cleared from tasks.

Can't see such setting☹️

**Comment by z-huang** [comment]
It's not released, but you can try out debug builds.

**Comment by Aaniket7** [comment]
> It's not released, but you can try out debug builds.

When are you planning to release this setting?

**Comment by z-huang** [comment]
This week.
