### ISSUE TITLE
App crashes while sharing artist page.

### ISSUE THREAD

**Issue by Aaniket7** [z-huang/music#1426]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Go into the app
Play any song
Under name of the song you'll se an artist name, click on that...
Now at the top right of the scree there is share option, click on it
Boomm...here's how the app crashes..

### Expected behavior

Shouldn't be crashed.

### Actual behavior

It crashes.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/8fa12a35-21ab-45b2-b1b9-2b580a16daf9

### Logs

-

### InnerTune version

0.5.8

### Android version

Android 14

**Comment by z-huang** [comment]
I cannot reproduce. Can you provide logs?

**Comment by Aaniket7** [comment]
Would you plz help me finding logs

**Comment by z-huang** [comment]
Maybe check out this app: https://play.google.com/store/apps/details?id=com.tananaev.logcat&hl=en

**Comment by Aaniket7** [comment]
> Maybe check out this app: https://play.google.com/store/apps/details?id=com.tananaev.logcat&hl=en

Not working in my phone

**Comment by z-huang** [comment]
So, you may need a computer to do this.
Read the doc: https://developer.android.com/tools/logcat
The simplest way is to run `adb logcat`, do something that causes the crash in your phone, stop `adb logcat`, and report all the outputs.

**Comment by z-huang** [comment]
Closing for inactive.
