### ISSUE TITLE
FDroid & IzzyOnDroid stuck on version 0.5.3

### ISSUE THREAD

**Issue by user8446** [z-huang/music#1433]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

FDroid & IzzyOnDroid are stuck on version 0.5.3 and not progressing.

Are the recent releases on github considered beta?

**Comment by Anonuser-code** [comment]
No, it is not beta. It is better version with better features. Just use the full version on github. Fdroid is not up to date.

**Comment by user8446** [comment]
Thank you. What about IzzyOnDroid? I do see this commit but not sure if that is what was blocking the updates there:

https://github.com/z-huang/InnerTune/commit/2f5576cc3767f516d8456850d5c8134887523f31

**Comment by Anonuser-code** [comment]
> Thank you. What about IzzyOnDroid? I do see this commit but not sure if that is what was blocking the updates there:
> 
> https://github.com/z-huang/InnerTune/commit/2f5576cc3767f516d8456850d5c8134887523f31

I have no idea. I just use github happly.

**Comment by z-huang** [comment]
F-Droid has built the latest version (https://monitor.f-droid.org/builds/build) and will update soon.
IzzyOnDroid has updated to 0.5.8 hours ago.
