### ISSUE TITLE
Sharper and HD song thumbnails

### ISSUE THREAD

**Issue by Grevellia123** [z-huang/music#1434]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I want a more HD song thumbnail, I know it might take a lot of data but you can provide HD and low features for thumbnails in settings
![IMG_20240822_000547](https://github.com/user-attachments/assets/6965e681-89ee-40dd-b5c2-8c8c0f227973)

### Why do you want this feature?

Because I want the song thumbnail to look better or HD like on YouTube

**Comment by Megaantony00** [comment]
Maybe it can be even transformed to a square like from this


![maxresdefault (4)](https://github.com/user-attachments/assets/b11c2f8f-ba0d-44ad-b15e-ca1ce01b3b74)


To this

![download (1)](https://github.com/user-attachments/assets/daf83f7d-4eb9-491c-b884-9387ea11e339)

**Comment by ABHIRAJ770** [comment]
Brooo how do you change the app like that you have sharp thumbnail and wayvy timeline

**Comment by Roxo7777** [comment]
![Screenshot_20240826_014338_Muzio Player.jpg](https://github.com/user-attachments/assets/a34792c9-e036-42c0-b36f-27bfc4cbb034)

This option exists in Muzio Player (it's in Portuguese)

**Comment by filinux13** [comment]
what i don't like most is when the video is 1:1 and the thumbnail in innertune cuts to fit in 16:9

**Comment by z-huang** [comment]
Do you have examples?

**Comment by z-huang** [comment]
@Grevellia123 that resolution is the highest one youtube gave.
- https://music.youtube.com/search?q=rumor+police+piccadilly
- Right click on the thumbnail and open the image in new tab
- https://i.ytimg.com/vi/DWwFK2gjwa8/sddefault.jpg?sqp=-oaymwEWCJADEOEBIAQqCghqEJQEGHgg6AJIWg&rs=AMzJL3nwImtH8Qmfex3GId551y6IvFOFrQ
- This image is 400x225
