### ISSUE TITLE
Pure black in search menu

### ISSUE THREAD

**Issue by frutejuise** [z-huang/music#1437]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Opening the search menu in black mode, the search menu background is a themed color. Though it would appear better if it where black.

### Why do you want this feature?

It would improve consistency and have the benefits of pure black mode.

### Additional information

The solution would be to switch the category button backgrounds (which are black) with the background of the search menu (which is a themed color even though it takes more space.)

![Screenshot_20240821-165813](https://github.com/user-attachments/assets/9218bf98-9567-400a-b172-413ef72a7bbd)

**Comment by z-huang** [comment]
Thanks!

**Comment by frutejuise** [comment]
What about the background?

**Comment by frutejuise** [comment]
What I mean is, the search menu should have black theme: 

![Screenshot_20240822-084038.png](https://github.com/user-attachments/assets/31aef8d3-12bb-4176-b4c5-5631a2dc8c42)

![Screenshot_20240822-084031.png](https://github.com/user-attachments/assets/596329bb-d6e9-4e98-8ccb-0ab72f55a5b4)

The background should be black and the chips should mimic the ones in the library for consistency.

**Comment by z-huang** [comment]
Hey, I cannot make everything black. The search bar has a higher visual level, and hence its color is different than black. https://m3.material.io/components/search/specs The spec clear states that. We need non-black colors so that the hierarchy of elements can be accentuated.

**Comment by frutejuise** [comment]
Ah ok

**Comment by Username1-a** [comment]
> Hey, I cannot make everything black. The search bar has a higher visual level, and hence its color is different than black. https://m3.material.io/components/search/specs The spec clear states that. We need non-black colors so that the hierarchy of elements can be accentuated.

Can you at least make those elements darker so that it wouldn't be so out of place (Like it was in 0.5.5)? They don't need to be that bright in black theme, what's the point of it then
