### ISSUE TITLE
Musixmatch lyrics

### ISSUE THREAD

**Issue by ABHIRAJ770** [z-huang/music#1440]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add musixmatch lyrics for wider lyrics library and better translation

### Why do you want this feature?

It's good for translation of lyrics if its in a language I don't know

**Comment by z-huang** [comment]
Musicmatch API is not free.
