### ISSUE TITLE
Playlists not loading

### ISSUE THREAD

**Issue by RadioactivePlays** [z-huang/music#1441]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Login with account then try to load a playlist.

### Expected behavior

Show playlist contents

### Actual behavior

Keeps showing the skeleton loading screen

### Screenshots/Screen recordings

![Screenshot_20240822-110511](https://github.com/user-attachments/assets/c7a77b22-8db7-458c-ba08-713ffe1251e4)

### Logs

Not able to get It.

### InnerTune version

0.5.4

### Android version

Android 14

**Comment by Anonuser-code** [comment]
You indicated 0.5.4 version. Are you sure you are using latest (0.5.8) version?

**Comment by ruskcoder** [comment]
This issue was fixed a few releases ago, try updating and see if it works.

**Comment by RadioactivePlays** [comment]
> You indicated 0.5.4 version. Are you sure you are using latest (0.5.8) version?

I'm using the latest one available on F-Droid, 0.5.7. Is F-Droid a recommended source?

**Comment by z-huang** [comment]
GitHub is a more recommended source, as it's directly released by me, and F-Droid usually delays a few days to update.

**Comment by RadioactivePlays** [comment]
Just saw the "compare versions" section. Tysm.
