### ISSUE TITLE
Home button for easier navigation

### ISSUE THREAD

**Issue by CranialTyrant** [z-huang/music#1448]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

A home button, whether it be a logo or house icon, should be in the top left hand corner and when tapped, it'll take you back to the home screen.

### Why do you want this feature?

The reason for the suggestion is for ease of use in navigating in the app. Instead of having to tap the back button multiple times to get to the home screen, it can be done with one tap.

**Comment by Malopieds** [comment]
Hi, you can long press the back arrow and it will do what you're asking.

**Comment by ganairm** [comment]
Android already has a home button/gesture. why are you even asking for this?

**Comment by CranialTyrant** [comment]
> Hi, you can long press the back arrow and it will do what you're asking.

Had no idea this existed. Thank you!
