### ISSUE TITLE
App crashes when adding multiple songs with little delay

### ISSUE THREAD

**Issue by ItamiWasTaken** [z-huang/music#145]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. add 50+ songs and download
2. clear app from recents screen

### Expected behavior

app continues to run normally

### Actual behavior

app crashes less than a second after opening it, you are able to bypass this by tapping a different tab before it crashes.

### Music version

0.3.1

### Android version

Android 12.1

**Comment by neilideal** [comment]
I have the same problem on android 11, but downloading 24 - 26 songs

**Comment by owencz1998** [comment]
Think this is a known issue there is a issue with downloads at the moment where your device starts to delete the media I think he said he needs to fix that issue so hopefully it might fix that as well I'm not 100% sure if he needs to rewrite downloads or if it's a simple fix and I think he is busy at the moment hence no reply 🙂

**Comment by senolfndk** [comment]
phone crashes on search result: Samsung Galaxy A21s android 12

**Comment by senolfndk** [comment]
Samsung Galaxy A21s android 12 crashing on search result

**Comment by z-huang** [comment]
Can you provide log?

**Comment by Rabanad** [comment]
@z-huang 

I have the same issue described above:

type: crash
osVersion: google/raven/raven:12/SQ3A.220705.004/2022081800:user/release-keys
package: com.zionhuang.music:9
process: com.zionhuang.music

java.lang.NullPointerException
at com.zionhuang.music.utils.DownloadProgressMapLiveData$onActive$1$1.invoke(DownloadProgressMapLiveData.kt:25)
at com.zionhuang.music.utils.DownloadProgressMapLiveData$onActive$1.invokeSuspend(DownloadProgressMapLiveData.kt:16)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:14)
Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@eabcb8a, Dispatchers.IO]

**Comment by z-huang** [comment]
I removed displaying downloading progress temporary, so it's fixed.
