### ISSUE TITLE
add possibility to download all songs in playlist with 1 button

### ISSUE THREAD

**Issue by karimHI** [z-huang/music#1450]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

download all button on playlists 

### Why do you want this feature?

some playlists are to big to do it manually

**Comment by z-huang** [comment]
Add the playlist to your library and you'll see the download all button.
