### ISSUE TITLE
Add spotify account support

### ISSUE THREAD

**Issue by jyzeng77** [z-huang/music#1452]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Allow users to connect their spotify accounts to innertune, so that they may access and play spotify playlists on innertune.

### Why do you want this feature?

I have all my playlists on spotify and while I enjoy the quality of the Innertune app and its music, it's a hassle for me to transfer all my playlists from Spotify to Youtube Music. It would be more convenient for spotify users to just be able to take their existing music and playlists and directly use it in Innertune. Definitely will help grow user base too!

**Comment by z-huang** [comment]
Use this [service](https://www.tunemymusic.com/) to migrate your playlists to YTM.
