### ISSUE TITLE
Easy app updates

### ISSUE THREAD

**Issue by jyzeng77** [z-huang/music#1453]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Make a way for users to easily check for new Innertune updates and directly install them without needing to backup their data, check for a newer package and uninstall old/install new version of app.

### Why do you want this feature?

It's really hard to keep the app up to date as of its current system. It would be nice to have updates directly managed natively in the app rather than require users to go through all that work!

**Comment by jyzeng77** [comment]
Unless there's some easy way to do this that I'm not aware of???

**Comment by Anonuser-code** [comment]
You mean an update manager.

Secondly, you can update app without backup songs. Just install apk while still installed older version. Newer version will installed without delete your songs. I use that way. But if you want previous version, then you have to back up.

**Comment by z-huang** [comment]
True.
An in-app update checker is available, but I won't do an in-app upgrader.
