### ISSUE TITLE
PC Support For InnerTune Users

### ISSUE THREAD

**Issue by kitodoescode** [z-huang/music#1457]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I want InnerTune For PC

### Why do you want this feature?

Pls consider my request. I don't like the ui of YTM web and i also don't have YTM premium.

**Comment by kitodoescode** [comment]
Pls consider my request. I don't like YTM ui and I don't have premium.

**Comment by ruskcoder** [comment]
Use SpMp or Spotube (search on github). A pc app isn't planned as the current android app needs priority.

**Comment by z-huang** [comment]
Right. I don't have extra time for a pc version.
