### ISSUE TITLE
Select multiple songs at once

### ISSUE THREAD

**Issue by Roxo7777** [z-huang/music#1459]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

By pressing and holding on any part of a song, you can select not only 1 song, but several at once and select them.
https://drive.google.com/file/d/1fVSNws8Em7tXF7dp4_WIkUPmlxm7iF6P/view?usp=drivesdk

The screen recording was too big, so I uploaded it to the drive.

### Why do you want this feature?

I downloaded a lot of songs, and since the backup of the songs was removed, the method would be to relocate them in a playlist.

### Additional information

No, in the production list there is no button to select all or to put it in a playlist.
I consider this resource, although a little indifferent on certain occasions, of supra importance, whatever version you add it, it is important to be able to select several songs.

**Comment by Roxo7777** [comment]
Not to forget, when adding the option to select multiple songs, don't forget the option to select all (at once).

**Comment by Roxo7777** [comment]
If not for now, add the option to create a playlist with the list of reproduction, it would also help in my case.

**Comment by ruskcoder** [comment]
#1348
