### ISSUE TITLE
latest app (Music_v0.3.1.apk) is being flagged as a trojan

### ISSUE THREAD

**Issue by phartshorn** [z-huang/music#146]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Download the app on a phone that has the avast virus scanner
2. launch the app
3. observe the notification that the app is malicious

Also see the virus total report: https://www.virustotal.com/gui/file/e3d378402f998020cdc16f98f849afa1530c2501597d2228091265769cb0dd15

### Expected behavior

the app should be able to be open without being flagged as malware

### Actual behavior

the phone detected the app as malware

### Screenshots/Screen recordings

![Screenshot_20220810_130006](https://user-images.githubusercontent.com/47765103/183820167-723a84ce-de84-4ddc-b49a-07089e3029a7.jpg)

### Music version

0.3.1

### Android version

Android 12

### Additional information

The phone I use is a Vivo y20s (which has avast scanning built in)

I first downloaded the app through the f-droid app and then downloaded it directly from the itzyOnDroid link in the readme - same result both times.

Version 0.3.0 (downloaded directly from itzyOnDroid) does not get detected as malware.

**Comment by z-huang** [comment]
It's strange. 0.3.1 is flagged, but 0.3.0 isn't. You can find the code diff of the two versions [here](https://github.com/z-huang/music/compare/v0.3.0...v0.3.1). I will rebuild 0.3.1 apk and upload to VirusTotal to test again.

**Comment by z-huang** [comment]
The rebuild 0.3.1 APK [test report](https://www.virustotal.com/gui/file/6f19606a459f5b3d8f3d3d7f0cce18234b02813ad119631361db44fe6ca5df15?nocache=1) is still flagged by Avast-Mobile. But I build the developing `feature/innertube` branch APK([here](https://www.virustotal.com/gui/file/fff23567bede5972c38de4b44755f7ce1ece5cbfa983097d951608e3d6e7796b/detection)), and there's no reds. I think it's a false positive.

**Comment by z-huang** [comment]
I can confirm that the code is safe, and an open-source project is transparent to everyone. So, I'll close the issue.
