### ISSUE TITLE
sort by like date

### ISSUE THREAD

**Issue by siggi1984** [z-huang/music#1463]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I think it would be cool to sort the songs further, namely by "like date"

### Why do you want this feature?

X

**Comment by Anonuser-code** [comment]
Or change the queue of songs

**Comment by z-huang** [comment]
Unfortunately, the database stores "like" information in boolean, not timestamp. To do this, I need to change the database scheme.

**Comment by siggi1984** [comment]
> Unfortunately, the database stores "like" information in boolean, not timestamp. To do this, I need to change the database scheme.

Everything is fine, if this sorting option is problematic. It is a wish of mine, in the end you decide what you implement. No matter what you decide, "Innertune" is a great app. Thank you very much for it.

**Comment by z-huang** [comment]
So, I won't add this in the near future.
