### ISSUE TITLE
Smaller speed increments

### ISSUE THREAD

**Issue by frutejuise** [z-huang/music#1466]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Smaller speed increments, like .10/.15/.20. Or make the increments editable.

### Why do you want this feature?

Sometimes .25± speed isn't great in either direction, most of the time it's basically useless.

**Comment by Filipexos** [comment]
I think speed/pitch control should be a slider, easier to control.

**Comment by Roxo7777** [comment]
It doesn't make sense, kind of useless, it would be better to put a reverb + slowed and a speed up, or rather, an internal equalizer.
