### ISSUE TITLE
Sleep Timer till end of playlist

### ISSUE THREAD

**Issue by filinux13** [z-huang/music#1468]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

There should a option to Change the sleep timer till the end of the playlist (right next to end of song sleep timer)

### Why do you want this feature?

It would help a lot and it would benefit everyone who uses the sleep timer function.

**Comment by z-huang** [comment]
Instead of this feature, you may want an option to disable auto-loading more songs. Which one you think is better?

**Comment by filinux13** [comment]
> Which one you think is better?

Maybe adding that option could be more usefull.

**Comment by serrq** [comment]
I would like listening a whole album and saying to your app shut off at the end of it.
