### ISSUE TITLE
Slowed + Reverb and Speed-Up

### ISSUE THREAD

**Issue by Roxo7777** [z-huang/music#1469]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I don't know if there is an app with it, but I really like audios with reverb and slowed, or speed up, if you can make an equalizer put these options first, because I think it's more useful than what voice virtualizer. 

### Why do you want this feature?

Some artists in their singles put speed up usually, one of my favorites (shiny_sz) puts in all, however, there are artists who don't, i like the same effect of the reverb + slowed or speed up of the music of it, wanted to be able to apply it to songs that the artists doesn't put in his singles.

(this translation is far from expressing me correctly, but in essence, that's all it is.)

**Comment by ItzHenry1** [comment]
You can try tweaking pitch and tempo settings, I got a similar slowed and speed up effect modifying this settings
![Screenshot_20240827-060148~2](https://github.com/user-attachments/assets/a9b32506-a84e-4d6e-8b49-1080e313e108)

For slowed I just made speed 0.75x and pitch between -2 and -5 and speed up 1.25x and +2

**Comment by ItzHenry1** [comment]
Hope this helps to achieve a similar result for you!

**Comment by z-huang** [comment]
Sorry, I don't quite understand your description. Can you explain more?

**Comment by Roxo7777** [comment]
> Sorry, I don't quite understand your description. Can you explain more?

Sorry for the confusing understanding

Add an internal equalizer, which would have the option of slowed and reverb, along with speed-up, these options usually only exist in music editors like Moises, but there are some versions of Muzio Player that had it, but they took it away along with the volume booster.

Example of the artist I mentioned:
https://music.youtube.com/browse/MPREb_9MAUej69Aaw

**Comment by z-huang** [comment]
This feature sounds very professional. Moises uses AI techniques and both apps are closed-source. I don't think I can make it. Let's wait for contribution :)
