### ISSUE TITLE
Bottom menu for search items

### ISSUE THREAD

**Issue by ansarimohammed422** [z-huang/music#1470]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

When we search a song we get song suggestion below search bar but when we long press on those songs the menu doesn't appear just like queue items so add that also

Like when we long press on search item bottom song menu should appear

### Why do you want this feature?

It will elevate application user experience UX

**Comment by ansarimohammed422** [comment]
And Now its a Complete Application
Thanks😀
@z-huang

**Comment by z-huang** [comment]
Still a lot of work to do. 😃
