### ISSUE TITLE
"New Release Albums" Always Shows Local Content Despite Changing Default Country

### ISSUE THREAD

**Issue by mecodeur** [z-huang/music#1473]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1 - Open the app and go to the settings.
2 - Change the default content country to any country other than your current location (e.g., USA, Australia, Belgium,..).
3 - Navigate to the "New release albums" section.
4 - Observe that the albums displayed are still from your current country.

### Expected behavior

The "New release albums" section should display albums from the selected country after changing the default content country.

### Actual behavior

The section continues to display albums from my current country, ignoring the selected default content country.

### Logs

No Logs

### InnerTune version

0.5.8

### Android version

Android Studio Koala | 2024.1.1 Patch 1

### Additional information

![01](https://github.com/user-attachments/assets/2dc624bb-39f3-46c7-8345-8366731822a9)
![02](https://github.com/user-attachments/assets/b17fa020-10bf-4008-a83d-5e1e80fc166d)

**Comment by z-huang** [comment]
Have you restarted the app?

**Comment by mecodeur** [comment]
Yes, I have restarted the app, but I still get the same result. However, when I use a VPN set to another country, the content in the "New release albums" section changes accordingly

**Comment by dainvincible1** [comment]
ive same issue

**Comment by z-huang** [comment]
> Yes, I have restarted the app, but I still get the same result. However, when I use a VPN set to another country, the content in the "New release albums" section changes accordingly

InnerTune changes the `gl` parameter to simulate different country, but it seems that YTM doesn't really care about `gl` but take your IP to get your country. Then, we have no way to fix this issue.

**Comment by mecodeur** [comment]
That's what I thought as well because I tried setting a static value for gl, but the result didn’t change. Thank you very much for the explanation and your help!
