### ISSUE TITLE
No songs play anymore

### ISSUE THREAD

**Issue by AlecHCodes** [z-huang/music#148]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Find any song
2. Tap play on the song

### Expected behavior

Song should play

### Actual behavior

Song doesn't load, stops loading after ~2 seconds

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/87393142/184492835-7ddc019e-1d8a-4af8-981e-85a93fc553ed.mp4

### Music version

0.3.1

### Android version

Android 11

### Additional information

Probably related to https://github.com/TeamNewPipe/NewPipe/issues/8760,  needing a Newpipe Extractor update

**Comment by z-huang** [comment]
See #147.

**Comment by jeffreyxuworld** [comment]
[v0.23.2](https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.23.2) already released
