### ISSUE TITLE
Restoring a backup makes app crash

### ISSUE THREAD

**Issue by dt192** [z-huang/music#1480]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Install app
Restore backup

### Expected behavior

Music restored

### Actual behavior

App crashes and then immediately crashes on every attempt to open thereafter

### Logs

I'm in bed atm, if you can't reproduce, let me know and I'll get logs later.

### InnerTune version

0.5.9

### Android version

14

**Comment by z-huang** [comment]
Are you migrating from Malopieds's fork? If so, check out this migration tool: https://github.com/7heMech/InnerTune-Backup-Fix

**Comment by dt192** [comment]
Many thanks, that resolved it. I hadn't realised that it was another fork, just thought it was an RC.

Something I did find is that the file downloaded from that site can't be opened in InnerTune. I had to duplicate it in the file manager and the duplicate opened without issue.

![Screenshot_20240828_161901_Files~2](https://github.com/user-attachments/assets/2de68c04-5e01-4bb5-89a0-7c5c04df7887)
