### ISSUE TITLE
Change downloaded music order

### ISSUE THREAD

**Issue by Anonuser-code** [z-huang/music#1485]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

The ability to change song order in the 'playlist' tab should also be available in the downloaded music tab (check video).

### Why do you want this feature?

Would be way more useful for most users of innertune

### Additional information

https://github.com/user-attachments/assets/9079c6cd-7f8f-42c2-8415-d2e145eb7a9c

**Comment by z-huang** [comment]
The database doesn't store position information of downloaded songs. Please add them to a playlist to be able to order them.
