### ISSUE TITLE
Automatically sync with your YouTube Music 

### ISSUE THREAD

**Issue by fuzi0nz** [z-huang/music#1486]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

This feature is implemented in the OuterTune fork but I really prefer the UI of InnerTune more. I was wondering if you could implement this feature as I like to keep the music I listen to synced up with my actual YT Music account and I think this would be a really helpful feature for some.

### Why do you want this feature?

I think it would add a lot more functionality and keep song recommendations fluid and more tailored throughout the YouTube Music and InnerTune ecosystem if we have the option to sync what we listen to on InnerTune.

**Comment by z-huang** [comment]
I'm considering about this. Move to #1409.
