### ISSUE TITLE
Screen protection over "recent apps" and "screenshot"

### ISSUE THREAD

**Issue by serrq** [z-huang/music#1492]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Some apps give the ability (optional) to switch ON/OFF the "screenshot" and "recent apps" protection feature by other prying apps.
Basically a privacy feature.

### Why do you want this feature?

More privacy. I don't want other apps can establish what are my habits and tastes.

### Additional information

![1000042036](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/499a76af-6db7-4f6b-b886-f06ff7dad708)

**Comment by z-huang** [comment]
I like this idea. Done.
