### ISSUE TITLE
Add a whole album to the library (button)

### ISSUE THREAD

**Issue by serrq** [z-huang/music#1493]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Adding a button to add a whole album to the playlist.

### Why do you want this feature?

Easy to use and save time.

### Additional information

![1000118113](https://github.com/user-attachments/assets/807bfde5-30cb-4972-80fb-18db8ff44738)

![1000118115](https://github.com/user-attachments/assets/7c3a4d9f-86bc-4900-8990-de4e3866469f)

**Comment by z-huang** [comment]
I'll add multi-select to album page.

**Comment by serrq** [comment]
Both solutions can live together in my opinion.

For example I am pretty sure about an album that I like, push the button + and boom... it is in my library.

Multi selection is useful when one doesn't like all the tracks of an album. So one selects just that he likes.

**Comment by z-huang** [comment]
I agree, so I added both of them!
