### ISSUE TITLE
Add "clean the queue" button

### ISSUE THREAD

**Issue by serrq** [z-huang/music#1494]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Clean the queue.

### Why do you want this feature?

Because sometimes I want start to listen totally different music tracks.

### Additional information

![1000118119](https://github.com/user-attachments/assets/1e6d8dcf-aa61-4e38-8224-6c33b4e7763d)

**Comment by thornySoap** [comment]
Why don't you just drag the player bottom sheet down to close the player?

**Comment by z-huang** [comment]
You can

- drag the player bottom sheet down to stop the player, as @thornySoap said
- click on a song to start a new queue
- multi-select all queue items and remove them

**Comment by serrq** [comment]
Not so intuitive but okay. It works. Thanks.
