### ISSUE TITLE
More iconic (and shorter) app name and icon

### ISSUE THREAD

**Issue by serrq** [z-huang/music#1497]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I literally trimmed all long app names.
 In the home screen Android restricts the characters limit to 8, if I don't wrong.

Currently I renamed InnerTune in Tune on my home screen, but there is yet too much "tune" in the app name that make your app so popular and not iconic.

iTunes, TuneIn, etc. to do some example.

In Italian "tune" is translated in "sintonia" if you like the sound of this word.

The icon is nothing special. People doesn't recognize it between thousands of similar ones.

Not a criticism, just I want improve to make this app better.

What do you think?

### Why do you want this feature?

More iconic.

There are app like Mull, Transistor, Fennec, Bura, Anemo, etc. that have their distinct name and styled. Iconic.

### Additional information

![1000118125](https://github.com/user-attachments/assets/0b37c89d-06c2-46da-88bc-5d6febf480df)

**Comment by z-huang** [comment]
> In the home screen Android restricts the characters limit to 8, if I don't wrong.

That depends on your screen width and the number of columns in your home screen.

The current app name and icon come from the discussion of the community, and I won't change it for a long time.
InnerTune comes from YouTube's private API, which called "innertube". The icon has "IT", which is the acronym of the app name. Many people have got used to this name and icon. Changing the name and icon again is not good for a product.

**Comment by serrq** [comment]
Thanks for the explanations.
