### ISSUE TITLE
Auto scroll up and down feature

### ISSUE THREAD

**Issue by Anonuser-code** [z-huang/music#1498]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

When i try to move order a song in playlist, page won't scroll up or down. (Check video)

Also we should select multiple songs for move order.

### Why do you want this feature?

Would be A LOT easier to edit playlist.

### Additional information

https://github.com/user-attachments/assets/1e00c9ed-e577-40be-be91-34a1819cd22a

**Comment by ruskcoder** [comment]
Yeah, I've had this issue a few times, it should also do that in the queue.

**Comment by Anonuser-code** [comment]
> Yeah, I've had this issue a few times, it should also do that in the queue. 

Also we should be able to sort in various ways.

**Comment by z-huang** [comment]
See #1225

**Comment by z-huang** [comment]
Done. Can you try and tell me if it's working right? I personally think the reordering feature vulnerable, so I need someone's test for insurance.

**Comment by Anonuser-code** [comment]
> Done. Can you try and tell me if it's working right? I personally think the reordering feature vulnerable, so I need someone's test for insurance.

Thank you. Seems like works well.
https://github.com/user-attachments/assets/f4a9413f-90cd-48f8-93fc-b10c5ba4431f

**Comment by Anonuser-code** [comment]
> Done. Can you try and tell me if it's working right? I personally think the reordering feature vulnerable, so I need someone's test for insurance.

Also custom order works well, thank you.https://github.com/user-attachments/assets/9ec9709c-b8ae-4551-8b69-72562949687b
