### ISSUE TITLE
Voice search

### ISSUE THREAD

**Issue by owencz1998** [z-huang/music#150]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

To be able to search by voice.

### Why do you want this feature?

Would be easier for me whiles I'm at work and might be helpful to others.

**Comment by z-huang** [comment]
Implemented.

**Comment by owencz1998** [comment]
It works perfect thanks so much 😁😁😁
