### ISSUE TITLE
Going to Modern Talking/Songs breaks InnerTune

### ISSUE THREAD

**Issue by Sagitee** [z-huang/music#1504]
### Checklist

- [ ] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Whenever I go to Modern Talking artist /  Songs section InnerTune stops.

### Expected behavior

Opening of the Songs section of that artist, without the app stopping.

### Actual behavior

Hi and thank you for the great work and app.
Whenever I go to Modern Talking artist /  Songs section InnerTune stops.
Thanks a lot.

### Logs

111

### InnerTune version

I'm facing this issue on all recent InnerTune releases (f-droid 0.5.3 - 0.5.8) and only on that particular artist/section. This behavior also happened on Malopieds InnerTune Github releases but not on other apps, like SimpMusic or ViMusic, that I tried.

### Android version

Android 13 LineageOS

**Comment by Richard38907** [comment]
Same here

**Comment by z-huang** [comment]
Thanks!

**Comment by Sagitee** [comment]
Great, thanks a lot.
