### ISSUE TITLE
Visually showing how much track I listened in the past (like shown in Next Player)

### ISSUE THREAD

**Issue by serrq** [z-huang/music#1505]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

When I have a long playlist like 67 music tracks, I do (i.e.) my home workout and listen a part of 67 tracks.

Next workout I listen an other part.

But how I do to understand where I arrived listening to?

Solution: visible track listening power bar.

### Why do you want this feature?

To have more awareness to how I listen music and discovering more tracks in long playlists.

![1000118161](https://github.com/user-attachments/assets/42d0a5a8-897a-40a9-a21b-e114437b59bb)

![1000118163](https://github.com/user-attachments/assets/9a2adc0e-06ed-4585-b4e8-d30c362ab3af)

**Comment by z-huang** [comment]
I don't think it necessary. A song is short. There's no need to listen to the first half first time, and listen to the second half next time.
