### ISSUE TITLE
Don't stopping music if I close app tab (in recent apps screen)

### ISSUE THREAD

**Issue by serrq** [z-huang/music#1507]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

When I close the InnerTune app tab music stream mustn't be stopped.

If I want stop music I can push "force quit" or stop it manually by the player control buttons.

### Why do you want this feature?

Because I want close InnerTune tab and controlling music from the notification bar.

**Comment by z-huang** [comment]
Check out settings -> player and audio -> stop music on task clear.

**Comment by serrq** [comment]
OnePlus CPH2399
Android 14
Inner 0.5.9 Izzy

Doesn't run (stream stops itself) or app crashes.

![1000118168](https://github.com/user-attachments/assets/bc791bfa-e62a-4ed4-9c35-2b112821ecbf)

**Comment by serrq** [comment]
News about this issue?

0.5.10 doesn't solve the issue.

**Comment by z-huang** [comment]
Any logs?

**Comment by serrq** [comment]
How to produce a log? I am not a developer.

**Comment by Richard38907** [comment]
Download platform tools (adb)

To generate logs type:

adb logcat > logcat.txt

Ctrl+C to stop the log monitoring and generate the log

ℹ️(To set up adb: you can watch a tutorial.)

**Comment by serrq** [comment]
I am not a developer. Molly has logcat built-in.
