### ISSUE TITLE
Multiple choice at once (filtering)

### ISSUE THREAD

**Issue by serrq** [z-huang/music#1509]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

When I search new music, I want selecting multiple filter at once, simultaneously.

For example "albums" and "featured playlists".

### Why do you want this feature?

To improve my searches.

![1000118180](https://github.com/user-attachments/assets/df30a42b-f907-4a94-907c-06ea74f51c21)

**Comment by z-huang** [comment]
Why not watch one first and switch to another filter?

**Comment by serrq** [comment]
Why must I do two distinct researches when I can do one only and quickly finding what I search or discover?

I can combine more filters at once and having an overall sight.

Answer: time. More productive my method.

**Comment by z-huang** [comment]
To have an overall sight, you can take advantage of the "All" filter. It contains some of each filters.

IMO, when you're searching, you have a clear mind about your target -- songs, albums, artists, or playlists. I don't wander around each filters. If you don't know clearly what you want, radio and home screen recommendations will be more suitable.

Second, how to combine multiple filters? How to sort these items? Share your thoughts if you have some.

**Comment by serrq** [comment]
> when you're searching, you have a clear mind

Wrong. When I am searching something new, I am an explorer, I completely unaware on what I will discover.

But okay, I closed the isssue. So no problem.
