### ISSUE TITLE
Add 'cancel' button in notification drawer when I download something if mistakenly activated

### ISSUE THREAD

**Issue by serrq** [z-huang/music#1510]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Cancel button in notification panel.

### Why do you want this feature?

To avoid mistakes (preserve data plan and battery in case of mistake).

![1000118183](https://github.com/user-attachments/assets/9055966b-074b-4d2f-9964-fa1ba2847bd3)

**Comment by serrq** [comment]
I discovered another way to stop a download, but objectively cancel it in notification panel is more comfortable (my opinion).

**Comment by z-huang** [comment]
How?

**Comment by serrq** [comment]
Going in the album/song/playlist and pushing again the download button (it cancel the download).

**Comment by z-huang** [comment]
Adding a button in the notification may be possible.

**Comment by Hikari2w2** [comment]
Good idea 💡
