### ISSUE TITLE
Large gap with empty space between sections in the "Forgotten favorites" section

### ISSUE THREAD

**Issue by netrunner-exe** [z-huang/music#1511]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Open homepage 
2. If you have one song in the Forgotten favorites section, you might see a big gap between sections

### Expected behavior

This gap visually ruins the homepage

### Actual behavior

Big unsightly gap with empty space between sections in the "Forgotten favorites" section, possible if there is only one song in the list.

### Screenshots/Screen recordings

![Screenshot_2024-08-31-18-20-35-453_com zionhuang music debug](https://github.com/user-attachments/assets/61d4ca3a-a5c3-49e5-b156-b0dc5e193e34)

### Logs

N/A

### InnerTune version

Latest debug

### Android version

A13

**Comment by z-huang** [comment]
Thanks!

**Comment by netrunner-exe** [comment]
@z-huang, Hi!  Almost got it 
![Screenshot_2024-08-31-19-07-02-946_com zionhuang music debug](https://github.com/user-attachments/assets/d40cecf8-dad6-4924-97fe-f3aaa235cc3d)

**Comment by z-huang** [comment]
Sorry I forgot to change height.

**Comment by netrunner-exe** [comment]
@z-huang now all works like charm , thank you! 

![Screenshot_2024-08-31-19-38-32-893_com zionhuang music debug](https://github.com/user-attachments/assets/94503952-7f00-49b7-b29a-4bd0335d008c)

![Screenshot_2024-08-31-19-39-22-557_com zionhuang music debug](https://github.com/user-attachments/assets/aad090d0-f07f-4e33-a6cf-53a69952b82b)
