### ISSUE TITLE
A YouTube sync feature that's automatic - inspired from OuterTune 

### ISSUE THREAD

**Issue by JDjunior057** [z-huang/music#1512]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

![Picsart_24-08-31_23-31-11-188](https://github.com/user-attachments/assets/2610f106-1ae0-41d7-a0d3-e0f662aa7931)

In OuterTune, a fork of Innertune there's a good feature I loved. (Tons of bugs in there though, something to consider when adding features). 

There's a feature that allows YouTube playlists to be added automatically. Instead of going through each one and syncing them manually. 

The sync is also bidirectional. That means when you add a song to the playlist in OuterTune app, the change is reflected in YouTube. 

P.s: there's a bug in it - latest playlist doesn't appear in the list. This can be solved easily using Innertune's manual syncing. Bad news is that OuterTune doesn't have manual syncing options ( I didn't find maybe I haven't looked enough) 

### Why do you want this feature?

For someone like me, with around 40 playlists minimum in one account, it's tedious to do all the playlists manually. Imagine someone with 100+ playlists. 

Also, I could only add 25 playlists at a time. So I had to update the others so that it appeared in account menu of the home page in Innertune. Apparently it shows newly created 25 playlists at a time. I don't think I missed the option to change that number. I have been using innertune for 3 days now. 

### Additional information

I am not an Android developer and have almost no idea about software engineering. So I am sorry I was unable to provide technical solution to the problem. 

If it was game dev or anything I would probably be of more use. 

Sorry about that. Even without this feature, Innertune is a solid app.

**Comment by JDjunior057** [comment]
I was trying to say it. Optional obviously. 
I know a few cases ( I myself have few accounts where it would be bad if it was a core feature and not optional. ) 

Like I have 25 playlists in one account, I wouldn't want all of them to reflect in the Innertune app. 

In the mentioned app, it's done nicely. It's up to user to choose if they want to sync.

**Comment by z-huang** [comment]
Move to #1409.
