### ISSUE TITLE
Sorting options ---> customized

### ISSUE THREAD

**Issue by serrq** [z-huang/music#1514]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Tracks order decided by user through drag and drop (up and down).

### Why do you want this feature?

To customize listening experience.

![1000118195](https://github.com/user-attachments/assets/720160d6-d3ad-4947-950d-f77714d49146)

**Comment by Anonuser-code** [comment]
Transfer your downloaded music to a playlist for now. Similar feature to you mentioned  probably come in the next update. I mentioned the same thing to the developer. Here is what he added:
 https://github.com/user-attachments/assets/a807c37d-c8eb-4684-9076-7af8e06e2b86

But would be better if Zion add same feature in "downloaded" page too.

**Comment by z-huang** [comment]
You need to convert the songs to a playlist. The database does not store position information in library/artist songs.
