### ISSUE TITLE
Easier remove from playlists / More direct info and changes on playlist inclusion of a song

### ISSUE THREAD

**Issue by Sagitee** [z-huang/music#1515]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I suggest:

![01](https://github.com/user-attachments/assets/8e478102-1e71-4a34-81a7-9bddd9e1db72)

a) (1st image) If a song is added in any playlist(s), the showing up of a Playlist icon under each song's title and next to its artist's name in the various song lists, just as the Library and Download little icons are showing up accordingly.

![02](https://github.com/user-attachments/assets/2b432f83-5626-465e-8381-699a5d27f32d)

b) (2nd image) The removing of the "Remove from playlist" menu icon and if a song is not added in any playlist, the remaining of the current "Add to playlist" menu icon.

![03](https://github.com/user-attachments/assets/e65acff1-48ac-4be1-ba2a-b4dd943f6097)

c) (3rd image) If a song is added in any playlist(s), the replacement/diffenrentiation of the "Add to playlist" menu icon and text eg. to something like that of the 3rd image, just as the Library and Download icons and text change to show if a song is already in the library and/or downloaded.

![04](https://github.com/user-attachments/assets/b1347504-9668-4618-99ff-af59efa5df44)

d) (4th image) The addition of an active checkbox next to each playlist, in the "Add to playlist" or eg. "Change playlist inclusion" window.

As a simple, less complete, alternative solution, to at least minimize the time/effort to remove a song from the playlists it is included in, I would suggest a "Remove from all playlists" menu icon/command, that would ideally be accessible from any songs list a song is viewed in or via the player's menu for any currently playing song.
Thanks a lot for the great work and app.

### Why do you want this feature?

Currently, it is very easy for one both to KNOW if a song is included in the library and/or is downloaded and to REMOVE it from the library and/or REMOVE the download.
Those options are possible and accessible for a song that is playing or that one sees in the varius list and sections, like:
- one's full library list
- the songs of an artist
- one's library's songs of an artist
- an album's songs of a list
- the search results songs list
- etc.
via the active icons that are both properly showing up next to the artist of the song in the lists and changing their shape and function (add/remove) accordingly in the menus of commands of the song.

On the other hand, KNOWING if a song is included in one or more playlist(s) and in which one(s) and/or REMOVING it from that (those) playlist(s) is of much difficulty, as one's only option is to leave from one's currently viewed list of songs where one sees that song and search for it in all the playlists (of maybe hundrends of songs).

**Comment by z-huang** [comment]
There will be too many badges if I add a playlist badge, and your proposal seems too complicated.
There're some existing features that may be helpful to you:
- When you add a song to a playlist, you get a notification if the song is already in that playlist.
- You can search in a playlist

**Comment by Sagitee** [comment]
Hi and thanks for your answer and suggestions.
Sorry for coming back.
I just want to remention, in case you didn't noticed it, the mentioned above, maybe less complicated, alternative solution, to at least minimize the time/effort to remove a song from the playlists it is included in, of a "Remove from all playlists" menu icon/command, that could be accessible from any songs list a song is viewed in or via the player's menu for any currently playing song.
Thanks a lot.
