### ISSUE TITLE
"Download all" button in 'Artist' page

### ISSUE THREAD

**Issue by serrq** [z-huang/music#1519]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

See the attachment.

### Why do you want this feature?

![1000118208](https://github.com/user-attachments/assets/6b4780a9-ffd0-4a6b-8e84-4ea3338d5038)

**Comment by z-huang** [comment]
Multi-select added in artist page.
