### ISSUE TITLE
Add ability to import a YouTube Playlist to your Library.

### ISSUE THREAD

**Issue by AqilCont** [z-huang/music#152]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I just have some playlists in YouTube, some with over 300-500 songs, and I would love to be able to add them to my library straight instead of tapping on each one and then pressing "Add to Library".

### Why do you want this feature?

Even though this app makes my life a lot easier already, it would make it very blissful.

### Additional information

I love this app! It looks amazing and fulfills all of my lifelong dreams. : D

**Comment by z-huang** [comment]
This feature is already available in `feature/innertube` branch, which will become the new version of this app. You can download debug apk to try it.

**Comment by AqilCont** [comment]
Ah thank you! The actions tab right? I'll see if there's any bugs or anything if you want me to.

**Comment by AqilCont** [comment]
I don't think the buttons work, and there's no way to migrate your old library ;w;

Sorry, idk if these are separate issues or if I should just wait because of the Issue Freeze.

**Comment by z-huang** [comment]
![IMG_20220819_073209.jpg](https://user-images.githubusercontent.com/39427017/185512735-63edf8f4-236e-47b0-93f2-8ba4ed729969.jpg)

The database structure changed a lot, so I'm not sure migration can be done.

**Comment by AqilCont** [comment]
Ohh, I was talking about the buttons on top of the playlist page under the title + info, but that works fine, thank you!! I think migration would be cool but yeah the whole app looks completely different so IDK.

**Comment by z-huang** [comment]
> I was talking about the buttons on top of the playlist page under the title + info

I haven't implement that.
