### ISSUE TITLE
Deleting while scrolling

### ISSUE THREAD

**Issue by Anonuser-code** [z-huang/music#1520]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

When scrolling through a playlist, it sometimes accidentally deletes a song by swiping to the side. Make it harder to swipe (change the angle required for swipe) and one way swipe (only from right to left).

### Why do you want this feature?

I accidentally delete songs when i scroll on page for reorder my song. Need a little fix. It deletes when I scroll at a slight angle. No problem for completely vertically scroll but slight angle deletes.

(Video from debug version)

### Additional information

https://github.com/user-attachments/assets/84d58a23-7648-4a5f-91e8-532889952aa3

**Comment by z-huang** [comment]
There's an undo button. See https://issuetracker.google.com/issues/252334353. There're some workaround to avoid accidentally deletion.

**Comment by Anonuser-code** [comment]
> There's an undo button. See https://issuetracker.google.com/issues/252334353. There're some workaround to avoid accidentally deletion.

But this happens so often 😭

**Comment by z-huang** [comment]
Please wait for the workaround to be added.

**Comment by Anonuser-code** [comment]
> Please wait for the workaround to be added.

okay
