### ISSUE TITLE
Continue playing

### ISSUE THREAD

**Issue by siggi1984** [z-huang/music#1525]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Automatically resume playback when Bluetooth connection or wired device connected

### Why do you want this feature?

X

**Comment by Anonuser-code** [comment]
Already resume?

**Comment by z-huang** [comment]
Already have that on my device.
