### ISSUE TITLE
In the latest version of InnerTune, the queue is not working correctly

### ISSUE THREAD

**Issue by netrunner-exe** [z-huang/music#1532]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Open playlist and play song
2. Open queue

### Expected behavior

Working queue

### Actual behavior

In the latest version of InnerTune, the queue is not working correctly. When playing a track from the playlist (it is not the last track in the playlist) and at the end of its playback, the transition to another song occurs not to the one that should be in order in the playlist, but to the one that was added to the queue. Settings: audio normalization, persistent queue, auto load more songs and shuffle icon in queue is disabled. Enabling or disabling these settings has no effect on this bug

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/31090957-6cd0-4a61-afe9-f0c39dc74818

### Logs

N/A

### InnerTune version

0.5.10

### Android version

A13

**Comment by ruskcoder** [comment]
Weird, it works for me. Are you sure it's the right version?

**Comment by netrunner-exe** [comment]
> Weird, it works for me. Are you sure it's the right version?

Of course I'm sure. Release 0.5.10, full. Try to open playlist from InnerTune homepage, for example from your Google music account, which has at least 70 songs, play one of the first, then scroll to the end and turn on some 50th (not from the queue menu but in the playlist) and see how the queue changes.

**Comment by z-huang** [comment]
YouTube changed their API. Tell me if the fix is correct.

**Comment by netrunner-exe** [comment]
> YouTube changed their API. Tell me if the fix is correct.

@z-huang Hi! Yes, looks like fix is working, thank you

**Comment by netrunner-exe** [comment]
@z-huang Then it turns out that I can't put my online playlist on repeat, even with "repeat all" enabled, when the end of the last song is reached, the tracks in the queue continue to play instead of returning to the first song in the playlist. Should I create a new topic in issues to solve this bug?
