### ISSUE TITLE
Color match albums background

### ISSUE THREAD

**Issue by owencz1998** [z-huang/music#154]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Match the colors of the album for the media player and also the mini player.

### Why do you want this feature?

Looks nice and really puts come colors into the app :)

### Additional information

![Screenshot_20220819-065443_YouTube Music](https://user-images.githubusercontent.com/96526481/185552803-359a6c6c-f916-413d-9566-bc1005cda369.jpg)
![Screenshot_20220819-065728_YouTube Music](https://user-images.githubusercontent.com/96526481/185552809-0feb9d90-5ece-4f9e-9cae-183978afa8a5.jpg)
![Screenshot_20220819-065453_YouTube Music](https://user-images.githubusercontent.com/96526481/185552811-a9bf6f95-1bf0-4259-abe3-5a482f029c75.jpg)

**Comment by z-huang** [comment]
I'd like the color to be applied to the whole theme, so let's transfer to #159.

**Comment by owencz1998** [comment]
No problem
