### ISSUE TITLE
Search plays first song

### ISSUE THREAD

**Issue by ruskcoder** [z-huang/music#1540]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1 - go to a playlist you have
2 - search for a certain song
3 - play the searched song

### Expected behavior

It should play searched song

### Actual behavior

It plays first song in playlist

### Logs

N/A

### InnerTune version

Latest

### Android version

13

**Comment by Anonuser-code** [comment]
Nope. Mine works well. Try add a video.

**Comment by ruskcoder** [comment]
Alright

What happens is when I search it plays the index of the song on the search of the playlist. Eg, I click the 3rd item in search, it plays the third item in the playlist.
 https://github.com/user-attachments/assets/88343696-0e04-441a-b9f1-79582ea0c428

**Comment by ruskcoder** [comment]
Oops, turns out my app didn't update to the latest version properly, it had an error I didn't notice 😅. I'll close this issue.
