### ISSUE TITLE
Change Stats Page to be Similiar to Last.FM

### ISSUE THREAD

**Issue by ThatOneUnoriginal** [z-huang/music#1548]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

To be absolutely clear, this isn't a suggestion to add last.fm support to InnerTune since you can already do that with the last.fm application. Rather this is a suggestion to change the stats screen on the InnerTune app to have a similar structure to Last.FM showing how many times you've listened to a song, artist, or album within the specified time. 

So for my example, instead of just saying that I've listened to Drake, Kendrick Lamar, and Eminem the most it'll tell me that I've listened to Drake 1296 times, Kendrick Lamar 382 times and Eminem 382 times. Malopieds forked version of InnerTune already has this version in the Debug version so I'll showcase that;
![Screenshot_20240903-191624](https://github.com/user-attachments/assets/944df0f6-0d6d-45bf-922d-f26d4df87362)

### Why do you want this feature?

I've been considering switching from [Malopieds](https://github.com/Malopieds/InnerTune) fork of the InnerTune application since the launch of the 5.10 update for the original InnerTune application (aka this one.) This feature is already implemented in a debug version of Malopieds fork and seeing that many features from the fork have knowingly or unknowingly been brought here, I thought this would be a nice addition to those. 

But to provide another reason other then "Malopieds version has it", I believe it would be a nice addition to know how many times you've listened to an artist, song, or album instead of just being told that it's the number 1 song you've listened to all time. Also when it comes to Malopieds implementation of the feature, it shows _every_ artist you've listened to, _every_ song you've listened to and _every_ album you've listened to, not just the top 6.

**Comment by Roxo7777** [comment]
I have already made a suggestion regarding this
#1460

**Comment by z-huang** [comment]
Close as duplicate.
