### ISSUE TITLE
Getting Weblate working again

### ISSUE THREAD

**Issue by lucasmz-dev** [z-huang/music#1559]
This is meant to track my work getting the project @ Weblate to work reliably.

**Comment by lucasmz-dev** [comment]
#1558 so that Weblate does not believe these strings to be translated properly when they're not

**Comment by lucasmz-dev** [comment]
Preferably asking the project at Toolate to be removed to decrease issues

**Comment by lucasmz-dev** [comment]
Merge all translation related PRs, and also #1557 to point users to Weblate

That should be it so that I can unlock the project with care

Adding https://hosted.weblate.org/engage/innertune/ afterwards if this all works out as a translation link in F-Droid could be nice

**Comment by z-huang** [comment]
@lucasmz-dev Many thanks to your contribution! In the past, I tried to set up Weblate but failed. Now, more people can contribute translations in a more friendly platform!

> Adding [hosted.weblate.org/engage/innertune](https://hosted.weblate.org/engage/innertune/) afterwards if this all works out as a translation link in F-Droid could be nice

How to do it?

**Comment by lucasmz-dev** [comment]
I'm actually not sure 😬
I was looking into it and I couldn't find the metadata files in F-Droid for InnerTune for some reason

**Comment by lucasmz-dev** [comment]
@z-huang https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15700

**Comment by lucasmz-dev** [comment]
Do you think it'd make sense to highlight Weblate working in the next update in changelogs? Like add a line saying "Our Weblate is now working! Check out the translation link in F-Droid to help us translate the app to more languages!"

**Comment by z-huang** [comment]
Yeah, it's okay.

**Comment by lucasmz-dev** [comment]
@z-huang 
![image](https://github.com/user-attachments/assets/d1d1bd95-77ce-4aa9-a59f-4092ddcc38d4)

Should I change it to GPL-3.0-or-later? I'm unsure here of how the licensing works

**Comment by Anonuser-code** [comment]
> @lucasmz-dev Many thanks to your contribution! In the past, I tried to set up Weblate but failed. Now, more people can contribute translations in a more friendly platform!
> 
> > Adding [hosted.weblate.org/engage/innertune](https://hosted.weblate.org/engage/innertune/) afterwards if this all works out as a translation link in F-Droid could be nice
> 
> How to do it?

Which platform do you use for translation of app? I want to help about it.

**Comment by lucasmz-dev** [comment]
@Anonuser-code 

Weblate, the same link you mentioned

Thanks for the help :)

**Comment by Anonuser-code** [comment]
> @Anonuser-code 
> 
> Weblate, the same link you mentioned
> 
> Thanks for the help :)

Then i did my translation on this site before. And when Zion going to update the languages?

**Comment by lucasmz-dev** [comment]
@Anonuser-code no promises. I would guess if everything goes alright then whenever next updates comes. 

If you'd like to check out how the translations are looking like, you can check the Weblate pull request and download the APK from GitHub actions by checking the "uploading APK" section.

**Comment by lucasmz-dev** [comment]
#1592 has some revelant info

**Comment by lucasmz-dev** [comment]
> Should I change it to GPL-3.0-or-later? I'm unsure here of how the licensing works

On this, I originally did, then put it back, and now I put it back on GPL-3.0-or-later, this licensing is specific to the translations, I think translations should be permissive, translators can't always be contacted and it would be a pain to do so already

**Comment by maboroshin** [comment]
Please check what is currently PL'd. (PL is pull request) If uploaded directly to GitHub, string.xml is PLed. https://github.com/z-huang/InnerTune/pulls?q=is%3Apr+is%3Aclosed

**History**

* Merged from Weblate in September 2024. [https://github.com/z-huang/InnerTune/pull/1573 ](https://github.com/z-huang/InnerTune/pull/1573) It was also merged from Weblate in October 2024.
* Merged but rejected by Crowdin in January 2024. Not merged. https://github.com/z-huang/InnerTune/pull/1212 (Crowdin has closed in 2024.)
* Merged but rejected by Crowdin in 2023. Not merged. https://github.com/z-huang/InnerTune/pull/859 Related: https://github.com/z-huang/InnerTune/issues/853
* Weblate was locked up for years. Weblate translation repository existed, but previously did not work at all. https://github.com/z-huang/InnerTune/pull/981

**Comment by lucasmz-dev** [comment]
Sorry @maboroshin I'm lost, what are trying to say? What does PL mean?

**Comment by lucasmz-dev** [comment]
I actually just now really became aware of the Crowdin. I was searching through issues and was like "huh?"

I could see if I could get these translations inside Weblate, in case no one already messed with them anyway

**Comment by maboroshin** [comment]
Thank you for your efforts.There was some confusion due to lack of announcements. I have documented it.

At present, developers should stop Crowdin. But that has not been done so there will be people doing translations on Crowdin. Documentation is needed for those confused.

**Comment by lucasmz-dev** [comment]
@z-huang maybe close Crowdin? Not sure if that's complicated

If there's any translations that haven't been merged and it's easy like Weblate to get a git history for it I would, I could look into if it makes any sense to put them in, though at this point they might have been overwritten by other people anyway

**Comment by lucasmz-dev** [comment]
Traffic there is pretty minimal at least a few strings every now and then but very much dead

**Comment by z-huang** [comment]
> maybe close Crowdin? Not sure if that's complicated

Closed.

**Comment by lucasmz-dev** [comment]
I have set up screenshots in Weblate, should help random translators that don't have the app
