### ISSUE TITLE
No Player Notification since ~v0.5.4

### ISSUE THREAD

**Issue by choozn** [z-huang/music#1564]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [x] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Open the app
2. Play any song
3. Swipe down to display notifications
4. No player is visible

### Expected behavior

A player notification should be displayed when playing a song.

### Actual behavior

No player notification is present.

### Screenshots/Screen recordings

![Screenshot_2024-09-05-19-08-10-77_f4703f2d42345ac28c56f11a6100c500](https://github.com/user-attachments/assets/94c6bc8e-c3aa-480c-a63d-675a209f9357)
![Screenshot_2024-09-05-19-08-06-26_f4703f2d42345ac28c56f11a6100c500](https://github.com/user-attachments/assets/0ed16eb3-251a-44b1-8af7-0d3831bd7622)

### Logs

/

### InnerTune version

Since ~0.5.4

### Android version

Android 11

### Additional information

The player is displayed properly in the fork by Malopieds (https://github.com/Malopieds/InnerTune).

**Comment by Anonuser-code** [comment]
![IMG_20240905_202019.jpg](https://github.com/user-attachments/assets/1f39eb88-2e40-47ec-85d4-0fe6f46dc340)

Works well for me.

**Comment by smarttommyau** [comment]
did you accidentally turn off the notification in the android settings?

**Comment by choozn** [comment]
I am in shame. Really sorry to have bothered you. 😔😅

Thank you @smarttommyau. I did not know that this was a setting in android.
