### ISSUE TITLE
The words“移除”show incomplete

### ISSUE THREAD

**Issue by internet-coffee** [z-huang/music#1572]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Choose a song,and press the menu button.

### Expected behavior

Show full words 

### Actual behavior

show incomplete

### Screenshots/Screen recordings

![Screenshot_20240908_100358_InnerTune](https://github.com/user-attachments/assets/d982ee1b-307f-446a-ac3e-750d20dd120f)

### Logs

I don't know what is it

### InnerTune version

0.5.10(full)

### Android version

Android 13

**Comment by KEVIN970712** [comment]
oh,the word“單” has the same problem,It seems that this problem occurs with double-line text.
