### ISSUE TITLE
APK detected as trojan

### ISSUE THREAD

**Issue by arfanmrafeek** [z-huang/music#160]
### Checklist

- [×] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [×] I've checked that there is no issue about this bug.
- [×] This issue contains only one bug.
- [×] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Installation 

### Expected behavior

Warning from Xiaomi Installation package virus scanner.

### Actual behavior

Unable to install, And Can't trust, I'm using bank applications. 

### Screenshots/Screen recordings

![Screenshot_2022-08-15-04-21-54-177_com miui global packageinstaller](https://user-images.githubusercontent.com/69381592/186416256-b49061fc-4e98-4547-9a7d-f75b6d87a930.jpg)

### Music version

Latest 

### Android version

Android 12 (Xiaomi note 10 pro 5G global edition, MiUi 13)

**Comment by arfanmrafeek** [comment]
#146 I saw, Anyway, I'll check.

**Comment by z-huang** [comment]
I don't know why it's flagged. I'll submit a false-positive to Avast. If you wan't to install, there's an "Ignore" text in your screenshot to bypass the check.

**Comment by z-huang** [comment]
I'm using MIUI too, and I find the apk passing the check.

**Comment by z-huang** [comment]
I've received the mail from Avast telling that they had marked the apk as clean.
