### ISSUE TITLE
Optimize application size

### ISSUE THREAD

**Issue by internet-coffee** [z-huang/music#1600]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I had used innertune for a long time, it's a great music application.But the application size is over 800mb(Not included cache),compare with Spotify,It only 200mb

### Why do you want this feature?

Save phone storage space

### Additional information

![Screenshot_20240917_125748_Settings](https://github.com/user-attachments/assets/b3f1c962-4052-41b9-92b0-1cb6c771958c)

**Comment by renhiyama** [comment]
InnerTune wil be caching/downloading your music locally. You can manually clear them in-app. InnerTune itself is pretty much optimized.

**Comment by z-huang** [comment]
You can set the cache limit in the settings.

**Comment by internet-coffee** [comment]
> You can set the cache limit in the settings.

what is "clear song cache" mean?
It doesn't seem to have anything to do with downloading songs.Is it used to speed up song loading speed?
![Screenshot_20240921_090814_InnerTune](https://github.com/user-attachments/assets/f51047a5-64a7-4410-ab28-7d7d33be3ce4)

**Comment by z-huang** [comment]
InnerTune automatically caches songs you're listening. Cached songs can play directly without Internet. It's just a mechanism to make it faster and improve user experience, but it takes more storage space. Cache is independent to downloads.
