### ISSUE TITLE
Audio sounds compressed and washed out

### ISSUE THREAD

**Issue by CranialTyrant** [z-huang/music#1602]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Having audio normalization on or off or the quality auto, high, or low doesn't seem to make a difference.
2. Open a song with a heavier melody (such as Theocracy's Hide in the Fairytale [https://music.youtube.com/watch?v=8AS1PelE138]
3. Around the 0:47-0:52 mark, the "washed out sound" is noticeable the cymbal clang and riff compared to the same upload being played through any other YouTube client.

### Expected behavior

It should sound more clear.

### Actual behavior

It sounds washed out.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/08efaf22-0564-44ff-9020-b193c9113ca0

### Logs

I don't have the ability to do this.

### InnerTune version

0.5.10

### Android version

Android 14

**Comment by gechoto** [comment]
Please tap on the three dots at the bottom and go to the "Details". Post a screenshot of it.

Also you should really turn audio normalization off in the current version
see https://github.com/z-huang/InnerTune/issues/1526

**Comment by Thatstinkyguy** [comment]
> Please tap on the three dots at the bottom and go to the "Details". Post a screenshot of it.
> 
> Also you should really turn audio normalization off in the current version see #1526

I put in a screen recording demonstrating the issue and I turned off audio normalization.

**Comment by CranialTyrant** [comment]
> Please tap on the three dots at the bottom and go to the "Details". Post a screenshot of it.
> 
> Also you should really turn audio normalization off in the current version see #1526

![Screenshot_20240922_030134_InnerTune](https://github.com/user-attachments/assets/37836921-b5ab-4531-9647-ffb80ff66970)

I also have audio normalization off, the audio quality is set to high, and I also turned off battery optimization.

I have no idea why the bitrate is lower on ones like this. I checked another song (King's X - Complain) and the bitrate listed in the details on that was 131.

**Comment by gechoto** [comment]
> I have no idea why the bitrate is lower on ones like this

Did you have the audio quality set to Low or Auto when you played the song for the first time?
Because InnerTune currently saves songs in a cache on first playback in the quality it was first loaded in. So if the audio quality is low on first playback -> it will always stay low

This might change in the future
see: https://github.com/z-huang/InnerTune/issues/1527#issuecomment-2324855247

The only workaround I know for now is you need to ensure that songs are never loaded in low quality.
To do this:
1) Close the currently playing song
2) Open settings
3) In `Player and audio` set `Audio quality` to `High`
4) Go back to settings and to `Storage`
5) Select `Clear all downloads` and `Clear song cache`

**Comment by CranialTyrant** [comment]
Unfortunately, the low bitrate on some songs persists (including the one used in the example), even after following the steps, and clearing the app cache from the settings.

**Comment by gechoto** [comment]
> Unfortunately, the low bitrate on some songs persists (including the one used in the example)

Just tested the example song and I get high quality opus (format 251)
![](https://github.com/user-attachments/assets/0d54d53a-785d-40ce-bae8-c1cc438fcb28)



> even after following the steps, and clearing the app cache from the settings.

Hm you could test uninstalling the app, reinstalling it and set audio quality to High as first step after installation before playing any song.

If this doesn't help it might be a server-side limitation. In this case using a VPN/Proxy might help.

What format do you get in the original YT Music app or the Web player?

**Comment by CranialTyrant** [comment]
@gechoto I get the high preset with YT Music itself. I'll try uninstalling and reinstalling.

**Comment by CranialTyrant** [comment]
@gechoto Update: I reinstalled it with importing a backup with my liked songs. That made the issue persist. However, after reinstalling it again and not importing a backup, it's fine. I'll have to like all my songs again, but as Thanos said...
![thanos-a-small-price-to-pay-for-salvation](https://github.com/user-attachments/assets/520fe350-4b11-4ef6-885f-cf63761de097)

Thanks for all your help, by the way!

**Comment by gechoto** [comment]
Continuation: https://github.com/z-huang/InnerTune/issues/1631
