### ISSUE TITLE
For my opinion in full version of Innertune you can use musixmatch to lyrics translation

### ISSUE THREAD

**Issue by furkansa50** [z-huang/music#1605]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

You know sometimes machine translation can be wrong

### Why do you want this feature?

For see better translations

**Comment by priyanshu8017** [comment]
Same thing, Hindi to English translation is terrible 🤣

**Comment by z-huang** [comment]
Musixmatch is not free.
