### ISSUE TITLE
Add comments in InnerTune

### ISSUE THREAD

**Issue by cgykcftyi** [z-huang/music#1609]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

You can find comments about this song on the main interface of the music player. It is best to obtain them directly from the original music source.

### Why do you want this feature?

lt will be very interesting to listen a song with watching other people's comments.

### Additional information

![Screenshot_20240919_232225_app rvx android apps youtube music](https://github.com/user-attachments/assets/861f8f48-aca7-4867-b061-d3e05cb476b6)

**Comment by HehehBoiii78** [comment]
When I first saw this issue, I thought that you want the developer to add Tooltips in InnerTune, which don't exist anywhere in the app yet.

**Comment by z-huang** [comment]
Not planned. I don't think it necessary.
