### ISSUE TITLE
When playing music from the "search" section, the application crashes.

### ISSUE THREAD

**Issue by Insidevk18** [z-huang/music#161]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Open the app

2.Go to the "search" section

3. play any song searched on the internet.

### Expected behavior

The app would be expected to play the songs normally.

### Actual behavior

The app automatically closes.

### Screenshots/Screen recordings

![1](https://user-images.githubusercontent.com/94028610/186963688-e35a0597-a88f-4351-84a3-98bac5d589d6.jpg)
![2](https://user-images.githubusercontent.com/94028610/186963721-93fe8743-162c-47b8-bbcb-94a16ad3e075.jpg)
![3](https://user-images.githubusercontent.com/94028610/186963736-4f17b1a7-2010-4e1e-949c-7af956892719.jpg)
![4](https://user-images.githubusercontent.com/94028610/186963740-77d82627-2a54-4442-81a4-774a02d7b448.jpg)
![5](https://user-images.githubusercontent.com/94028610/186963745-2a8f9a81-e7b1-4e00-bde5-8f9b65fdb8cf.jpg)

### Music version

0.3.2

### Android version

Android 10

### Additional information

-Phone: Xiaomi Redmi 8A
-MIUI version: MIUI Global 12.5.1
-NewPipe version of the "music" app: 0.22.1

Note: The app closes automatically, and is not even in the background.

**Comment by bacteriostat** [comment]
Newpipe Extractor needs update. See https://github.com/TeamNewPipe/NewPipe/issues/8876
