### ISSUE TITLE
Arch-specific .apk files for the app's FOSS variant

### ISSUE THREAD

**Issue by ghost** [z-huang/music#1611]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

You should provide arch-specific .apk files of the app's FOSS variant.

### Why do you want this feature?

This will make the FOSS variant of the app smaller.

**Comment by z-huang** [comment]
It's already small enough.

**Comment by ghost** [comment]
Why not make arch-specific .apk files for the app's FOSS variant? It comes at no cost to the user. I don't see why not.

**Comment by z-huang** [comment]
Users may be confused about why there're so many files and which one to download. 7mb is really not a big file, considering today’s internet technology.

**Comment by ghost** [comment]
> Users may be confused about why there're so many files and which one to download. 7mb is really not a big file, considering today’s internet technology.

I think you should add a link to some page explaining which one you should pick or do a short explanation on release descriptions.

**Comment by nvllz** [comment]
@FixItKit such a comparison is already linked under download badges at the top of readme page
