### ISSUE TITLE
Error: "Sign in to confirm you're not a bot"

### ISSUE THREAD

**Issue by gechoto** [z-huang/music#1614]
### Checklist

- [ ] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Play a song or a few, sometimes it works for a while before the error shows up

### Expected behavior

Songs should play

### Actual behavior

At some point playback does not work anymore and it shows this error in place of the cover image

### Screenshots/Screen recordings

![](https://github.com/user-attachments/assets/9ed4999e-6711-4885-9672-972381ebefef)

### Logs

idk how to get this

### InnerTune version

0.5.10

### Android version

Android 14

**Comment by serrq** [comment]
![1000120512](https://github.com/user-attachments/assets/517c82f0-7898-4c33-b25c-df6a6751a826)

**Comment by lettuceandmeat** [comment]
![Screenshot_20240930_065944_InnerTune.jpg](https://github.com/user-attachments/assets/91026bd2-428d-49ec-a6b5-29ec422a990a)
Same

**Comment by lettuceandmeat** [comment]
![Screenshot_20240930_065944_InnerTune.jpg](https://github.com/user-attachments/assets/43509fea-1a82-4306-bc7c-f5ade2bd9e35)

Same

**Comment by Kyoria** [comment]
change your vpn nodes

**Comment by gechoto** [comment]
> change your vpn nodes

I'm not using a VPN

**Comment by dheerajgajula02** [comment]
looks like that is a block by google servers if it has suspicious activity from your network, I don't think there's anything that can be done , just use mobile data , and turn off VPN if you have it on and clear cache and try. It should ideally work. It did for me, I had my wire-guard setup on AWS and it didn't work for me.

**Comment by serrq** [comment]
I got stuck in this position. No playing.


![1000124563](https://github.com/user-attachments/assets/49b67cc4-03ef-41f5-8d0e-c64427593a8e)

**Comment by gechoto** [comment]
A few duplicates:
https://github.com/z-huang/InnerTune/issues/1674
https://github.com/z-huang/InnerTune/issues/1673
https://github.com/z-huang/InnerTune/issues/1666
https://github.com/z-huang/InnerTune/issues/1660
https://github.com/z-huang/InnerTune/issues/1657
https://github.com/z-huang/InnerTune/issues/1654
https://github.com/z-huang/InnerTune/issues/1653
https://github.com/z-huang/InnerTune/issues/1645
https://github.com/z-huang/InnerTune/issues/1632

**Comment by donty** [comment]
This looks to be only related to innertune. It's not the net connection it looks like Google servers are blocking access and require a YouTube music subscription to continue access.

**Comment by z-huang** [comment]
See #1653
