### ISSUE TITLE
Switch piped instances

### ISSUE THREAD

**Issue by th3me** [z-huang/music#1632]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Switch the piped instance the player uses to fetch music.

### Why do you want this feature?

Player started throwing an exception for me so I dumped logs and found out this app used the piped api and the specific instance it was calling (piped.kavin.rocks) threw an error on the site when trying to play a video. I searched for other instances that would work for me and there was one and it would be nice if I could use it with innertune without building the app myself. Thanks.

### Additional information

![picturecache_0](https://github.com/user-attachments/assets/cac339c7-bcb8-4539-8342-86a561246afa)
![picturecache_0](https://github.com/user-attachments/assets/5b648312-611e-4f6d-803b-0996c851336e)
![picturecache_0](https://github.com/user-attachments/assets/f0dc2175-e79a-495a-85db-4b2feb3e799a)

**Comment by z-huang** [comment]
See #1653
