### ISSUE TITLE
Uknown Error after clearing cache

### ISSUE THREAD

**Issue by ProphetVII** [z-huang/music#1643]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Clear cache for songs and images
2. Update App
3. Play any song

Can not quite reproduce because I can't play any songs since clearing the cache. 

### Expected behavior

Songs start getting cached again. 

### Actual behavior

Unknown Error when trying to play songs.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/6a0602e1-7780-471c-b316-b1737842cc9c

### Logs

n/a

### InnerTune version

5.1

### Android version

Android 14

**Comment by Toasin80** [comment]
I am also facing the same issue.

**Comment by ProphetVII** [comment]
I went over to F-Droid and un-installed the version that I had. Installed again from F-Droid. It's working again. 

cc @Toasin80
