### ISSUE TITLE
Player says "unkown error" when trying to open random music

### ISSUE THREAD

**Issue by HafizBeyy** [z-huang/music#1657]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

When i click on a it mostly says : "unkown error" and refuses to play it

### Expected behavior

it should have played

### Actual behavior

it said "unkown error"
nowadays it says "please sign in"

### Logs

.

### InnerTune version

0.5.10

### Android version

Android 14

### Additional information

i promise ima donate 200try if you solve these issues. it costs 1/10 of my monthly allowance. also i want to provide logs but dont know how.

**Comment by Vikingtons** [comment]
Also able to reproduce this on a pixel 7 / Android 14. Perhaps we should rename this issue to be more concise?

**Comment by z-huang** [comment]
See #1653

**Comment by kranukul** [comment]
I am also facing the similar kind of issue even though I am already logged in with a gmail account.

please help me to resolve the issue !! 
![Screenshot_20241217-232121](https://github.com/user-attachments/assets/fd8d783e-460d-4985-abd8-fae722513ec1)
![Screenshot_20241217-232103](https://github.com/user-attachments/assets/f054944f-1aa3-44c5-98a5-dcdb5cc0425f)

**Comment by loxoron218** [comment]
For me it also started again to not work today, even though I'm connected with my _Google_ account...
