### ISSUE TITLE
Add search in playlist

### ISSUE THREAD

**Issue by owencz1998** [z-huang/music#166]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add search bar in playlists.

### Why do you want this feature?

Easier to search for a song in playlist without having to find it though thousands of songs :)

**Comment by z-huang** [comment]
Instead of searching in playlist, why not searching in the library?

**Comment by owencz1998** [comment]
Ahh yeah not a bad shout as the songs will be downloaded there to haha is downloads working now dude

**Comment by z-huang** [comment]
> is downloads working now

Fixed.

**Comment by owencz1998** [comment]
Nice very quick Nice job dude much appreciated 😄
