### ISSUE TITLE
Please sign in

### ISSUE THREAD

**Issue by TruongTanLuc201270** [z-huang/music#1660]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Play but say "Please sign in"

### Expected behavior

As above

### Actual behavior

As above

### Screenshots/Screen recordings

![Screenshot_20241019-160712](https://github.com/user-attachments/assets/e148d1b8-3240-4881-a92d-16feff5c02fe)

### Logs

I have no logs

### InnerTune version

0.5.10

### Android version

9

**Comment by Fantasy924** [comment]
Hello, just go into Settings -> Content, then log in using your Gmail account. Then boom it should be fixed.

**Comment by ytggobs** [comment]
> Hello, just go into Settings -> Content, then log in using your Gmail account. Then boom it should be fixed.

I signed in to my Gmail and didn't do anything. Maybe Gmail accounts with multiple YouTube accounts doesn't work?

**Comment by ProphetVII** [comment]
Had this issue, Logging in through the Settings fixed it for me.

**Comment by Saiv46** [comment]
> I signed in to my Gmail and didn't do anything. Maybe Gmail accounts with multiple YouTube accounts doesn't work?

Same issue. App started working once I deleted auto-created channel, then I was able to successfully log in.

**Comment by looowizz** [comment]
Hi! i get this same issue but it seems to resolve itself after clicking the error message a few times :)

**Comment by ihaadi** [comment]
> Hi! i get this same issue but it seems to resolve itself after clicking the error message a few times :)

it doesn't work for me

**Comment by TruongTanLuc201270** [comment]
Need backup first before uninstall then reinstall this app to fix, may be fixed.

**Comment by jericjan** [comment]
I can confirm that it only seems to work when the account used only has one YouTube account

**Comment by Samarthsattani66** [comment]
Why it's not working

**Comment by Namithesh** [comment]
> Hello, just go into Settings -> Content, then log in using your Gmail account. Then boom it should be fixed.

is there any other workaround without login in

**Comment by Takashi-69** [comment]
I have the same issue, I downloaded the latest version it shows and searches all the latest songs but when I play them it says "please sign in" there is no sign in option in the app??? Please help.

**Comment by eu-kode** [comment]
I have the same issue. After few songs played it show the message "Login".
And even after logging in with my personal account it shows the same error. It's really annoying and makes the app useless. 

![Screenshot_20241024_221555_Gallery.jpg](https://github.com/user-attachments/assets/55e7dc21-ee8d-41cf-b669-3437f1654be9)

**Comment by Ariseheart-24** [comment]
I thought signing in was optional,why now is it becoming a forced issue

**Comment by choozn** [comment]
Same issue on my end

**Comment by casta** [comment]
Hello, it seems general to all yt clients. RiMusic has the same issue (and working on it): https://github.com/fast4x/RiMusic/issues/4106

**Comment by choozn** [comment]
Original Issue: https://github.com/z-huang/InnerTune/issues/1653

**Comment by techy2245** [comment]
The new issue now is I can't play songs even though I have signed showing some Java error![Screenshot_2024_1025_230625.jpg](https://github.com/user-attachments/assets/9c209200-ad66-4171-8683-70549e32fddc)

**Comment by JAE2103** [comment]
RiMusic just fixed this issue, please add the fix to this app

**Comment by techy2245** [comment]
Rimusic isn't working

**Comment by z-huang** [comment]
See #1653

**Comment by FIREHAWK039** [comment]
> Hello, just go into Settings -> Content, then log in using your Gmail account. Then boom it should be fixed.
Worked for me... THANKs
