### ISSUE TITLE
Awesome Work!

### ISSUE THREAD

**Issue by BrandonIsHere5** [z-huang/music#1665]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I actually don't want to share any features that should be added, but I just wanna say thanks Zion Huang for this app! Very cool and easy to use, I'd like to donate but can't, maybe if I got my own money, I would literally donate you per week! Awesome work! I'm loving it! Please keep up the good work, I really would love to donate you!

### Why do you want this feature?

It's already good enough to me

### Additional information

Absolutely awesome work!

**Comment by z-huang** [comment]
Thanks!
