### ISSUE TITLE
Log In

### ISSUE THREAD

**Issue by jorge2985** [z-huang/music#1666]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Ingreso a la aplicación
2. Selecciono un tema musical
3. El tema no se reproduce porque pide que me loguee
4. Me logueo en la sección de contenidos 
5. Selecciono otro tema
6. Me pide nuevamente que me loguee a paser ya estarlo.

### Expected behavior

Debería poder reproducir los temas musicales.

### Actual behavior

Este problema comenzó hoy y con cualquier tema. Tanto los de mi historial como los que aparecen en la Home o los que busco.

### Logs

-

### InnerTune version

0.5.10

### Android version

Android 14

**Comment by ExalFelix** [comment]
I am having the same issue since this morning. One thing I suspect to be the cause is having multiple YouTube accounts associated with one Google account. Do you have more than one channel for your Google account?

**Comment by SixthPhilosopher** [comment]
Same here.
I don't have any YT channel associated with my Google account.

**Comment by choozn** [comment]
Duplicate of https://github.com/z-huang/InnerTune/issues/1660

**Comment by gechoto** [comment]
Duplicate of:
https://github.com/z-huang/InnerTune/issues/1674
https://github.com/z-huang/InnerTune/issues/1673
https://github.com/z-huang/InnerTune/issues/1660
https://github.com/z-huang/InnerTune/issues/1657
https://github.com/z-huang/InnerTune/issues/1654
https://github.com/z-huang/InnerTune/issues/1653
https://github.com/z-huang/InnerTune/issues/1645
https://github.com/z-huang/InnerTune/issues/1632
https://github.com/z-huang/InnerTune/issues/1614

Please close this, we have too many already.

**Comment by jorge2985** [comment]
I close the issue cause it's duplicate
