### ISSUE TITLE
I really like the vimusic ui, is there any plan on implementing an option to use vimusic ui?

### ISSUE THREAD

**Issue by SolskGaer** [z-huang/music#1667]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

![WechatIMG6](https://github.com/user-attachments/assets/cde14cbb-78e9-4c00-a544-c2a28e2d28ff)
something like this, the Innertube UI is great, but I would appreciate having another option as well.

### Why do you want this feature?

An alternative UI is appreciated

**Comment by choozn** [comment]
I guess use vimusic (?!)

**Comment by n-ce** [comment]
Innertune is not part of ViMusic family. You can use ViTune, Music You, RiMusic for that.

**Comment by z-huang** [comment]
> Innertune is not part of ViMusic family. You can use ViTune, Music You, RiMusic for that.

Yes.
