### ISSUE TITLE
Multiple select 

### ISSUE THREAD

**Issue by owencz1998** [z-huang/music#167]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

To be able to select multiple songs in all pages on the navigation bar.

### Why do you want this feature?

quicker to download all songs and to delete or select 1 by 1 :)

**Comment by z-huang** [comment]
Duplicate of #116
