### ISSUE TITLE
Info on downloads 

### ISSUE THREAD

**Issue by owencz1998** [z-huang/music#168]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add a % on songs that are downloading and maybe network speed if possible.

### Why do you want this feature?

Just to make it easier to tell if songs are being downloaded  :)

### Additional

**Comment by z-huang** [comment]
The percentage of download is temporarily removed so as to fix #145. I won't display network speed because Android has the setting to show network speed in the status bar.

**Comment by owencz1998** [comment]
Ahh ok my phone doesn't have the network % haha

**Comment by z-huang** [comment]
Oh, sorry. But I think network speed text isn't that important because the fillesize isn't big.

**Comment by owencz1998** [comment]
No worries I will wait for the fix 😁I'll close this issue now 😁
