### ISSUE TITLE
Option to disable screen wake lock

### ISSUE THREAD

**Issue by emi-YFcz5XDj** [z-huang/music#1682]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Currently, Innertune stops the screen from turning off when in certain states.

Add an option that allows the user to turn this feature off.

### Why do you want this feature?

My phone has attention aware, this feature is redundant and only causes accidental battery drain.

**Comment by z-huang** [comment]
Wake lock is only applied when you're looking at lyrics. To prevent this, toggle off lyrics.
