### ISSUE TITLE
Download issues 

### ISSUE THREAD

**Issue by owencz1998** [z-huang/music#169]
Ahh it's now working on this version again how strange I'll close the issue 😅

**Comment by z-huang** [comment]
Download info is shown in notification. The app just won't show the download progress.

**Comment by owencz1998** [comment]
All the files are downloaded and this is all it does

![Screenshot_20220901-055924_Music Debug.jpg](https://user-images.githubusercontent.com/96526481/187834801-53bfe0ff-4fb9-4397-8ab7-462eed573b7f.jpg)

![Screenshot_20220831-202701_Solid Explorer.jpg](https://user-images.githubusercontent.com/96526481/187835011-4318b8bc-a676-42e0-8e92-e0ff98310a21.jpg)
