### ISSUE TITLE
Search local artists and playlists

### ISSUE THREAD

**Issue by airon90** [z-huang/music#17]
You can look through songs but not through artists and playlists

**Comment by z-huang** [comment]
Can you specify more in detail? I can't really get it.

**Comment by airon90** [comment]
If you want to search for a particular song in your saved music, you can do it by tapping on the magnifier icon. If you want to search for a particuoar artist or playlist between your saved ones you can't do that

**Comment by z-huang** [comment]
Got it. This feature isn't added yet. Possibly combined with #7 to make a unified search fragment.
