### ISSUE TITLE
when will the new app be available

### ISSUE THREAD

**Issue by Alliba** [z-huang/music#170]
When will there be an update to the next version. is there already a plan?
the development of the app looks awesome to you, can't wait for the update.
keep it up...

**Comment by z-huang** [comment]
Almost finished. Just fixing bugs and implementing migration code for users from 0.3.3. Dynamic theme and lyrics won't be included in this version.

**Comment by z-huang** [comment]
BTW, you should post this in the discussion section. It's not an issue.
