### ISSUE TITLE
Some songs require Sign in

### ISSUE THREAD

**Issue by mohsinnawaz04** [z-huang/music#1718]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Search My Rules by Dua Lipa
2. Play Song

### Expected behavior

The song should play.

### Actual behavior

Instead, It says **Requires Sign In**

### Screenshots/Screen recordings

![Screenshot_20241117-081701](https://github.com/user-attachments/assets/cb958946-736e-4cff-91d1-6283decf2dec)

### Logs

No log to show.

### InnerTune version

0.5.10 Full

### Android version

Android 14

**Comment by ganairm** [comment]
just sign in man. go into settings -> content and sign in with your google account

**Comment by Hazhi-Hassan** [comment]
> just sign in man. go into settings -> content and sign in with your google account

I am signed in and everything works but still when i try to play any songs, it says please sign in!

**Comment by Atony1400** [comment]
All songs require it now. Works after signing in, I'd just rather not if I can. Also this has seemingly broken Discord integration as well.

**Comment by Hazhi-Hassan** [comment]
> All songs require it now. Works after signing in, I'd just rather not if I can. Also this has seemingly broken Discord integration as well.

Don't quite understand how this can be done. But to be honest, this version has lots of issues. Hope it gets fixed

**Comment by mosstuff** [comment]
Just wanted to say same over here. I've been having this issue for months now.. I attached a screen recording of me signing in but it still not working.. Am I doing something wrong or is it really just broken?
https://github.com/user-attachments/assets/76b62a39-f275-4d49-b347-15fa6e54dba8

**Comment by TruongTanLuc201270** [comment]
Please see #1653

**Comment by MillionsToOne** [comment]
> just sign in man. go into settings -> content and sign in with your google account 

This is like telling a person with broken GPU drivers to just buy a new GPU. It doesn't solve the problem, only circumvents it.

**Comment by ThisIsSidam** [comment]
> I am signed in and everything works but still when i try to play any songs, it says please sign in!

My personal experience, the same was happening. But I noticed that my gmail had multiple channels in it and maybe the problem was in choosing one. I used a different account with only one channel. Same happened. Went to login again, and saw Yt Music instead of Youtube this time, went back and could see my username instead of 'login' in the settings. Very happy that its working for me now.

**Comment by ganairm** [comment]
> > just sign in man. go into settings -> content and sign in with your google account
> 
> This is like telling a person with broken GPU drivers to just buy a new GPU. It doesn't solve the problem, only circumvents it.

the fuck do you mean? it literally tells you to sign in, and signing in works for the majority of people, me included. what's wrong with it?

**Comment by ganairm** [comment]
just use an account that isn't linked to a youtube channel. if it still doesn't work, create a new email and use that to sign in. this will definitely work

**Comment by mohsinnawaz04** [comment]
I'm sorry. It was a blunder on my side. I had to log in with my google account and it fixed the error.

**Comment by MillionsToOne** [comment]
> > > just sign in man. go into settings -> content and sign in with your google account
> > 
> > This is like telling a person with broken GPU drivers to just buy a new GPU. It doesn't solve the problem, only circumvents it.
> 
> the fuck do you mean? it literally tells you to sign in, and signing in works for the majority of people, me included. what's wrong with it?

I literally mean what I mean? Do you have reading comprehension issues? It doesn't solve the problem. It's a band-aid solution.

**Comment by macharia22** [comment]
Y'all how do I unsubscribe from this thread? I am not a fan of emails
honestly 😭. I have tried unsubscribing here and github too but new
messages keep popping up. Kindly help

**Comment by MillionsToOne** [comment]
If you are gonna advertise the app as usable without accounts, then making it work is the right step. Otherwise you might just remove it completely.

**Comment by MillionsToOne** [comment]
> Y'all how do I unsubscribe from this thread? I am not a fan of emails honestly 😭. I have tried unsubscribing here and github too but new messages keep popping up. Kindly help

Just press the unsubscribe button, or on mobile, 3 dots and unsubscribe.

**Comment by ganairm** [comment]
> > > > just sign in man. go into settings -> content and sign in with your google account
> > > 
> > > 
> > > This is like telling a person with broken GPU drivers to just buy a new GPU. It doesn't solve the problem, only circumvents it.
> > 
> > 
> > the fuck do you mean? it literally tells you to sign in, and signing in works for the majority of people, me included. what's wrong with it?
> 
> I literally mean what I mean? Do you have reading comprehension issues? It doesn't solve the problem. It's a band-aid solution.

it's been working flawlessly for many people, thank you very much. prob an issue on your end then lol

**Comment by MillionsToOne** [comment]
> > > > > just sign in man. go into settings -> content and sign in with your google account
> > > > 
> > > > 
> > > > This is like telling a person with broken GPU drivers to just buy a new GPU. It doesn't solve the problem, only circumvents it.
> > > 
> > > 
> > > the fuck do you mean? it literally tells you to sign in, and signing in works for the majority of people, me included. what's wrong with it?
> > 
> > I literally mean what I mean? Do you have reading comprehension issues? It doesn't solve the problem. It's a band-aid solution.
> 
> it's been working flawlessly for many people, thank you very much. prob an issue on your end then lol

And it doesn't work as it should. You should be able to listen to music without an account. Therefore it being a band-aid solution. It doesn't fix the problem you idiot. It only circumvents it.
