### ISSUE TITLE
Like or dislike

### ISSUE THREAD

**Issue by owencz1998** [z-huang/music#174]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

And the 👍 or 👎  on media screen and also add a heart on the notifications bar.

### Why do you want this feature?

Quicker way to add the music to your songs section if u don't want to set it up to automatically and allows u to choose what u like also a heart into the notifications bar so u don't have to open up the app to add it to your songs.

**Comment by z-huang** [comment]
I'll just add ❤️, not 👍 or 👎.

**Comment by owencz1998** [comment]
Nice one bro 👌

**Comment by airon90** [comment]
Are there differences between Like and Add to library?

**Comment by z-huang** [comment]
You can only like library songs, so like the song will also add the song to library.
