### ISSUE TITLE
Nothing shows up on Explore>Song, Video tab

### ISSUE THREAD

**Issue by PKRN0** [z-huang/music#175]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Open app
2. Go to explore tab
3. Search for anything

### Expected behavior

Songs related to my search keyword should appear.

### Actual behavior

Nothing appears.

### Screenshots/Screen recordings

[screen capture](https://imgur.com/a/f8Qgdjs)

### Music version

0.3.3

### Android version

Android 12 July ASB, MIUI 13.0.6.0 SKFIDXM

### Additional information

System language is Korean

**Comment by owencz1998** [comment]
He's releasing a bug update soon 0.4.0 which has a proper home screen and many new features have u tried the debug version in innertube branch and in the actions page

**Comment by z-huang** [comment]
It seems that you're in Korea, so your are probably facing #136. The solution is to find a proxy or VPN because YT Music is not supported in your country.

**Comment by PKRN0** [comment]
> It seems that you're in Korea, so your are probably facing #136. The solution is to find a proxy or VPN because YT Music is not supported in your country.

Oops, I missed that issue. Sorry for my carelessness.

And thanks for making such a cool app.
