### ISSUE TITLE
Discord integration not showing in Discord

### ISSUE THREAD

**Issue by HGStyle** [z-huang/music#1751]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Login to YouTube Music to make listening to music works (if needed)
2. Login to your Discord account in InnerTune
3. Play any song

### Expected behavior

A popup should show with the title I am currently playing.

### Actual behavior

Nothing pops up, but it definitely didn't do anything: when I entered the app, my account (which I was not currently connected to) came from offline to online.

### Screenshots/Screen recordings

![image](https://github.com/user-attachments/assets/93381f18-739c-4e78-a5d1-cb0235e22b24)

### Logs

Read "Additional information"

### InnerTune version

0.5.10

### Android version

Android 14 - HyperOS & HyperOS 2

### Additional information

This bug makes me unable to play songs to test if the embed works or not: https://github.com/z-huang/InnerTune/issues/1748
However this bug exists since multiple months, never made an issue because I didn't had time to...

Also, note that I am trying to see the Discord integration popup from another account with which I am friend to.

**Comment by HGStyle** [comment]
Mobile screenshots:

![Screenshot_2024-12-18-08-53-26-153_com zionhuang music](https://github.com/user-attachments/assets/09074371-54af-4fd7-842f-4ab57dc01dd6)
![Screenshot_2024-12-18-08-53-20-187_com zionhuang music](https://github.com/user-attachments/assets/3ce97f8e-55a1-4bfd-981b-a69f8fbf7c83)

**Comment by CranialTyrant** [comment]
https://github.com/z-huang/InnerTune/issues/1725

**Comment by HGStyle** [comment]
> #1725

Sorry, closing this.
