### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Knsravan** [z-huang/music#1762]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1.Play My name is Billa Song
2.Forward Music to at a particular time
3.There We get Unknown Error
4.This is Happing to some of The songs and some song get error at start of the playing the song 
![Screenshot_20241219-204613](https://github.com/user-attachments/assets/96b85102-965c-49f5-aab1-179e0fc7ccd1)

### Expected behavior

Showing Unknown Error For some of the songs 

### Actual behavior

It should play the songs with out any errors 

### Logs

Ad logcat

### InnerTune version

0.5.10

### Android version

Android 13

**Comment by Jackson4Rocks** [comment]
Ya, it has been happening to alot of people. I don't think it's a bug

**Comment by Knsravan** [comment]
Please look into this It's even in the previous version of the app and after update it some what good and now it's showing again these errors
