### ISSUE TITLE
Got Unknown error? JUST LOG OUT

### ISSUE THREAD

**Issue by fishmodem** [z-huang/music#1782]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

If you're getting "Unknown error" on all songs, it's because of a change on youtube's end that broke all playback for logged in accounts on InnerTune.

The easiest fix is to just log out of your youtube account by going to Settings > Content > [Your google acc name], and logging out from the web interface that opens. Then you should be able to play most songs in InnerTune without the error.

Note: This will NOT allow you to play songs with age-restriction on them. As far as I'm aware though testing "fixes" in issues and patches in PRs in this repository, there is no working patch or fork that makes this possible yet. 

### Expected behavior

N/A

### Actual behavior

N/A

### Screenshots/Screen recordings

N/A

### Logs

N/A

### InnerTune version

0.5.10

### Android version

N/A

### Additional information

Sorry to break the issues formatting for this. Only options are "bug" and "enhancement" and I figure this pertains to a bug so it's the best fit.

**Comment by ohyeah23940** [comment]
I tried this, but it didn't work. I'm still getting the same error after logging out and logging back in.

**Comment by Smittttttt** [comment]
After logging out it says "Please sign in"

**Comment by thehost12** [comment]
> I tried this, but it didn't work. I'm still getting the same error after logging out and logging back in.

You can't log back in, and you can't be logged out either because it will just ask you to log back in, you can only listen to songs you have downloaded until it's patched

**Comment by fishmodem** [comment]
It might be working for me like that because I use microg instead of google play services, or because of my region. It loads non-age-restricted songs fine, but age-restricted ones do show the "Please sign in." I'll close this as I don't want to mislead anyone.
