### ISSUE TITLE
Proxy settings

### ISSUE THREAD

**Issue by xmha97** [z-huang/music#180]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

YouTube blocked on my country.
Please add the proxy settings. (Socks5)

### Why do you want this feature?

Access to YouTube

**Comment by owencz1998** [comment]
Has proxy setting in version 0.4.0 check innertube branch and go to actions page and get the debug version

**Comment by z-huang** [comment]
But it only support HTTP proxy. I need to add SOCKS support.
