### ISSUE TITLE
My phone restarts!

### ISSUE THREAD

**Issue by xmha97** [z-huang/music#182]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Go to the "Music" app
2. Play music
3. Crashing Bluetooth!
4. My bluetooth turns on and off rapidly
5. My phone restarts!
6. It enters the recovery menu
### Expected behavior

Play music without issue

### Actual behavior

See "Steps to reproduce the bug"

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/23485114/190854361-b3206525-ea1b-4d2d-b37e-f2d92e8b8dc4.mp4

![Screenshot_2022-09-17-16-04-15-483_com.miui.bugreport.jpg](https://user-images.githubusercontent.com/23485114/190854654-b38dd59c-02a1-4ac1-ba82-e7e2c6a41a58.jpg)

### Music version

0.3.3 (Debug)

### Android version

Android 12

**Comment by xmha97** [comment]
Last night, in order to solve this problem, I factory reset my phone, but the problem still persists.

Please don't close this issue until it is resolved although I have no logs to give you so you can resolve it.

**Comment by z-huang** [comment]
I'm sorry. Is that your phone can't boot normally after the crash?

**Comment by xmha97** [comment]
No, It enters the recovery menu!

**Comment by xmha97** [comment]
No, It enters the recovery menu!
Yes, this is reproducable.
Isn't this a strange problem?

**Comment by xmha97** [comment]
@z-huang 
I have installed this app on several Xiaomi mobile phones
This problem happened on all these phones!

When Bluetooth is turned off, the app works fine
But as soon as Bluetooth is turned on, Bluetooth turns off and on quickly, and the phone restarts.

Please turn on Bluetooth on your mobile to see if there is a problem or not.

I have to choose between Bluetooth and this app
Hi, wired handsfree

**Comment by z-huang** [comment]
I'm using a Xiaomi phone, too. But I don't have this issue. My bluetooth is open all the time.

> ![Screenshot_2022-09-17-16-04-15-483_com.miui.bugreport.jpg](https://user-images.githubusercontent.com/23485114/190854654-b38dd59c-02a1-4ac1-ba82-e7e2c6a41a58.jpg)

Can you give me the full output? I need lines that start with "com.zionhuang.music" so that I may know where the disaster starts.

**Comment by xmha97** [comment]
> Can you give me the full output?

# Page 2
![Screenshot_2022-09-17-17-51-30-679_com.miui.bugreport.jpg](https://user-images.githubusercontent.com/23485114/190859419-edf1aea1-ea26-4dbb-9e2a-0baa771285f9.jpg)

# Page 3
![Screenshot_2022-09-17-17-52-51-537_com.miui.bugreport.jpg](https://user-images.githubusercontent.com/23485114/190859422-45957f7b-486f-486d-85db-067c8c60c974.jpg)

**Comment by xmha97** [comment]
> I'm using a Xiaomi phone, too.

What's your Xiaomi phone? (Model)

**Comment by z-huang** [comment]
MI 9 with MIUI EU 12.5

**Comment by owencz1998** [comment]
No issues with samsung just a heads up 🙂

**Comment by xmha97** [comment]
> No issues with samsung just a heads up 🙂

What's your Samsung phone? (Model)

**Comment by owencz1998** [comment]
Z fold 3 dude

**Comment by xmha97** [comment]
> No issue with my Xiaomi 11T Pro

Are you using the debug version?
Is your bluetooth on when playing music?

**Comment by z-huang** [comment]
Can you try f96bbcbfe1125936fc6708d70a5e07a6f1c1fa70?

**Comment by xmha97** [comment]
Now I using this version: https://github.com/z-huang/music/actions/runs/3075547412
The problem is not solved.

**Comment by z-huang** [comment]
Is that any settings you've changed in your phones in common? Especially in the developer options.

**Comment by airon90** [comment]
> Are you using the debug version?
Is your bluetooth on when playing music?

I tested the Debug version playing music in my car, linking the phone to the car via bluetooth

**Comment by owencz1998** [comment]
I use Samsung ear buds everyday with the debug version never had that issue

**Comment by owencz1998** [comment]
Iv just looked online apparently people have had this issue and had to replace the battery have u checked to make sure all software and app updates are done and checked other music apps to see if it does the same

**Comment by airon90** [comment]
> Is there any setting you've changed in your phones in common? Especially in the developer options.

I don't think I set something particular that can change Bluetooth behaviour: in dev option I just activated USB debugging

**Comment by xmha97** [comment]
Hi @z-huang
I tested many debug versions and found out which version is causing the problem:

![IMG_20220919_033409_371.jpg](https://user-images.githubusercontent.com/23485114/190932005-7a0c6252-0c16-4840-a2e0-84e95169111d.jpg)

![IMG_20220919_033413_678.jpg](https://user-images.githubusercontent.com/23485114/190932013-d099db81-7751-463f-8cce-64af495b5dd4.jpg)
As you can see, my phone's bluetooth is on but there is no problem.

**Comment by xmha97** [comment]
# Log
(the latest debug version)
Download [logcat.zip](https://github.com/z-huang/music/files/9595554/logcat.zip)

**Comment by z-huang** [comment]
Try this: d5c2f928a18f320959ec300c9abfd029ed4060ff
It should fix the bug.

**Comment by xmha97** [comment]
> Try this: [d5c2f92](https://github.com/z-huang/music/commit/d5c2f928a18f320959ec300c9abfd029ed4060ff) It should fix the bug.

Thank you, I tested the app for one day, and the app was OK. 👍
