### ISSUE TITLE
Create own F-Droid repo 

### ISSUE THREAD

**Issue by airon90** [z-huang/music#189]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Create own F-Droid repo

### Why do you want this feature?

It would speed up the release of a new version a lot 

### Additional information

You can find how here: https://f-droid.org/en/repomaker/

**Comment by z-huang** [comment]
It requires a server and users have to add the repo manually, so I don't consider doing that.

**Comment by ronidee** [comment]
@z-huang Do you consider adding it to the regular f-droid store (not via izzysoft), perhaps once the project is in a less "unstable stage"? If not, would you mind explain the advantages of not doing so?

Kind regards
ronidee

PS: both UX and UI design of your app are really good. Do you have a donation link?

**Comment by z-huang** [comment]
Yes, I'm consider adding this app to F-Droid, and time is when I have a new icon and name for this app.
As for donation, I'll accept it once this app becomes fully ripe.

**Comment by shuvashish76** [comment]
> Do you consider adding it to the regular f-droid store (not via izzysoft)

@ronidee Now live on F-Droid: https://f-droid.org/packages/com.zionhuang.music/ 🎉 _(re-sync the repo to see updates on your F-Droid client, their website usually takes some time)_

@z-huang F-Droid badges : https://gitlab.com/fdroid/artwork/-/blob/master/badge/README.md
