### ISSUE TITLE
Playing videos not on Youtube Music(but on Youtube) causes app to crash

### ISSUE THREAD

**Issue by nikhilCad** [z-huang/music#191]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

On 0.4.0, Search "Hindi Theme Song"
Go to "Community Playlists"
Select "Back to 90's cartoon theme songs in Hindi"
Open any song
Crash

### Expected behavior

Plays normally

### Actual behavior

Crashes app

### Music version

0.4.0

### Android version

10

**Comment by z-huang** [comment]
Fixed in efb4098ef30ef833e328f6fb0b2d27a0dbe38ca9.

**Comment by nikhilCad** [comment]
Any way to generate a release apk over cloud? I dont have a pc and debug builds are slow

**Comment by owencz1998** [comment]
Apparently they brought debug section to the app but couldn't see it anywhere 😂
