### ISSUE TITLE
theme

### ISSUE THREAD

**Issue by senolfndk** [z-huang/music#198]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Can you add theme options?

### Why do you want this feature?

mp3 download speed is too slow

### Additional information

frankly, I couldn't see a new feature or anything changed in the new version

**Comment by z-huang** [comment]
Theme options already exist in previous versions. It's in the settings.

**Comment by senolfndk** [comment]
ok now i see
