### ISSUE TITLE
Refetch option crashes the app

### ISSUE THREAD

**Issue by saracenz21** [z-huang/music#199]

**Comment by z-huang** [comment]
What kind of refetch? Song, artist, album, or playlist?

**Comment by saracenz21** [comment]
App version 4.0
Android 9

**Comment by saracenz21** [comment]
Songs

**Comment by z-huang** [comment]
I can't reproduce. Please attach logs or tell me which song are you refetching.

**Comment by saracenz21** [comment]
Ok sorry for not being clear

Songs i have opened with YouTube links crashes the app

Songs which i have searched through app gets refetched

**Comment by z-huang** [comment]
Can you provide the link?

**Comment by saracenz21** [comment]
https://www.youtube.com/watch?v=W4VTq0sa9yg

**Comment by z-huang** [comment]
I'm didn't have crash. But this song can't be played because YouTube throws a error message saying "The video is unavailable."

**Comment by saracenz21** [comment]
Yes I think issue is with refetching those links. Adding it as new is fine 
Guess i have to manually do

Thank you for this wonderful app 🔥
