### ISSUE TITLE
The cover is not displayed

### ISSUE THREAD

**Issue by xmha97** [z-huang/music#200]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Play a music
Swipe up

### Expected behavior

See cover

### Actual behavior

cover is not displayed

### Screenshots/Screen recordings

![Screenshot_2022-09-21-09-17-47-812_com zionhuang music](https://user-images.githubusercontent.com/23485114/191416819-b8a1dae7-bb0c-433c-be6b-ac008864f428.jpg)

![Screenshot_2022-09-21-09-17-51-260_com zionhuang music](https://user-images.githubusercontent.com/23485114/191416832-000e0fc9-f996-4b16-9ab2-91c78db98324.jpg)

### Music version

0.4.0

### Android version

Android 12

**Comment by z-huang** [comment]
![Screenshot_2022-09-21-12-54-04-890_com.zionhuang.music.debug.jpg](https://user-images.githubusercontent.com/39427017/191417308-4a12e5cc-ba82-43c3-91b4-e812b7218e79.jpg)

I'm working fine. Are you connected to internet when playing?

**Comment by bacteriostat** [comment]
I had some older songs added to library, the first one's cover loaded while others didn't. Refreshing/Refetching  them loads the album art, also adds some more details that were previously missing.

**Comment by xmha97** [comment]
> Are you connected to the internet when playing?

No, is the cover only displayed in online mode?

**Comment by z-huang** [comment]
The cover uses cache strategy. If you have loaded the image before, it would have been cached. When you're offline, the app tries to find the cached image. The app doesn't save the thumbnail in advance.

**Comment by xmha97** [comment]
> The cover uses cache strategy. If you have loaded the image before, it would have been cached. When you're offline, the app tries to find the cached image. The app doesn't save the thumbnail in advance.

Thank you for your explanation. 🙏
You can close this issue.
