### ISSUE TITLE
Homepage suggestions not correctly fetched

### ISSUE THREAD

**Issue by airon90** [z-huang/music#202]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Just open the app and change settings about default content language and country

### Expected behavior

There should be a setting about home page data, as my phone is in Italian but I don't want Italian suggestions

### Actual behavior

I don't know where it gets suggestion: I am Italian, suggestions are about Italian music. I changed app language, default content language is set to system default (en-us) and default content country set to FI. I keep on getting Italian music as suggestions

### Music version

0.4

### Android version

MIUI 13/Android 12

**Comment by z-huang** [comment]
The data is what you see in YouTube Music web version.

**Comment by z-huang** [comment]
The results in homepage depends on YTM server. It seems that YTM gives you results based on the geographical location of your IP. So, I may not be able to fix it.

**Comment by YouSummoner** [comment]
> The results in homepage depends on YTM server. It seems that YTM gives you results based on the geographical location of your IP. So, I may not be able to fix it.

Then what exactly the region change in the app settings fo?

**Comment by z-huang** [comment]
Region and language settings change the parameter `gl` and `hl` when making request to YouTube.
