### ISSUE TITLE
Customize the share url

### ISSUE THREAD

**Issue by Bnyro** [z-huang/music#209]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I would love to have an option to choose a different URL in the settings that is gonna be used for sharing instead of the default one:
Currently the share link is redirecting directly to YouTube, using an alternative privacy respecting frontend like Invidious or [Piped](https://github.com/TeamPiped/Piped) therefore is not possible yet.

It could just be an `EditTextPreference` allowing to choose the share URL for videos:
* By default it would be the current one: `https://music.youtube.com/watch?v={videoId}`
* The preference would allow to use something like `https://piped.kavin.rocks/watch?v={videoId}` instead

### Why do you want this feature?

I don't want to use YouTube directly and for sharing I prefer using Piped, the mentioned feature would make it easier to share the link with friends or just copy it via a privacy respecting alternative frontend for YT.

### Additional information

I would love to work on this on my own, I just want to make sure before there are no complaints about adding it and that it therefore would be an accepted feature.
It would probably fit well in the privacy tab :)

**Comment by z-huang** [comment]
What about the url of artists, albums and playlists? Would you like them to be customizable as well?

**Comment by Bnyro** [comment]
Yes, that would be cool as well but I'm not sure what the best way for adding settings for it would be.
Piped and Invidious support the same paths as YouTube does too, so in theory it would be enough to only let the users customize the host, e.g. from `https://music.youtube.com/` to `https://piped.kavin.rocks/`.

**Comment by z-huang** [comment]
But for urls such as `https://music.youtube.com/browse/MPREb_hqiB0KumHYT`, `https://piped.kavin.rocks/browse/MPREb_hqiB0KumHYT` gives 404 error.

**Comment by airon90** [comment]
https://github.com/iv-org/invidious/issues/2290

**Comment by z-huang** [comment]
It seems that Piped can't handle all types of url from YouTube Music. We should better wait for it.
