### ISSUE TITLE
Allow choosing what tab to open on start of app

### ISSUE THREAD

**Issue by nikhilCad** [z-huang/music#212]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Allow to choose whether to open "Home", "Songs" or other tab as first tab on start of app.

### Why do you want this feature?

Already have many songs in "Songs" tab, don't need Home and Explore everytime app opens but only when finding something new

**Comment by owencz1998** [comment]
He's added this in the debug for next release
