### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by owencz1998** [z-huang/music#219]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Could the changelog also be added into the about section 

### Why do you want this feature?

Just so I can see what been added anytime and not just in the updater.

**Comment by z-huang** [comment]
I think that's the responsibility of the updater. I don't want this to be hardcoded in the apk.

**Comment by airon90** [comment]
I don't see changelog in F-Droid. Is it okay?

**Comment by z-huang** [comment]
Me either. I don't know why. Maybe I should contact someone responsible for that.

**Comment by airon90** [comment]
Maybe @IzzySoft knows why

**Comment by IzzySoft** [comment]
Yes, he knows. Nobody told him to enable them when they were added :stuck_out_tongue:

**Comment by z-huang** [comment]
@IzzySoft How to enable changelog?

**Comment by IzzySoft** [comment]
It is enabled now – I have to do that in the config on my end and did so right when writing above comment. Should be visible now, [see here](https://apt.izzysoft.de/fdroid/index/apk/com.zionhuang.music) – and the Android client should show it once it refreshed the index.

**Comment by z-huang** [comment]
I saw it. Thank you very much!
