### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by airon90** [z-huang/music#22]
How to translate the app?

**Comment by z-huang** [comment]
The app currently provide language in English and Traditional Chinese. Since the project isn't stable yet, the texts tend to be modified frequently. Once the project become stable, I'll add information about how to contribute translation in README.

**Comment by mondlicht-und-sterne** [comment]
> How to translate the app?

I want to translate, too ;)

**Comment by z-huang** [comment]
> The app currently provide languages in English and Traditional Chinese. Since the project isn't stable yet, the texts tend to be modified frequently. Once the project become stable, I'll add information about how to contribute translation in README.

I originally planned to allow translations after the app becomes stable. But maybe this can be done in the meantime so that the app can become more friendly to global users. Therefore, I'll organize the `string.xml` file a bit and add instruction for contributions in `README.md`.

Also, I'm glad that you guys would like to translate the app.

**Comment by mondlicht-und-sterne** [comment]
@z-huang 

I don't understand the repo fork and then create a pull request.

Can I deposit the strings file (if I find it) on github and you copy it to yourself?

It would be easier if you put it on crowdin or weblate, I'm not on transifex anymore.

**Comment by z-huang** [comment]
> Can I deposit the strings file (if I find it) on github and you copy it to yourself?

This works. The location is `app/src/main/res/values/strings.xml`. Note that lines with `translatable="false"` can be ignored.

Crowdin is more easier for translating, but I encounter problem that the project name is already used. I have to think of a better name for this app first. (#35)

**Comment by airon90** [comment]
> This works. The location is app/src/main/res/values/strings.xml. Note that lines with translatable="false" can be ignored.

How to upload a translated file? Should it be named string-XX.xml (as XX is the language code) or something similar?

**Comment by z-huang** [comment]
It should be place in `app/src/main/res/values-{language code}-r{region code}/strings.xml`. It will be good if you create a pull request. But if you don't know how to, just upload the file anywhere and tell me the language and region.

**Comment by airon90** [comment]
App description on F-Droid should me make translatable too ;) Anyway, #36

**Comment by z-huang** [comment]
Added translation instruction in README.
