### ISSUE TITLE
Fetching an artist doesn't work

### ISSUE THREAD

**Issue by airon90** [z-huang/music#222]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Install Music v0.3.3 or lower
2. Have songs in library
3. Upgrade to v0.4
4. Go to Artist page
5. Choose an artist and press three-dot menu of that artist
6. Press Refetch

### Expected behavior

It should fetch all songs from the artist

### Actual behavior

Nothing happens

### Music version

0.4

### Android version

MIUI 13/Android 12

**Comment by z-huang** [comment]
Only YouTube artists can be refetched. If you upgrade from 0.3.3, the original artists are converted to local artists. You should refetch songs first to update the artists to YouTube artists.

**Comment by z-huang** [comment]
> It should fetch all songs from the artist

No, "refetch" means refetching the data of the artist.

**Comment by airon90** [comment]
Ah, I thought it would have refetched all songs by the artist. Closing
