### ISSUE TITLE
Improve landscape mode

### ISSUE THREAD

**Issue by xmha97** [z-huang/music#227]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

- Open the app in landscape mode

### Expected behavior
Move bottom navigation bar to left on landscape mode (like the GitHub app)

![Screenshot_2022-09-25-15-08-53-874_com.github.android.jpg](https://user-images.githubusercontent.com/23485114/192141607-200afe07-6ebb-47fd-a95c-45a8b35f2058.jpg)

### Actual behavior

-

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/23485114/192141398-bfcc00cd-9eba-4e4b-99bf-b84bf814c4c5.mp4

![Screenshot_2022-09-25-15-06-32-669_com zionhuang music](https://user-images.githubusercontent.com/23485114/192141422-537ac9ae-1053-479b-ab2b-9a5f4207ca8d.jpg)

![Screenshot_2022-09-25-15-06-37-422_com zionhuang music](https://user-images.githubusercontent.com/23485114/192141423-9dd3d1f0-d969-4a59-865e-8131c50c15c7.jpg)

### Music version

0.4.1-stable

### Android version

Android 12

**Comment by z-huang** [comment]
Thanks for reminding. Landscape mode experience is really bad currently. I will fix it.

**Comment by xmha97** [comment]
A idea for extended buttom player:
![Screenshot_2022-10-08-03-14-59-480_code name monkey retromusic](https://user-images.githubusercontent.com/23485114/194676009-ddbc04eb-e25c-40da-824f-d555fdd85567.jpg)
https://github.com/RetroMusicPlayer/RetroMusicPlayer
