### ISSUE TITLE
Bug in playing songs 

### ISSUE THREAD

**Issue by airon90** [z-huang/music#23]
If you press on a song in the Songs section, the app starts playing that song. If you press on a song in the Artists or in the Playlists section the app will not load the song

**Comment by z-huang** [comment]
This commit solved the bug of not playing songs in the artists fragment: 9eb8f6cbb234314d9e6e13e6810342313d4dfcbf
However, playlist songs should work fine as I've tested.
Can you try the debug apk in the GitHub Action artifacts of the latest dev branch commit?

**Comment by airon90** [comment]
I am sorry, it worked in playlists so I close this bug report. Thank you for your work!
