### ISSUE TITLE
Some small issues

### ISSUE THREAD

**Issue by xmha97** [z-huang/music#233]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

*

### Expected behavior

General

### Actual behavior

Gerenal

### Screenshots/Screen recordings

![Screenshot_2022-09-25-23-50-52-184_com zionhuang music](https://user-images.githubusercontent.com/23485114/192163607-c2a6d5b2-1744-423a-b824-4f2fb4d211c6.jpg)

### Music version

0.4.1-stable

### Android version

Android 12

**Comment by xmha97** [comment]
Also on home tab, arrows is dark (on dark theme)
![Screenshot_2022-09-26-01-17-27-544_com.zionhuang.music.jpg](https://user-images.githubusercontent.com/23485114/192167041-1998000c-c730-4f94-92c8-381ece5c54d9.jpg)

**Comment by z-huang** [comment]
> ### Expected behavior
> General
> ### Actual behavior
> Gerenal

What do you mean?

> Also on home tab, arrows is dark (on dark theme)

Fixed.

**Comment by xmha97** [comment]
> What do you mean?

General typed wrong: ~~Gerenal~~

**Comment by airon90** [comment]
> "General" is typed incorrectly: Gerenal

It will be fixed with #241

**Comment by z-huang** [comment]
Oops! Sorry!

**Comment by z-huang** [comment]
Fixed.
