### ISSUE TITLE
Tap Cover -> Play/Pause

### ISSUE THREAD

**Issue by xmha97** [z-huang/music#235]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Play/Pause on tapping the cover (like AntennaPod)

https://user-images.githubusercontent.com/23485114/192247411-2d0c2280-44c2-4c76-88c9-4e4cd43d1bdc.mp4

### Why do you want this feature?

Better user experience

### Additional information

Also add material ripple click effect on tapping on cover (like video)

**Comment by z-huang** [comment]
No. I'll leave it for other feature.
