### ISSUE TITLE
Option to download music to the `Music/` folder

### ISSUE THREAD

**Issue by ThatOneCalculator** [z-huang/music#238]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Title

### Why do you want this feature?

The option to have songs downloaded in the `Music/` folder would be great, especially if I want to play the songs I download in other apps or migrate my songs out of this app.

**Comment by z-huang** [comment]
Duplicate of #177

**Comment by ThatOneCalculator** [comment]
@z-huang not quite. This links back to #117 , but that doesn't properly do what this issue (or #177 / #137 ) asks for.

**Comment by z-huang** [comment]
You're asking for another place to save downloaded songs, exactly #177 and #137. If you're asking for "automatically export to custom folder", you're right to link #117.
