### ISSUE TITLE
Option for changing the app language within app settings

### ISSUE THREAD

**Issue by aaj013** [z-huang/music#250]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

An option for changing the app language within the app General settings would be nice. Similar option is available in [Newpipe](https://github.com/TeamNewPipe/NewPipe).

<img src="https://user-images.githubusercontent.com/5847582/192955259-21299ce2-b6a5-4faf-a6a1-10d145aec764.jpg"  width="350" />

### Why do you want this feature?

We can choose a different language specifically for the app than the system language.

**Comment by z-huang** [comment]
Sorry, implementing this feature causes other troubles, which is costly, so I decided to deprecate it.

**Comment by Deemitry88** [comment]
So how can I change my app language ? I don't like the french translation and prefer to have th app in english
