### ISSUE TITLE
Music recommendation algorithm

### ISSUE THREAD

**Issue by CuongBa956** [z-huang/music#251]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I hope the app will have a music recommendation algorithm.  for example from songs i add to my library or songs i listen to many apps can suggest me songs like that or maybe i will like on home page

### Why do you want this feature?

I think it will increase the user experience of the app. I think this is a difficult thing but I hope this feature will appear

**Comment by z-huang** [comment]
It's really difficult for me. Honestly, I have no idea if it's possible.

**Comment by CuongBa956** [comment]
thanks also i think its a hard thing especially for such a small project with only a single developer

**Comment by CuongBa956** [comment]
thanks also i think its a hard thing especially for such a small project with only a single developer

**Comment by LuanRT** [comment]
> It's really difficult for me. Honestly, I have no idea if it's possible.

Hey @z-huang, I noticed your InnerTube client [uses a hard-coded `visitorData` token](https://github.com/z-huang/music/blob/aaf4f3e3e827bb808a57071d2d7f18b07e571e61/innertube/src/main/java/com/zionhuang/innertube/models/YouTubeClient.kt#L50).  Note that this specific token is what allows InnerTube to provide algorithmic recommendations for a user, even if they are not signed in. It sort of works like a session, so to implement this you'd have to either generate the visitor data token (it is just a base64d protobuf that consists of a timestamp and a random 11 characters string, [this](https://github.com/LuanRT/YouTube.js/blob/95e047974507d503ea4f2f30a2c3c58dbdb6c455/src/core/Session.ts#L145) is how I generate it in my library) or grab it from YouTube Music's service worker endpoint (https://music.youtube.com/sw.js_data), store it somewhere and use it for all requests. 

That should be enough to make the home feed, up next, related, etc adapt to one's music taste.

**Comment by z-huang** [comment]
Thanks! However, is a unique `visitorData` enough for the trick? I saw that there are also `log_event` and `watchtime` API endpoints.

**Comment by LuanRT** [comment]
> Thanks! However, is a unique `visitorData` enough for the trick? I saw that there are also `log_event` and `watchtime` API endpoints.

Yes, playback tracking can make it better. But you *do not* have to ping the `watchtime` endpoint  (`api/stats/watchtime`), this endpoint in particular is used to record watch time after playback tracking is initialized with `api/stats/playback`, which is what adds songs/videos to a user's watch history ([like we do here](https://github.com/LuanRT/YouTube.js/blob/2f56c15ecc151ec8d0d764b7c3a4dcb10ec8f6e1/src/parser/youtube/VideoInfo.ts#L191)), and interestingly, also tunes recommendations for unauthenticated users. You also do not have to ping the `log_event` endpoint, it is used for telemetry.

**Comment by z-huang** [comment]
Thanks for your expert explanation! I'll generate a random `visitorData` for each user.
