### ISSUE TITLE
Italian changelog on F-Droid doesn't handle HTML tags

### ISSUE THREAD

**Issue by airon90** [z-huang/music#256]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Open F-Droid
2. Search for Music

### Expected behavior

Changelog should not show html tags

### Actual behavior

<br> and <b> are shown as they are

### Music version

0.4.1

### Android version

MIUI 13/Android 12 with F-Droid 1.15.2 and Music 0.4.1

**Comment by z-huang** [comment]
It works in IzzyOnDroid website and [Droid-ify](https://github.com/Iamlooker/Droid-ify), but not in F-Droid app. 🙁
Try to remove `<br>` in the changelog and see if it works.

**Comment by airon90** [comment]
It doesn't even read <b> tag. I suppose all HTML tags are not parsed by F-Droid

**Comment by z-huang** [comment]
I hope that can be fixed when I add the app to F-Droid repo.
