### ISSUE TITLE
Song data are not correctly sent via bluetooth

### ISSUE THREAD

**Issue by airon90** [z-huang/music#26]
![20220414_155936_041143](https://user-images.githubusercontent.com/139841/163418334-6c600dba-79a6-4c81-948d-76e30500d61e.jpg)

I took a picture of what I see on the app and what I see on my car's screen. The app should send data about artists and album, instead those fields are empty.

I am using 0.13-beta via F-Droid, so it may be fixed in 0.20-dev

**Comment by airon90** [comment]
@z-huang On latest Music Debug, the name of the artist is shown but the album title is not shown. Instead, "unknow" (sic) is shown.

**Comment by z-huang** [comment]
Can you test 7fd4f782b2d479f0172d7f130a785394f8befcdb? I don't have the environment to test.

**Comment by airon90** [comment]
It works! Thank you! 💖
