### ISSUE TITLE
Aesthetic Changes

### ISSUE THREAD

**Issue by Black-StellarSpectrum** [z-huang/music#261]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### **Screenshot describes it well:**
**Now Playing expanded form**

**Current look:**
![Screenshot_20221002-191800_Music](https://user-images.githubusercontent.com/79910450/193459328-8463abf0-1386-4baf-9e78-42eb21736273.png)

**New look I think would look good:**
![20221002_195605](https://user-images.githubusercontent.com/79910450/193459369-b0533e58-b271-4e3d-86c9-bfd635c26eab.png)

### Why do you want this feature?

I think it'll make the app look much better and improve the aesthetics!

**Comment by z-huang** [comment]
I'm currently doing player redesign. You can try the latest debug apk.

**Comment by Black-StellarSpectrum** [comment]
> I'm currently doing player redesign. You can try the latest debug apk.

Where can I download the debug version?

**Comment by z-huang** [comment]
See README.
