### ISSUE TITLE
Replay Gain Normalization

### ISSUE THREAD

**Issue by Alliba** [z-huang/music#262]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Some songs are louder than others in a playlist. Replay Gain Normalization can be used to make them equally loud

### Why do you want this feature?

Variable loudness is annoying and some songs are nor even audible unless you manually pump up volume for that specific song only

**Comment by z-huang** [comment]
Duplicate of #24
