### ISSUE TITLE
Icon is just a white space without music notes.

### ISSUE THREAD

**Issue by muichunlim** [z-huang/music#263]
This happened when I install music on my oneplus phone.

![Screenshot_2022-10-02-10-27-07-77_b783bf344239542886fee7b48fa4b892](https://user-images.githubusercontent.com/55557915/193467617-a48cb680-d61b-4445-a65f-2df7b159b9b7.jpg)

**Comment by owencz1998** [comment]
Duplication of #230

**Comment by z-huang** [comment]
Duplicate of #230
