### ISSUE TITLE
Newpipe Extractor broke, No songs playing

### ISSUE THREAD

**Issue by nikhilCad** [z-huang/music#27]
TeamNewPipe/NewPipe#8202

Update extractor after this issue in main Newpipe gets fixed.

**Comment by nikhilCad** [comment]
Now fixed in Newpipe Extractor

**Comment by z-huang** [comment]
Noticed. Working to release a hotfix version.

**Comment by z-huang** [comment]
Release 0.2.1-beta is released.
Closing the issue.
