### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by JPGuillemin** [z-huang/music#277]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Note : when no network (ie : plane mode) :

- Playing a 100% downloaded/cached album should be possible 
- "Home" and Artist tabs should be hidden or disabled.
- "Songs" tab should show only cached songs
- "Albums" tab should show only fully cached albums

### Why do you want this feature?

Without this feature the user will get many warnings and will think that the cache is useless

**Comment by z-huang** [comment]
> Playing a 100% downloaded/cached album should be possible

Playing a 100% downloaded/cached song is possible.

> "Home" and Artist tabs should be hidden or disabled.

I'll make artists browsable, at least being able to view their songs in the library. (#246)

> "Songs" tab should show only cached songs

I'll still show all songs. You can find downloaded songs in "Downloaded songs" in playlist tab. As for 100% cached songs, I'm finding if it's possible to convert the cache file directly into downloaded file. Then it will be fast to download cached songs.

> "Albums" tab should show only fully cached albums

All albums will show up and be browsable. If possible, I'll add a downloaded badge if all album songs are downloaded.

**Comment by JPGuillemin** [comment]
ok :)

**Comment by xmha97** [comment]
Add a banner top of app (like Google Chrome app) for the offline mode:
![Screenshot_2022-10-08-03-06-54-330_com android chrome](https://user-images.githubusercontent.com/23485114/194675807-e2ca1f87-bb3f-4ca8-9fcb-639d1f139a51.jpg)

**Comment by z-huang** [comment]
> Add a banner top of app (like Google Chrome app) for the offline mode

I may show an offline icon in the center of the screen instead.

This issue is covered by #276 and #246.
