### ISSUE TITLE
Add menu list as option for albums or artists

### ISSUE THREAD

**Issue by 92flash** [z-huang/music#28]
I was sondering if it also might be possible to implement the three dotted menu, you can click on at individual songs, at albums and channels.
![signal-2022-04-15-13-16-57-690](https://user-images.githubusercontent.com/76122930/163578517-c2ad982e-0b95-449c-a2dc-104ec21ae8ab.jpg)

**Comment by z-huang** [comment]
Yes, three-dot menu isn't implemented for albums, playlists and channels. The feature will be added in the future.
