### ISSUE TITLE
Add close button to notification bar

### ISSUE THREAD

**Issue by xmha97** [z-huang/music#280]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

![Screenshot_2022-10-08-03-54-56-795_code name monkey retromusic](https://user-images.githubusercontent.com/23485114/194678243-934db4c9-cc39-4e7a-b05e-b3f3e0e992bd.jpg)
https://github.com/RetroMusicPlayer/RetroMusicPlayer

### Why do you want this feature?

Close player from notification bar

**Comment by z-huang** [comment]
There's no space to add this button. Instead, you can pause the music and swipe away the notification.
