### ISSUE TITLE
Add this app to default music apps

### ISSUE THREAD

**Issue by xmha97** [z-huang/music#281]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Hi, please add this app to default music apps.
![Screenshot_2022-10-08-04-14-20-900_com android settings](https://user-images.githubusercontent.com/23485114/194679027-f6bbe755-758a-4741-aeb9-258bbdc5f8e7.jpg)

### Why do you want this feature?

When I press the play button on my smart watch or Bluetooth hands-free, the default player opens on my mobile and the content I don't like is played.

**Comment by z-huang** [comment]
But this app doesn't support local files yet. This will be added after #3.
