### ISSUE TITLE
Add Shuffle FAB (floating action button)

### ISSUE THREAD

**Issue by xmha97** [z-huang/music#282]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Please add Add Shuffle FAB (floating action button)
Only on the "Songs" tab.

![Screenshot_2022-10-08-04-35-19-465_code name monkey retromusic](https://user-images.githubusercontent.com/23485114/194680168-d4b2a36c-20ad-4cb6-b69e-1417aa84ee95.jpg)
https://github.com/RetroMusicPlayer/RetroMusicPlayer

### Why do you want this feature?

Shuffle play is a mode of music playback in which songs are played in a randomized order that is decided upon for all tracks at once.

**Comment by z-huang** [comment]
Already here.

<img width="317" src="https://user-images.githubusercontent.com/39427017/194682354-75c72cc4-5adb-45d6-bb6b-52e4322e3325.png">
