### ISSUE TITLE
allow upgrading debug apk

### ISSUE THREAD

**Issue by JPGuillemin** [z-huang/music#287]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

To keep database and especially downloaded content between debug apk versions : upgrading should be possible.

As for now you have to uninstall previous apk , so loose all data when switching to a new debug apk. (Xiaomi 12)

Backuping/restoring database and copying the whole "files" folder is a pain.

### Why do you want this feature?

It makes it simpler to live with debug apk as main music app .

**Comment by z-huang** [comment]
It seems like different builds have different signing keys, so I have to generate a debug key for it. Also, as a reminder, you should know that sometimes different debug versions are incompatible and you won't be able to open the app after upgrade without clearing app data. Therefore, you should make backup in case.

**Comment by JPGuillemin** [comment]
Ok :)

**Comment by owencz1998** [comment]
A shame about not able to implement a beta setting in the app to get updates to any commits but at least we now have the backup and restore😄

**Comment by xmha97** [comment]
https://github.com/z-huang/music/issues/63

**Comment by owencz1998** [comment]
Right I know that as that's my opened issue 😂
