### ISSUE TITLE
Low resolution media art

### ISSUE THREAD

**Issue by MehediHasanJihad** [z-huang/music#291]
In the notification and quick settings panel the media player's album arts are shown in very low resolution. Can you fix it? And overall its really great music streaming app. Really appreciate it man!

**Comment by z-huang** [comment]
Are you using Android 13? It's probably a duplicate of #244.

**Comment by MehediHasanJihad** [comment]
Yes, I'm currently using Android 13

**Comment by z-huang** [comment]
Duplicate of #244
