### ISSUE TITLE
background playback is broken

### ISSUE THREAD

**Issue by JPGuillemin** [z-huang/music#296]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

background playback is broken on latest debug apk.

### Expected behavior

Should keep playing when app in background 

### Actual behavior

Like unregistered YouTube apk.

### Music version

latest debug

### Android version

12

**Comment by owencz1998** [comment]
Also happens when listening to a song then go to the app settings haha

**Comment by z-huang** [comment]
Oops, sorry!
