### ISSUE TITLE
No song

### ISSUE THREAD

**Issue by hands8142** [z-huang/music#30]
![Screenshot_20220417-215829_Music](https://user-images.githubusercontent.com/46277532/163715438-6eb613dd-f9ad-4e68-95ca-e81a1ecbd251.png)
There's no song. What's the problem? I'm using the latest version. I live in Korea. Is it a problem in Korea?

**Comment by hands8142** [comment]
Android version: 12
Music version: 0.2.1-beta

**Comment by nikhilCad** [comment]
You go to Explore tab and search for songs. There is add to library button
( the + button) to add them to first tab.

**Comment by hands8142** [comment]
I'm sorry. I didn't know how to use it.

**Comment by nikhilCad** [comment]
UI is little confusing especially for first time users. I think developer
said they will change that
