### ISSUE TITLE
Stats for nerds

### ISSUE THREAD

**Issue by owencz1998** [z-huang/music#304]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

A option in the settings to enable stats for nerds like ytmusic.

### Why do you want this feature?

Just a handy feature to have.

**Comment by z-huang** [comment]
Coincidentally, it's what I'm working on today!😆 But I'm not sure when it will take. Also, the cache feature isn't fully implemented. I have to deal with different audio quality.
Warning: make sure to backup your data after updating debug apk since database structure may be changed.

**Comment by owencz1998** [comment]
Awsome Haha 😂that's grate and no problem I'll do that now and innertune is a grate name by the way 👌

**Comment by owencz1998** [comment]
Nice work bro 👏

**Comment by owencz1998** [comment]
Just one thing does music have to be redownload to get the stats as only working for streaming dude

**Comment by z-huang** [comment]
Thanks for the spot. Fixed. Stats will be automatically fetched when internet available. But the refetched info may be inconsistent with the downloaded song if you change audio quality settings between downloading and refetching. To assure you get the right info, redownload the song.

**Comment by owencz1998** [comment]
No problem and that's all good I don't intend to change audio as I keep it as the max 👌
