### ISSUE TITLE
Backups ".db"

### ISSUE THREAD

**Issue by Eri1320** [z-huang/music#308]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Support for restoring backups of ".db" files, in case I want to switch from another application to "music" without having to put all my favourite songs back again.

### Why do you want this feature?

I currently use two applications, and I want to switch to Music, but the backup is not compatible because it is ".db".

**Comment by z-huang** [comment]
It's never possible to import the backup of one app to another app. The database structure is different.

**Comment by Eri1320** [comment]
In any case, thanks for explaining it and creating such a wonderful application :3
