### ISSUE TITLE
Slide category bar

### ISSUE THREAD

**Issue by owencz1998** [z-huang/music#312]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Can this category bar that slides be added for a quicker way to discover music.

### Why do you want this feature?

Easier and quicker to find different kinds of music.

### Additional information

![Screenshot_20221016_084619](https://user-images.githubusercontent.com/96526481/196024378-c13ebd9d-53a0-4d54-86d3-e1ecdbaf436e.jpg)

**Comment by z-huang** [comment]
I afraid not. I'm using web version of YTM to get feeds, and web version doesn't provide such option.

**Comment by z-huang** [comment]
By the way, I'm going to release the new version today. Is there any bug?

**Comment by airon90** [comment]
@z-huang ping me for changelog

**Comment by z-huang** [comment]
You can do it now.

**Comment by owencz1998** [comment]
No problem and haven't had any bugs so far mate will let u know ASAP if there is dude
