### ISSUE TITLE
Cache settings

### ISSUE THREAD

**Issue by xmha97** [z-huang/music#315]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Go to app settings
2. Select Cache
3. Crash

### Expected behavior

Show cache settings

### Actual behavior

Crash app

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/23485114/196034636-3ffdb76f-dd62-4da2-9095-3e843933b267.mp4

### Music version

0.4.2

### Android version

Android 12

**Comment by z-huang** [comment]
The solution is to play a song first for the cache to be created. I should catch the error.
