### ISSUE TITLE
Allow for 3rd party app equalization

### ISSUE THREAD

**Issue by Nogooduser** [z-huang/music#33]
I use an equalizer app (Poweramp Equalizer) to make my headphones sound a bit better and sadly while I was testing music I discovered poweramp can't detect it as a music player.

This also happened with other equalizers I tested (Wavelet, etc.) so it's definitely a problem with how music is broadcasting its music notification that's not allowing 3rd party apps to detect it as a music player. 

I'm not sure about the details myself but I know this is possible to do as many other music apps properly show up. It would be great if this could be fixed so I could use music while adjusting my headphones to sound the way I want to.

**Comment by z-huang** [comment]
I'm wondering why Last.fm app can't detect my app playing song, too. I'll take a look at other apps to see what configuration I'm missing.
