### ISSUE TITLE
Rename the application

### ISSUE THREAD

**Issue by kayoo123** [z-huang/music#35]
Hello
First of all, thank you for tour apps that meets all my needs.
I can't help but recommend it to others.

I would like to know if you plan to change the name of the application "Music" because it seems too generic.

Thank you in advance for your feedback and once again thank you for your great work

**Comment by z-huang** [comment]
I'm still thinking what should I name the app, but yes I will rename the app.
Thanks for your appreciation and I'm still improving the app to make it better.😊

**Comment by Elaborendum** [comment]
I don't think you should close the issue until there's a new name chosen. Unless there is, but it's still not showing.

**Comment by z-huang** [comment]
Any suggestion is welcome!

**Comment by ArjixWasTaken** [comment]
Hmm, smth like ShadyPlayer would be funny

Anyways, here is a suggestion: TelioPlayer

Telio is a Greek word (τέλειο) which means perfect

**Comment by airon90** [comment]
It doesn't use NewPipe anymore in innertube branch

**Comment by z-huang** [comment]
The name is so generic. People won't what you mean when metioning "Music".

**Comment by xmha97** [comment]
> The name is so generic. People won't what you mean when metioning "Music".

Ok, choose a name for this app.
But I prefer "Music" only for the launcher.

**Comment by ArjixWasTaken** [comment]
> > The name is so generic. People won't what you mean when metioning "Music".
> 
> Ok, choose a name for this app. But I prefer "Music" only for the launcher.

that is something that you can change on your end, a lot of launchers allow renaming apps

**Comment by Pentaphon** [comment]
> The name is so generic. People won't what you mean when metioning "Music".

Your name is z-huang so call it:

1) ZMusic
2) MuZic

**Comment by z-huang** [comment]
> Your name is z-huang so call it:
> 1. ZMusic
> 2. MuZic

I've thought of "Muzic", but found there are already some projects with this name. Actually, I plan to name the app InnerVoice, in correspond with the core innertube library. Also, the name is a music term I learned when I learned piano. But I haven't come up with an icon with it.😅

**Comment by Pentaphon** [comment]
> Actually, I plan to name the app InnerVoice, in correspond with the core innertube library.

That makes it sound like another kind of app like a voice recorder or a voice to text app. I would go with InnerMusic instead. Or InnerPlayer. 

Wait, I got it! How about InnerTUNE? As in song aka tune aka music? It even sounds close to Innertube but describes the "tunes" you play from YouTUBE music. 

Innertune FTW.

**Comment by ArjixWasTaken** [comment]
inb4 apple tells us that iTunes meant inner tunes, so they sue

**Comment by z-huang** [comment]
How about InnerSound?

**Comment by ArjixWasTaken** [comment]
How about InnerPeace?

![](https://media.tenor.com/yUqKY2BlKvcAAAAC/wheeze-laugh.gif)

**Comment by ArjixWasTaken** [comment]
> > inb4 apple tells us that iTunes meant inner tunes, so they sue
> 
> Nah, it's too different for that to be a thing. 
> 
> > How about InnerSound?
> 
> That's ok, I guess, but I think Innertunes pairs better with the original Innertube project. 

I was memeing ofc

**Comment by Pentaphon** [comment]
Memes aside, @z-huang I think InnerTunes is the best option so far because:

1) It is easy to say. Rolls off the tongue. 
2) It refers to the Innertube project but also refers to music.
3) Its unique enough to google and find immediately. 
4) No other projects or even google results seem to use the name.
5) The name is not too long or short.
6) You should take it before other projects steal the Inner-something name for their own innertube music player.

**Comment by z-huang** [comment]
Okay, I'll take InnerTune. (without the 's')

**Comment by z-huang** [comment]
As for the new icon, I'll wait for a light bulb to go off in my head.

**Comment by Pentaphon** [comment]
Let's use this issue to ask people if they want to generously contribute an icon for Innertune!

https://github.com/z-huang/music/issues/305

**Comment by airon90** [comment]
@z-huang In order to completely rename the app you should rename the GitHub repo too and keep z-huang/music as redirect

**Comment by z-huang** [comment]
Yes, it's something I will do.
