### ISSUE TITLE
When shuffle, ongoing song should be the first in playlist

### ISSUE THREAD

**Issue by airon90** [z-huang/music#37]
If you play a song among others and you shuffle the playlist, the ongoing song should be the first of the list.

**Comment by z-huang** [comment]
I'm thinking removing the shuffle button in the player. There are already shuffle buttons for library songs, artist songs and playlist songs. Moreover, YouTube radio is giving you random songs. Therefore, shuffle button is not necessary.

**Comment by airon90** [comment]
What if I choose a list of songs to be played? If you remove the button I cannot shuffle the list, unless I create a playlist and play it with shuffle button

**Comment by z-huang** [comment]
Okay, I reserved shuffle feature.
