### ISSUE TITLE
App crashes when finding songs

### ISSUE THREAD

**Issue by airon90** [z-huang/music#38]
App crashes when I find some song in the first section, ordered by name, and I quickly move the right bar, maybe because I have 2000+ songs in my library.

**Comment by airon90** [comment]
How can I produce a log?

**Comment by myxor** [comment]
Can cornfirm the crash while having an empty library.

**Comment by airon90** [comment]
@z-huang
Here is my [log.txt](https://github.com/z-huang/music/files/8590978/log.txt)

**Comment by z-huang** [comment]
Thanks, this is useful.

**Comment by z-huang** [comment]
I should catch this error.
BTW, this should happen in the explore section, not the songs section, right? The songs section doesn't fetch suggestions online.

**Comment by z-huang** [comment]
@myxor You can try the debug version of this commit: 7e0fe088a69c546aee76eb35337ea05a4b18ce65. This should fix the crash.

**Comment by z-huang** [comment]
@airon90 Try this commit 1c918333cdeb33b4c03843be3134569779bd39ab.

**Comment by airon90** [comment]
I added 152 songs and that commit seems to fix both #38 and #47

**Comment by z-huang** [comment]
Transfering data is waiting to be implemented.
I'll close the two issues.
