### ISSUE TITLE
Small bugs

### ISSUE THREAD

**Issue by VN0** [z-huang/music#4]
Hello! This is very useful and cool app, i am using it with pleasure. Thanks.
I found some bugs:
1) Sometimes the application crashes, something to do with saving the track and switching the Explore and Songs section
2) Timer bugs, sometimes it displays the time incorrectly and freezes
3) Text bugs, quite rare, but sometimes the title of the track is shifted

![YG9CXmWNJbY](https://user-images.githubusercontent.com/37180264/155294512-1b0b8c42-54a5-4d4b-85a2-a8c842dff36c.jpg)
![Itofm6dsjng](https://user-images.githubusercontent.com/37180264/155294522-0d332571-7b99-4d1a-a246-abe4b98717ec.jpg)
![2mI2xplZzhY](https://user-images.githubusercontent.com/37180264/155294533-6c3b2c0b-db07-44e3-a857-8cec25854109.jpg)

P.S. Some wishes)
1) Make an equalizer and theme customization
2) You can also make a registration system for saving tracks and the ability to use your audio library on different devices
Thanks again)

**Comment by z-huang** [comment]
Thanks for the positive feedback!😃

Please first check if you are using the latest vesion (0.1.3-beta). If the bugs still occur, can you specify more about how to produce them, or paste the log when the app crashed?

The new features requested, which are an equalizer, theme customization and saving tracks for the next time you open the app, are planned to be implemented. As for the ability to use the audio library on different devices, do you mean exporting and importing the library or syncing? The former  would be easier than the latter as that won't need an online server.

**Comment by z-huang** [comment]
Idle for too long, close the issue.
