### ISSUE TITLE
[FEATURE] Main home page

### ISSUE THREAD

**Issue by owencz1998** [z-huang/music#43]
[FEATURE] can u add a main home page with charts and what not with the search bar on the same page :) brilliant app 👏 

**Describe the feature you'd liketo see added*
A short description of the feature, and what it would accomplish.

**Additional context**

**Comment by z-huang** [comment]
What kind of the search bar do you mean? A search icon in the app bar to be clicked and expand like YouTube?

**Comment by owencz1998** [comment]
Yeah can do mate any is perfect also woke up this and now when trying to load the app it freezes and won't let me on it 😥

**Comment by z-huang** [comment]
Sorry, I can't understand your English.😥 Can you write in more detail?

**Comment by owencz1998** [comment]
Basically when loading up the app can u add the home page like YouTube music with the new charts and what not and the search bar on top of that page and also when you have downloaded music the app no longer works it just shuts down again.

**Comment by z-huang** [comment]
Charts will be added after the modification of NewPipe Extractor. See comments in #3.

> when you have downloaded music the app no longer works it just shuts down again.

In my phone, I didn't have this bug. Can you create an issue for this and provide logs?
