### ISSUE TITLE
[FEATURE] Add phone screenshot in Italian

### ISSUE THREAD

**Issue by airon90** [z-huang/music#44]
I cannot upload them in Fastlane directory so please I beg you to upload them for me. Thank you very much!

![1651305217495](https://user-images.githubusercontent.com/139841/166097127-19d26b94-f429-41cf-9082-49a6d07a3f3c.jpg)
![1651305217511](https://user-images.githubusercontent.com/139841/166097129-c2f2be6b-c559-494d-bb0d-3a326d8fc61b.jpg)
![1651305217526](https://user-images.githubusercontent.com/139841/166097131-2cd8a5f7-8514-41d2-b443-e0e628d7cefa.jpg)
![1651305217538](https://user-images.githubusercontent.com/139841/166097132-31c863e6-0f85-4101-8336-5e62fb3e9c28.jpg)
![1651305217551](https://user-images.githubusercontent.com/139841/166097133-0164504c-223b-406c-9a0f-a8b2b0e90ebd.jpg)
![1651305217561](https://user-images.githubusercontent.com/139841/166097134-40d53634-2edd-4a43-9546-8a7a7b059926.jpg)
![1651305217573](https://user-images.githubusercontent.com/139841/166097135-5147f414-2dd4-4474-bdd5-9b0f7345b9f2.jpg)

**Comment by z-huang** [comment]
Sure. Thank you.

**Comment by airon90** [comment]
@z-huang

**Comment by airon90** [comment]
That's okay :)

**Comment by z-huang** [comment]
Done!
