### ISSUE TITLE
App icon not loaded 

### ISSUE THREAD

**Issue by anujithpp** [z-huang/music#464]
![IMG_20221205_223329.jpg](https://user-images.githubusercontent.com/106502495/205697912-5c27dda4-3d36-4eae-abfc-e56ee4749259.jpg)

**Comment by z-huang** [comment]
Duplicate of #230

**Comment by ShareASmile** [comment]
Try steps given in this comment if that helps:
https://github.com/z-huang/InnerTune/issues/230#issuecomment-1327660351
