### ISSUE TITLE
[BUG] Searching a song crashes

### ISSUE THREAD

**Issue by airon90** [z-huang/music#47]
**Describe the bug**
I opened the app, looked for the title of a song in my library and it crashed after typing 3 letters. 2k+ songs in library

**Information:**
 - Device: Xiaomi Redmi Note 8T
 - Android version: MIUI EU 12.5.2
 - Music version: F-Droid latest

**Additional context**
[log.txt](https://github.com/z-huang/music/files/8598544/log.txt)

**Comment by z-huang** [comment]
It seems that the cause is similar with #38. Try this commit 1c918333cdeb33b4c03843be3134569779bd39ab and tell me if this solves the bug.
