### ISSUE TITLE
[BUG] Too slow to load first song

### ISSUE THREAD

**Issue by airon90** [z-huang/music#48]
**To Reproduce**
1. Have a lot of songs in the library (actually I have 2177 songs)
3. Click on a song in a library to play
4. Wait for 20 seconds before app starts loading the song. Sometimes a freeze warning pops out 

**Information:**
 - Device: Xiaomi Redmi Note 8T
 - Android version: MIUI EU 12.5.2
 - Music version: F-Droid latest

**Additional context**
[log.txt](https://github.com/z-huang/music/files/8598564/log.txt)

**Comment by z-huang** [comment]
The player will first fetch all songs into the playing queue, that's why it's slow.
A lazy load measure should be taken.
