### ISSUE TITLE
Length of long music (like audiobooks, >1 hour long) is shortened in player, though full song plays

### ISSUE THREAD

**Issue by nikhilCad** [z-huang/music#49]
**Describe the bug**
Look at screenshot. You can find audiobooks by going to "Videos" section after searching. The actual length is 6:35:19 but its shown as 6:35 only(Which might get confused as 6 minutes 35 seconds)(though full book plays)
![Screenshot_20220502-205418](https://user-images.githubusercontent.com/47214394/166261249-e7fd40f1-13df-409b-b6d8-c62a90108174.png)

If you look at this screenshot, it shows 0:51 as played out of 6:35. Only 51 seconds out of 6 hour 35 minutes are played, but the placing of those digits makes it look like 51 minutes has been played.

**To Reproduce**
1. Play any song with length in hours
2. See duration on Player

**Information:**
 - Device: Moto E7 Power
 - Android version: 10
 - Music version: 0.2.1

**Additional context**
I know the app is not good for audiobooks as no player position is saved but just noticed this and reported anyways.

**Comment by z-huang** [comment]
The problem is that the textview's width doesn't change when the length of the text has changed. It's kind of weird. I'm still finding ways to solve it.
