### ISSUE TITLE
[BUG] Merge artists with same name

### ISSUE THREAD

**Issue by airon90** [z-huang/music#50]
If you have two songs with different artist in the library, e.g. A1 and A2, and you rename one artist's name (e.g. A1) to the second one (e.g. A2) the app doesn't merge the artists but the app keeps on maintaining two different artists with same name instead of merging both in a single artist

**Comment by z-huang** [comment]
Does it still happen?
In my phone, this function works well.

**Comment by airon90** [comment]
I downloaded the artifact from Actions page and it still happens. Here are the steps to reproduce this bug:

1. Add two songs from two different artists (I have some artists named "X" and "X - Topic")
2. Go to the Artists section
3. Rename one artist to the second one
4. You get two different artists with same name and in two different categories

**Comment by z-huang** [comment]
Oh, the app should forbid having two artists with the same name.
I think you want the feature to merge the songs of two artists together, right? Artists in YouTube Music become "Artist - Topic" in YouTube.

**Comment by airon90** [comment]
> I think you want the feature to merge the songs of two artists together, right?

Yes

**Comment by z-huang** [comment]
Implemented. You can try the latest dev build.

**Comment by airon90** [comment]
Now I will wait without patience for next version 😍 Thank you very much!
