### ISSUE TITLE
[BUG] Bottom player covers bottom menu

### ISSUE THREAD

**Issue by eumunhoz** [z-huang/music#52]
**Describe the bug**
When playing a song, the bottom player completely covers the bottom menu with a white bar, making it impossible to navigate the app during playback

**To Reproduce**
1. Play a song
2. Bottom menu is now inaccessible

**Information:**
 - Device: Xiamoi Redmi 7A
 - Android version: 12
 - Music version: 0.2.1-beta

**Additional context**
![image](https://user-images.githubusercontent.com/24512504/166557646-cf3482fa-140c-4424-be6c-8a164299d598.png)

**Comment by z-huang** [comment]
Does this happen in older versions?

**Comment by eumunhoz** [comment]
In older versions I couldn't play songs because of the now fixed Issue #6, so I'm not able to tell

**Comment by z-huang** [comment]
Let me study other apps about how they achieve bottom sheets behind bottom navigation bar.

**Comment by z-huang** [comment]
This issue is different from #31. #31 is that the bottom of the content is covered by the bottom player sheet. This issue is that the bottom player sheet covers the bottom navigation bar.

**Comment by eumunhoz** [comment]
After a system update the bug has stopped, so I assume it wasn't an issue with the app after all but my system instead. Thanks for your attention :)

**Comment by z-huang** [comment]
Thanks!
