### ISSUE TITLE
[BUG] Playback position not shown properly

### ISSUE THREAD

**Issue by eumunhoz** [z-huang/music#53]
**Describe the bug**
When playing a song the playback position is always shown as the track duration. In contrast, when pausing the song the playback position is shown correctly.

**To Reproduce**
1. Play a song
2. Expand bottom player
3. See error

**Information:**
- Device: Xiamoi Redmi 7A
- Android version: 12
- Music version: 0.2.1-beta

**Additional context**
Playback position at 0:15 when the song is playing (incorrectly displayed)
![image](https://user-images.githubusercontent.com/24512504/166558547-07b1a84a-3d71-4e5a-ae6e-b533713b2e65.png)

Playback position at 0:15 when the song is paused (correctly displayed)
![image](https://user-images.githubusercontent.com/24512504/166559099-3d137058-224b-4a60-80c8-5c3af76288a2.png)

**Comment by z-huang** [comment]
Does this happen in older versions?

**Comment by eumunhoz** [comment]
In older versions I couldn't play songs because of the now fixed Issue #6, so I'm not able to tell

**Comment by z-huang** [comment]
Thanks!
