### ISSUE TITLE
[BUG] Searching without an Internet connection leads to a crash

### ISSUE THREAD

**Issue by airon90** [z-huang/music#55]
**Describe the bug**
Suddenly my wifi connection broke and Music crashed while I was searching for a song.

I suggest to add a method to determine if Internet connection is off (turned off or not working) and to display an error

**To Reproduce**
1. Open Music
2. Play a song (maybe optional)
3. Turn off any kind of connection (wifi and 4G)
4. Search for a song in Explore section

**Information:**
 - Device: Xiaomi Redmi Note 8T
 - Android version: Latest MIUI EU 12.5.2
 - Music version: latest F-Droid version

**Comment by z-huang** [comment]
Have you tried the latest dev version? I think it is solved in #38.

**Comment by airon90** [comment]
I confirm that this is fixed in latest dev version. Closing this bug
