### ISSUE TITLE
Data backup

### ISSUE THREAD

**Issue by Alliba** [z-huang/music#57]
Cool would be a way to save the artists and playlists.

I am planning to change my phone. As it stands now, I have to recreate all artists and playlists on the new phone. At this point a backup would be really useful to save the work.
Offer add such an option, please 👃

**Comment by z-huang** [comment]
I've flashed a MIUI EU rom today. It seems that Google backups and restores the database automatically, but downloaded files won't be restored.

**Comment by z-huang** [comment]
Done. If you find any bug, tell me.
