### ISSUE TITLE
Switch song with swipes will stop working (compose ver.)

### ISSUE THREAD

**Issue by netrunner-exe** [z-huang/music#573]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Play any song
2. Tap "Start radio"

### Expected behavior

Working "Start radio"

### Actual behavior

Switch song with swipes will stop working, but the switch button will work. Album art will not change when switching tracks, in some cases there will be a blank background instead. If you swipe down and open again, the problem disappears. See the video for more details.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/81887288/218144563-40dc0150-379b-4b97-85e1-066c4ebcf5ae.mp4

### Music version

Apk was taken from "Build debug APK #861"

### Android version

Poco M4 Pro 4G, Miui 13, A12

### Additional information

I also compiled the apk from the "compose" branch on my PC, this bug is also present.

**Comment by z-huang** [comment]
Is it fixed in febfa141d4c3cc9ab80a281cdc11c57c83d09884?

**Comment by z-huang** [comment]
It's still not stable. I'll try another way to implement it.
