### ISSUE TITLE
Continue playback when switching connection

### ISSUE THREAD

**Issue by teemue** [z-huang/music#61]
If i'm home, connected to home wifi and music is playing and then I leave and mobile data is activated, playback will stop and the progress halts. The song needs to be started at the beginning.

**Comment by z-huang** [comment]
If you click the play/pause button, the progress will continue.

**Comment by owencz1998** [comment]
Sometimes happens when your in a bad area with bad connection would be cool for it to automatically start playing from where it was but it's not a issue or a feature that's needed 😄
