### ISSUE TITLE
Beta apk 

### ISSUE THREAD

**Issue by owencz1998** [z-huang/music#63]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Could you make an beta apk so whenever a new feature or fix has been added it will be added straight to the app :)

### Why do you want this feature?

Be cool to have constant updates 😁

**Comment by z-huang** [comment]
You can download the latest build in GitHub Action. For any workflow, it will produce a zip of an apk.

**Comment by z-huang** [comment]
Or do you mean another update channel?
Namely, a built-in updater that automatically checks for the latest GitHub Action build?

**Comment by nikhilCad** [comment]
Slightly unrelated, but can you change Actions workflow to upload release apks as well, here https://github.com/skyline-emu/skyline/actions release apks are also posted in Actions. They are faster than Debug one.

**Comment by owencz1998** [comment]
Yeah another update channel with built in updater and a option to have beta or full release so if I'm on beta it gets all the features and fixes straight away would be cool 😎

**Comment by z-huang** [comment]
I won't do this because having another update channel means more maintain effort.

**Comment by z-huang** [comment]
Also, artifacts from GitHub Action can't be downloaded if you're not logged in. Therefore, it's impossible to download apks from the app.
