### ISSUE TITLE
Music does not play 

### ISSUE THREAD

**Issue by edl2** [z-huang/music#64]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Open app
Search song
Click the song 

### Expected behavior

Song should play 

### Actual behavior

Song does not play. Pause putton stays paused even when clicked.

### Music version

0.2.1-beta.6

### Android version

Android 11

**Comment by z-huang** [comment]
Which song you can't play? Is every song unplayable?

**Comment by edl2** [comment]
> Which song you can't play? Is every song unplayable?

No songs work at all. trying to download or add to playlist causes a crash.

**Comment by z-huang** [comment]
1. Can you provide the log of the crash?
2. Try the latest dev version and see if the problem is solved.

**Comment by z-huang** [comment]
@senolfndk What do you imply? You need to add songs to your library by searching from the explore section.

**Comment by senolfndk** [comment]
app crashes while searching

https://user-images.githubusercontent.com/52818836/171324092-24082d00-7ca4-4635-a2b9-180829ea1ab6.mp4

**Comment by senolfndk** [comment]
> Bununla ilgili başka bir konu oluşturabilir misiniz? Mümkünse, `adb logcat`günlükleri sağlamak için kullanmak çok yardımcı olacaktır!

ok

**Comment by owencz1998** [comment]
I updated the app from 0.3.0 to new release and after that all my downloaded music would not work so had to remove music downloads and redownload it again to work.

**Comment by z-huang** [comment]
Strange. I reinstalled the app from 0.3.0, downloaded some songs, and update to 0.3.1, but the downloaded songs still can play.
