### ISSUE TITLE
Browse category songs

### ISSUE THREAD

**Issue by MrConqueror** [z-huang/music#68]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Could you add Category in Search bar, such as OPM, Christian songs, POP, something like that.

### Why do you want this feature?

it's helpful to browse within the app

**Comment by z-huang** [comment]
Implemented, provided by YT Music.
![1660565433587](https://user-images.githubusercontent.com/39427017/184632759-008f594f-b81b-4030-be8b-2c1afc2f418c.jpg)

**Comment by MrConqueror** [comment]
where, i download the app theres no such feature

**Comment by MrConqueror** [comment]
> Implemented, provided by YT Music. ![1660565433587](https://user-images.githubusercontent.com/39427017/184632759-008f594f-b81b-4030-be8b-2c1afc2f418c.jpg)


Uploading Record_2022-08-18-09-56-17.mp4…

**Comment by z-huang** [comment]
Download `featute/innertube` debug apk.
