### ISSUE TITLE
Unable to search anything

### ISSUE THREAD

**Issue by nikhilCad** [z-huang/music#7]
OS : Android 10
Model : Motorola E7 Power

https://user-images.githubusercontent.com/47214394/162607729-ab3c5e8a-3129-4072-b1e0-649ff5c9b881.mp4

**Comment by nikhilCad** [comment]
No wait. I am an idiot. You are supposed to search in the "Explore" section only. That works. Maybe explore section should be made default from UI/UX perspective, because its pretty confusing. Closing.

**Comment by z-huang** [comment]
I've predicted that this would happen to someone. It's confusing to a new user, I agree. So, in the future, I will combine searching from local and youtube together. The search button anywhere will act the same. Under the search fragment, a tab will be used to choose whether to search from YouTube or local database.😃

**Comment by airon90** [comment]
You can set Explore section as first tab everytime Songs section is empty

**Comment by z-huang** [comment]
You can add songs to the Song section, see #9. YT Music feed extractor isn't implemented, so the Explore section only serves search function. So, I think Song section being the first tab provides better experience in this stage.
