### ISSUE TITLE
The app (dev) is sluggish and sometimes freezes

### ISSUE THREAD

**Issue by netrunner-exe** [z-huang/music#734]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Normal everyday use of the app

### Expected behavior

Less freezes and freezes, more thoughtful removal of tracks from the playlist

### Actual behavior

The app freezes and lags even on the flagship device, tracks are deleted from the playlist very easily and without warning or the ability to cancel the action.

### Screenshots/Screen recordings
I tried to record the screen with freezes, of course this does not fully convey what I mean, but on the device itself it is very clearly visible, especially if you turn the screen frequency 90hz

https://github.com/z-huang/InnerTune/assets/81887288/191a345e-d6b8-46b6-a49d-2e8bad54263a

### InnerTune version

Latest dev debug

### Android version

App tested on A11, A12 and A13

### Additional information

Hi @z-huang! Very glad that after a break the work on the application continues, I really like to use InnerTune - the best both in terms of convenience and design! I understand that dev app is still in development, but on my devices the dev app is acting a little sluggish and freezes, especially when compared to the old version (from master branch), although I have 8 GB of RAM and not the weakest CPU. Also, there is another problem - from the playlist is very easy to delete swipe tracks. Just move your finger slightly to the side and the track is deleted without warning and the ability to undo the action. Just today, swiping through the playlist, accidentally deleted two tracks before I could even see which ones. Thank you for your hard work!

**Comment by oathzed** [comment]
Mate you should make a separate issue about that additional information about the playlist swipe thing. I agree but it might get lost in this issue

**Comment by Engaging4715** [comment]
Same issue here. Probably has to do with it being a debug version

**Comment by z-huang** [comment]
Stable builds have better performance, but some lags still exist. Some features may lead to the reduction of performance such as showing the playing indicator and the download badges. After all, I'm not an experienced Android developer, and I may not be able to fix the performance issue. However, if we can get important features by sacrificing some performance, I'll do it.
Of course, any PR to optimize the app is welcome.
