### ISSUE TITLE
Play last song again by tapping on play button after the last track in a playlist or an album has finished playing

### ISSUE THREAD

**Issue by netrunner-exe** [z-huang/music#741]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

At the moment, when the last song in the album or playlist finishes playing and no "Repeat" or "Repeat All" buttons are set, the play button just goes into a stopped state and there is no other action for it once pressed. I propose that it should be the same as now, but after playing to the end of the last song in the album or playlist (as long as the "Repeat" or "Repeat All" buttons are not activated), the player would switch to the beginning of the first song in the playlist and pause. (That is, we could just press the play button again and the playlist would start playing again from the first song) This approach was implemented in Deezer. Or alternatively, under the same conditions, pressing the play button again would start playing that last track from beginning (at least I haven't seen this feature yet).

### Why do you want this feature?

It seems to me that it would be a useful and convenient feature. It would be interesting to know your opinion, what you think about these two ideas and which one is better

**Comment by z-huang** [comment]
I'd like to replay from the first song of the playlist.
