### ISSUE TITLE
Renaming an artist can lead to lose songs from library

### ISSUE THREAD

**Issue by airon90** [z-huang/music#75]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Select Artist section
2. Select an artist and press Rename
3. Press Ok without changing the name of the artist

### Expected behavior

Nothing should change

### Actual behavior

A message will popup advising that there already is an artist with same name and if you merge all songs from that artist disappear from the library

### Music version

Latest from F-Droid

### Android version

MIUI 12.5

**Comment by z-huang** [comment]
Oops, sorry.
Fixed in 379d62570f1966a2032c0bdddb30f1e6c1c15de9.
