### ISSUE TITLE
Bookmark playlist

### ISSUE THREAD

**Issue by max5354** [z-huang/music#81]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

add option to bookmark playlists (so we don't need to frequently search for playlists we can directly play from bookmark playlists option).

### Why do you want this feature?

It's important

**Comment by z-huang** [comment]
"Add to library" fits your need.

 "Add to library" creates a link to browse the YT playlist, so it's always synced, but you can't edit. "Import playlist" copies the playlist into your phone. It's not synced, but you can edit.
![1660564954810](https://user-images.githubusercontent.com/39427017/184631750-fdd57c58-03c8-4a48-b137-c560b099d65b.jpg)
