### ISSUE TITLE
Create Telegram group.

### ISSUE THREAD

**Issue by max5354** [z-huang/music#86]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

please make one Telegram group so we can discuss about bugs and features request. And you can give faster reply in telegram. Github have too much process to just report bug or request features.

### Why do you want this feature?

It's necessary

**Comment by Alliba** [comment]
this is a good idea

**Comment by Alliba** [comment]
that's OK too

**Comment by max5354** [comment]
> this is a good idea

So when will you create telegram group.

**Comment by z-huang** [comment]
I mean GitHub Discussions [here](https://github.com/z-huang/music/discussions), for simple questions.

> But github have too much process to features request and bug reports.

I think a strict process to propose a feature request or report a bug is necessary. If these things are proposed in a chat-room way, it's hard to filter them out and manage the issues seperately. I like GitHub's system to manage the project. Also, this is a side project for me. I'm not always available to reply for messages.

**Comment by z-huang** [comment]
Me too. I wish I can keep developing it.😊
