### ISSUE TITLE
Music not adding to library from Playlist search

### ISSUE THREAD

**Issue by nikhilCad** [z-huang/music#9]
Search anything on Explore, go to "Playlists" tab of the search and press add to library on any song. It won't add. Interestingly it looks like songs without a playlist are getting added.

**Comment by z-huang** [comment]
Isn't that every song you search can't be added to library?
That may because the folder storing artworks isn't checked to be created.
This commit may fix the issue: f81e8e42cc601abd5fcb1c397004290b68d073a9.

**Comment by nikhilCad** [comment]
Song inside the playlist tab of search dont get added but songs without a playlist(I.e. those who directly appear in search result without opening any playlist) get added

**Comment by z-huang** [comment]
Oh, the popup memu listener is missing.
This commit will fix it: f3f12dc5f0ce0a4886d5618bb74d9c9726e78f9a
I've tested myself, it should work fine now.

**Comment by nikhilCad** [comment]
Thanks, closing issue
