### ISSUE TITLE
[FEATURE] Use Piped API

### ISSUE THREAD

**Issue by IceDBorn** [z-huang/music#90]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Use the Piped api instead of NewPipeExtractor.

### Why do you want this feature?

It would be great if I could sync my songs etc. with Piped.

**Comment by z-huang** [comment]
I didn't find the API to get user data from Piped.
Also, Piped use NewPipeExtractor as the backend. It's clean to communicate directly to YouTube without any proxy. Not considering to use Piped API in current stage.
