### ISSUE TITLE
Hide status bar.

### ISSUE THREAD

**Issue by max5354** [z-huang/music#91]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add option "hide status bar" so we can use this app in full screen.

### Why do you want this feature?

I think it's useful.

**Comment by z-huang** [comment]
Full screen mode is used when, say, watching video in landscape mode. Hiding the status bar avoid users from getting basic information such as time, notifications and battery percentage. Why is it useful?
