### ISSUE TITLE
Song unplayable after dismissing player notification

### ISSUE THREAD

**Issue by github-user93** [z-huang/music#998]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. play a song, any song
2. pause song and dismiss the player notification
3. now try to re-play the song
4. does not re-open player notification
5. does not play anything, need to restart app for it to play again.

I'm using Redmi note 7 pro, android 10, miui 12.5.1

### Expected behavior

it should re-open the player notification and play songs again

### Actual behavior

nothing happens, song does not play, and no player notification

### Screenshots/Screen recordings

https://github.com/z-huang/InnerTune/assets/127530649/9d69ba00-b15e-4f2e-96ba-1b1c4e97a586

### InnerTune version

0.5.2 debug

### Android version

Android 10

**Comment by d4f5409d** [comment]
Sometimes I have a similar problem, occasionally I can't play some songs and the app skips a whole bunch of songs until finally one of them gets played. If I restart the app 2 or 3 times, it works again for some time.

**Comment by MLZ94** [comment]
After https://github.com/z-huang/InnerTune/commit/4864572f8bbc6933ed536b1a342f8178fc9f04d1 we can indeed play the song again after masking the player. But now, after masking the player, the music stops, but the play button is still on "play" state, so we have to hit pause and play again to resume the music. The normal behavior should be that when the player is masked and the music stops, the play/pause button switches to "pause" state so that we can resume the music with one click.

**Comment by z-huang** [comment]
Sorry, what exactly does "masking the player" mean?

**Comment by MLZ94** [comment]
It refers to when we force stop the music player in the notification panel. I'll send a screen record in some minutes 

> Sorry, what exactly does "masking the player" mean?

**Comment by MLZ94** [comment]
Uploading screen-20230831-170021.mp4…

**Comment by MLZ94** [comment]
https://github.com/z-huang/InnerTune/assets/76778799/adaea694-901f-470f-9fcd-2cc563bce67c

**Comment by d4f5409d** [comment]
> 
> https://github.com/z-huang/InnerTune/assets/76778799/adaea694-901f-470f-9fcd-2cc563bce67c
> 
> 

Yeah I had the same issue here

**Comment by MLZ94** [comment]
> In my Android 13 emulator, I have to pause the music first in order to hide the player notification. After hiding the notification, I can resume the playback in the app.
> 
>  default.mov

Interesting... well i don't know why but it doesn't behave like actual pixel builds. The build i use in my screen rec is the stable a13 build for pixel 6 with latest security patch (August, TQ3A.230805.001). And it is actually possible to hide the notification player while the music is playing *for InnerTune*. I just figured that in Spotify for example, it behaves like on the emulatore and the music needs to be stoped to hide the player... No idea what's differend in Spotify, but with my little knowledge, i think it's a better option to just switch to the pause state when the service is closed from notification player.

**Comment by MLZ94** [comment]
https://github.com/z-huang/InnerTune/assets/76778799/c86b8b53-607f-41e1-9465-05096b0fc510

Here is a comparison between how Spotify player behaves while playing and how InnerTune's one does
